export type CaseStudy = {
  slug: string;
  title: string;
  place: string;
  region: "UK" | "US" | "Shared";
  labs: string[];
  lede: string;
  body: string[];
  exam: { prompt: string; hint: string };
  lat: number;
  lon: number;
  zoom: number;
  sources: { label: string; href?: string }[];
  /** Query string (no ?) that restores a teaching frame in the first lab. */
  state?: string;
};

export const CASES: CaseStudy[] = [
  {
    slug: "uk-daylength",
    title: "UK seasonal day length",
    place: "London to Lerwick",
    region: "UK",
    labs: ["seasons", "solar-altitude"],
    lat: 51.51,
    lon: -0.13,
    zoom: 4,
    state: "t=0.973&step=2&tilt=23.44",
    lede: "On the December solstice London keeps the Sun for about 7 h 50 m. Lerwick, in Shetland, keeps it for under six. Florida, near 28°N, still has a winter — but noon Sun stays high.",
    body: [
      "The difference is latitude on a tilted axis, not distance to the Sun. Earth’s orbit is only slightly elliptical. Perihelion — nearest the Sun — falls in early January, during northern winter. If distance caused seasons, London and Sydney would share summer. They do not.",
      "At 51.5°N, London’s noon solar altitude on the December solstice is about 15°. On the June solstice it is about 62°. Day length swings from under eight hours to about 16.5. Walk north to Lerwick, near 60°N, and the December day falls below six hours; June barely gets dark. The same geometry, stretched.",
      "A-level and AP students can treat this as insolation: the solar constant is the same. Incidence angle and duration are not. The energy received on a square metre of playground in December is a sliver of the June figure, even under a clear sky. UK solar farms know this in their yield curves. Field teachers know it in the last period on a winter Friday.",
      "Compare Miami, near 26°N. December noon altitude stays above 40°. The day shortens by a couple of hours, not eight. Growers in the Central Valley care about hours above a useful incidence angle — the same number UK horticulture cares about under glass. Tilt, not orbital distance, is why a Californian December is not a British one.",
      "Classroom move: freeze the seasons lab on 21 December. Read London’s day length, then Sydney’s. Ask which hemisphere is leaning toward the Sun before you reveal the tilt callout. Then scrub to June. The terminator walk is the whole argument.",
    ],
    exam: {
      prompt: "Explain why Lerwick’s December day is shorter than London’s, using axial tilt rather than distance from the Sun.",
      hint: "Latitude on a 23.44° axis. December: northern hemisphere leans away. Higher latitude → Sun lower and path shorter.",
    },
    sources: [
      { label: "Met Office — UK day length" },
      { label: "NOAA Solar Calculator", href: "https://gml.noaa.gov/grad/solcalc/" },
    ],
  },
  {
    slug: "florida-insolation",
    title: "Florida and California insolation",
    place: "Miami · Central Valley",
    region: "US",
    labs: ["seasons", "energy-budget"],
    lat: 25.76,
    lon: -80.19,
    zoom: 5,
    lede: "Miami in December still sees the Sun more than 40° up at noon. London does not. Same star, different incidence.",
    body: [
      "Insolation is incoming solar radiation at the surface. It depends on the solar constant, the angle of incidence, day length, and what the atmosphere and the ground do with the beam. The seasons lab isolates the first geometry: tilt. The energy-budget lab adds albedo and longwave.",
      "At the December solstice the Sun is overhead at 23.44°S. Miami, at about 26°N, still has a noon altitude near 40°. Day length is close to 10.5 hours. London’s noon altitude is about 15° and the day is under eight hours. Photosynthesis, heating load, and solar yield follow those numbers, not the calendar month.",
      "California’s Central Valley sits near 36°N. Winter days are short enough to matter for fog and for solar, long enough that citrus still works with irrigation. Summer days are long and noon Sun is high — a different energy budget from a Lake District valley at the same season.",
      "Students often say ‘Florida is closer to the Sun.’ It is not, in any sense that matters. Florida is closer to the subsolar latitude in northern winter than London is. That is a tilt-and-latitude sentence, not a distance sentence.",
      "Use the solar-altitude lab with Miami, London, and Nairobi marked. Scrub the date. Nairobi, on the equator, barely changes day length. Miami swings moderately. London swings hard. The three traces are the curriculum.",
    ],
    exam: {
      prompt: "Using noon solar altitude, explain why Miami’s December energy receipt exceeds London’s even on a cloudless day.",
      hint: "Incidence angle. Same solar constant; Miami’s beam is steeper, the day is longer.",
    },
    sources: [
      { label: "NOAA / NREL typical meteorological year" },
      { label: "NASA Earth Observatory — insolation" },
    ],
  },
  {
    slug: "holderness",
    title: "Holderness coast",
    place: "East Yorkshire",
    region: "UK",
    labs: ["coasts"],
    lat: 53.73,
    lon: -0.05,
    zoom: 9,
    state: "step=2",
    lede: "Soft glacial till, a north-to-south longshore system, and villages that have already gone into the North Sea.",
    body: [
      "Holderness is the standard UK coastal case because the process is fast enough to see in a school lifetime. The cliffs are mostly glacial till — boulder clay dumped by ice, not lithified rock. Wave attack at the foot, sub-aerial weathering above, and a mass movement that is often a slump rather than a clean fall. Average erosion rates of one to two metres a year are widely cited from East Riding monitoring; locally the number is higher after a storm cluster.",
      "The dominant wave approach is from the north-east. Swash runs up the beach at an angle; backwash returns down the steepest slope. Sediment therefore moves south in a longshore-drift conveyor. Spurn Head is the textbook spit at the southern end: a sand-and-shingle finger built where the coast turns into the Humber, with saltmarsh in the lee. It is not immortal. Storms breach it. The river and the sea then argue about where the mouth sits.",
      "Mappleton’s rock groynes, placed in 1991, are a choice about whose beach is allowed to keep sand. Up-drift of a groyne, the beach widens. Down-drift, the supply is starved and erosion can accelerate. That is the classic ‘protection here, problem there’ sentence. Withernsea and Hornsea have sea walls and groynes of their own. Skipsea and the sites of lost villages such as Ravenser Odd sit on the other side of that bargain.",
      "Constructive waves, with a strong swash, build a wider beach when the till supply and the drift allow it. Destructive waves, steeper, drag material back and attack the cliff. The Holderness fetch across the North Sea can throw destructive waves at a soft cliff for hours. Management options — do nothing, hold the line, managed realignment — are political, not just physical. The physics does not care about a caravan park. The budget does.",
      "Compare a US barrier: the Outer Banks of North Carolina. There the sediment is sand in a barrier-island chain, not till in a cliff. Longshore drift still moves material alongshore. Storms still punch inlets. The landform is different; the budget idea is the same. Students who can say ‘supply, transport, deposition, interruption’ can move between Holderness and the Banks without learning a new subject.",
      "Classroom move: run the coasts lab, turn on longshore particles, then freeze on the spit. Ask where a groyne would starve the spit. Then open this locator and point at Mappleton and Spurn. The 3D model is the process; this map is the place.",
    ],
    exam: {
      prompt: "Explain how longshore drift and groynes together change the sediment budget of Holderness, using Mappleton and Spurn Head.",
      hint: "NE waves → southward drift. Groynes trap up-drift, starve down-drift. Spurn is the depositional end-member.",
    },
    sources: [
      { label: "BGS — Holderness coastal erosion" },
      { label: "East Riding of Yorkshire coastal monitoring" },
      { label: "Environment Agency shoreline management" },
    ],
  },
  {
    slug: "jurassic-coast",
    title: "Jurassic Coast",
    place: "Dorset and East Devon",
    region: "UK",
    labs: ["coasts", "rock-cycle"],
    lat: 50.62,
    lon: -2.25,
    zoom: 8,
    lede: "A World Heritage rock sequence, and a coastline that writes cave–arch–stack–stump in Lias and chalk.",
    body: [
      "The Jurassic Coast is a teaching gift because lithology changes along the shore. Harder bands stand as headlands; weaker bands cut back as bays. Concordant and discordant patterns both appear. Durdle Door is an arch in limestone. Old Harry Rocks are chalk stacks off the Foreland. Lulworth Cove is a bay cut through a hard band into softer Wealden clays behind.",
      "The cave–arch–stack–stump sequence needs a headland, joints or bedding the sea can exploit, and enough energy to keep working the same lines. Hydraulic action, abrasion, and attrition do the cutting. Weathering opens the joints from above. When the arch roof fails, a stack stands. When the stack fails, a stump sits in the surf. The lab animates that sequence; this coast is where UK students are taken to see it in rock.",
      "Landslides at Black Ven and Stonebarrow remind a class that coasts are not only waves. Rain, groundwater, and a clay layer can send a whole undercliff toward the beach. The 2012 landslip near Bridport closed the coast path. Process on a cliff is always two-sided: marine at the toe, sub-aerial on the face.",
      "Tourism, fossil collecting, and shoreline management sit on top of the geology. Students should not be asked to memorise every cove. They should be able to match a named landform to a process and a rock type, then say what happens if the energy or the lithology changes.",
    ],
    exam: {
      prompt: "Using a named Jurassic Coast landform, describe the sequence from cave to stump.",
      hint: "Joints → cave → arch (Durdle Door) → collapse → stack (Old Harry) → stump.",
    },
    sources: [
      { label: "Jurassic Coast Trust / UNESCO" },
      { label: "BGS — Dorset coast" },
    ],
  },
  {
    slug: "lake-district",
    title: "A UK upland river",
    place: "Lake District",
    region: "UK",
    labs: ["rivers", "glaciers", "contours"],
    lat: 54.45,
    lon: -3.09,
    zoom: 9,
    lede: "Steep glacially-overdeepened valleys, waterfalls on resistant bands, and a short run to a lake or the Irish Sea.",
    body: [
      "A Lake District beck in spate is the upper course of the rivers lab made walkable. Gradient is steep. The channel is narrow. Vertical erosion cuts a V into a valley that ice had already overdeepened into a U. Waterfalls sit on resistant bands — Borrowdale volcanic rocks, Skiddaw slates, granite — with plunge pools and retreat of the nick point.",
      "Upper-course landforms sit close together. Students can stand at a waterfall and look downstream to a ribbon lake. The long profile is short. There is often no classic delta, because the load meets a lake or a tide that can take it. Compare the Mississippi: same processes, different scale and a different coast.",
      "Contour Vs in the valley floors are the same Vs as in the contours lab. A spur between two becks shows Vs pointing downhill. A stream in a trough shows Vs pointing uphill. OS Explorer interval is 10 m. The 3D hill in the contours lab is this skill without the sheep.",
      "Ice is the older author. Cirques (cwms), arêtes, and a pyramidal peak sit above the fluvial work. Helvellyn’s Red Tarn is a cirque lake. Striding Edge is an arête. The river lab does not invent those; the glaciers lab does. A good path walks ice first, then water.",
    ],
    exam: {
      prompt: "Explain why a Lake District valley may be U-shaped in cross-profile but still host a V-shaped inner channel.",
      hint: "Glacial trough, then post-glacial stream cutting a V into the floor.",
    },
    sources: [
      { label: "OS / BGS Northern England" },
      { label: "National Trust / Lake District National Park" },
    ],
  },
  {
    slug: "snowdonia",
    title: "Snowdonia / Eryri",
    place: "North Wales",
    region: "UK",
    labs: ["contours", "glaciers"],
    lat: 53.07,
    lon: -4.08,
    zoom: 11,
    lede: "A classroom-perfect contour map: cwms, arêtes, a pyramidal peak, and a railway that cheats the gradient.",
    body: [
      "Closed loops around Yr Wyddfa; V-shapes in the cwms. Interval on OS Explorer is 10 m. The same hill in 3D is the point of the contours lab. Spot heights sit on the summit and on the ridges. Tight contours on the east face are a steep drop; wider contours on some western approaches are a gentler slope — until they are not.",
      "Glacial landforms do the naming. A cirque is a armchair hollow with a steep backwall. An arête is a knife ridge between two cirques. A pyramidal peak is three or more cirques eating a mountain from different sides. Crib Goch is an arête students remember with their hands. Glaslyn and Llyn Llydaw sit in scooped rock.",
      "The railway is a sentence about gradient. A contour skill that can explain why a train hairpins is a skill that will survive the map paper. Grid references on this sheet are the grid-references lab’s natural homework.",
      "Compare Yosemite: a deeper U, granite, hanging valleys, and a rim that reads as coincident contours. Same ice logic, different rock and a different national-park poster.",
    ],
    exam: {
      prompt: "On an OS-style extract of Yr Wyddfa, how would you distinguish a cirque from a spur using contours alone?",
      hint: "Cirque: steep backwall, closed or tight curves around a hollow. Spur: Vs pointing downhill.",
    },
    sources: [
      { label: "Ordnance Survey" },
      { label: "BGS Wales" },
    ],
  },
  {
    slug: "yorkshire-dales",
    title: "Yorkshire Dales karst",
    place: "North Yorkshire",
    region: "UK",
    labs: ["karst", "weathering"],
    lat: 54.15,
    lon: -2.15,
    zoom: 9,
    lede: "Carboniferous limestone, clints and grykes, swallow holes, and caves that take a whole beck underground.",
    body: [
      "Karst is what happens when carbonation and jointing get ahead of surface drainage. Rainwater picks up carbon dioxide and becomes a weak carbonic acid. It works on calcium carbonate along bedding and joints. The surface becomes a limestone pavement: clints (blocks) and grykes (fissures). A stream that meets a swallow hole leaves the surface. It may return as a resurgence kilometres away.",
      "The Yorkshire Dales are the UK’s classroom for this. Malham Cove’s pavement is walked by GCSE groups every spring. Gaping Gill takes Fell Beck into a chamber high enough for a cathedral, then the water moves through the cave system toward Ingleborough’s flanks. Gordale Scar is a different argument — a gorge, possibly a collapsed cavern or a glacial meltwater cut, still debated, still useful.",
      "Soil is thin. Weathering is chemical first, mechanical on the frost days. Farmers talk about limestone in the same breath as drainage. Students should be able to sequence: rainfall → carbonation → widened joints → swallow hole → cave passage → stalactite if the drip has time.",
      "Mammoth Cave, Kentucky, is the US pair: a longer, lower-gradient carbonate system in the Mississippian limestones of the Chester Upland. Same chemistry, a different map scale. The karst lab’s pavement, sinkhole, and cave passage are both places.",
    ],
    exam: {
      prompt: "Explain how a swallow hole forms and what it implies for the drainage network on Carboniferous limestone.",
      hint: "Carbonation along joints. Surface stream captured underground. Watershed on the surface may not match the cave.",
    },
    sources: [
      { label: "BGS — Yorkshire Dales karst" },
      { label: "Natural England / Malham" },
    ],
  },
  {
    slug: "somerset-levels",
    title: "Somerset Levels",
    place: "Somerset",
    region: "UK",
    labs: ["hydrograph", "rivers", "drainage-basin"],
    lat: 51.13,
    lon: -2.83,
    zoom: 9,
    lede: "A low floodplain, peat and clay, pumped drainage, and a hydrograph that goes wrong when rain sits on saturated ground.",
    body: [
      "The Somerset Levels are a flood story written on a almost-flat long profile. Rivers such as the Parrett and Tone meander across peat and clay. Gradient is tiny. When rain is heavy and the ground is already wet, there is nowhere for water to go but up and out. The 2013–14 floods sat on villages for weeks. That is a hydrograph with a fat falling limb, not a flashy upland peak.",
      "Land use matters. Drained pasture, rhynes (ditches), pumps, and a few raised towns. Urban surfaces upstream shorten lag. Saturated peat does not infiltrate. High tide in the Parrett can hold fluvial water back — a reminder that a drainage basin has a mouth with its own schedule.",
      "Management is a choice among dredging, pumping, wetland restoration, and ‘making space for water’. Each changes a different part of the hydrograph. Dredging argues about channel efficiency. Restoration argues about storage on the floodplain. Students should be able to sketch both and say who wins in a wet January.",
      "Pair with the Mississippi: levées, cut-offs, and a bird-foot delta. Same machine, continental scale. The Levels are the UK size of that argument.",
    ],
    exam: {
      prompt: "Using the idea of lag time, explain why the Somerset Levels can stay flooded long after the rain has stopped.",
      hint: "Low gradient, saturated peat, tide lock, limited storage exit. Long falling limb.",
    },
    sources: [
      { label: "Environment Agency — Somerset" },
      { label: "UKCEH hydrology" },
    ],
  },
  {
    slug: "thames",
    title: "Thames and Severn",
    place: "Southern Britain",
    region: "UK",
    labs: ["water-cycle", "drainage-basin", "river-hydrology"],
    lat: 51.5,
    lon: -0.12,
    zoom: 7,
    lede: "Two basins, heavy abstraction, and a tide that still owns the lower Thames.",
    body: [
      "The global water cycle is closed. July in the London basin is a local deficit covered by reservoirs in the upper Thames, the London ring main, and abstraction licences. The ocean store did not notice. The town would, if the taps failed.",
      "The Thames is a lowland river with a large population on its floodplain. Groundwater in the chalk, soil moisture, and surface reservoirs are the stores that matter to a water company. Transfers are pumping and pipes as well as tributaries. The Severn, longer and wetter in its upland headwaters, is a different regime: more flashy in Wales, then a huge tidal range in the estuary — among the largest in the world.",
      "A drainage-basin overlay on the water-cycle lab is this case. The watershed is the divide. Rain on one side goes to the Thames, on the other to a neighbour. Abstraction is a tap on a local store. Over-draw it, and the reservoir falls even if the ocean is unchanged.",
      "Climate change moves the flows: heavier winter bursts, drier summers in the south-east. It does not invent a new cycle. Students who can name stores and transfers can then talk about drought without saying ‘the water ran out of the planet’.",
    ],
    exam: {
      prompt: "Why can a reservoir in the Thames basin fall in a dry summer even though the global water cycle is closed?",
      hint: "Local store, abstraction > recharge. Global mass conserved; location and timing are not.",
    },
    sources: [
      { label: "UKCEH / Environment Agency" },
      { label: "Thames Water / Defra abstraction" },
    ],
  },
  {
    slug: "iceland",
    title: "Iceland and Eyjafjallajökull",
    place: "Mid-Atlantic Ridge",
    region: "Shared",
    labs: ["plate-boundaries", "volcanoes", "seafloor-spreading"],
    lat: 63.63,
    lon: -19.62,
    zoom: 6,
    lede: "A divergent boundary above water, plus a hotspot. The 2010 ash plume closed northwest European airspace.",
    body: [
      "Iceland sits on the Mid-Atlantic Ridge, a divergent boundary, and on a mantle plume. New oceanic crust is made here. Thingvellir is a rift you can walk. The island is the ridge plus extra magma from the hotspot — which is why it stands above water when most of the ridge does not.",
      "Eyjafjallajökull in 2010 was a subglacial, explosive eruption of relatively evolved magma. Ice plus silica-rich melt made fine ash. High-level winds carried it over Europe. Aviation avoids ash because it damages turbine blades. UK specifications treat the eruption as a tectonic and atmospheric case. The ridge itself is the plate story; the ash is the hazard story.",
      "Compare the Himalaya: continent–continent convergence, crust stacked, not made. Compare Hawaii: a hotspot without a plate boundary. Compare Cascadia: subduction, not divergence. Three colours of boundary, plus a plume, cover the exam list.",
      "Seafloor spreading on either side of Iceland lays down magnetic stripes. The seafloor-spreading lab is that tape recorder. Iceland is where the tape is a country.",
    ],
    exam: {
      prompt: "Explain why Iceland has both basaltic fissure eruptions and occasional explosive, ash-rich events such as 2010.",
      hint: "Ridge + hotspot: usually basalt. Ice, evolved magma, and a central volcano can still go explosive.",
    },
    sources: [
      { label: "IMO / Icelandic Met Office" },
      { label: "BGS — Eyjafjallajökull 2010" },
      { label: "NASA Earth Observatory" },
    ],
  },
  {
    slug: "san-andreas",
    title: "San Andreas Fault",
    place: "California",
    region: "US",
    labs: ["plate-boundaries", "folds-faults", "earthquakes"],
    lat: 35.9,
    lon: -120.43,
    zoom: 6,
    lede: "A transform boundary you can walk. Pacific plate northwest, North American plate southeast.",
    body: [
      "The San Andreas is a right-lateral transform boundary between the Pacific and North American plates. The 1906 San Francisco and 1989 Loma Prieta earthquakes are this boundary in living memory. Offset fences, streams, and roads are the field evidence. Creep along some segments is slow and almost quiet; locked segments store elastic strain and then slip.",
      "Transform boundaries slide. They do not make a volcano chain. That is the exam contrast with Cascadia to the north, a subduction zone with a volcanic arc (the Cascades) and a different tsunami story. Students who colour both boundaries the same have missed the point of the plates lab.",
      "Strike-slip is the folds-faults lab’s third fault type. The San Andreas is the named example. Focus and epicentre, P and S waves, and a shake-map are the earthquakes lab. Parkfield has been an instrumented laboratory for decades because a repeating magnitude-6 sequence made it famous.",
      "UK students need this as the US pair to the Mid-Atlantic Ridge and the Himalaya. Three colours, three landforms, three hazards. The locator puts you on the Carrizo Plain, where the fault is a line in the grass.",
    ],
    exam: {
      prompt: "Why does the San Andreas system produce large earthquakes but not a volcanic arc, unlike Cascadia?",
      hint: "Transform vs subduction. Slide-past does not melt a slab; Cascadia does.",
    },
    sources: [
      { label: "USGS Earthquake Hazards Program", href: "https://www.usgs.gov/programs/earthquake-hazards" },
      { label: "USGS San Andreas fact sheets" },
    ],
  },
  {
    slug: "cascadia",
    title: "Cascadia subduction zone",
    place: "Pacific Northwest",
    region: "US",
    labs: ["plate-boundaries", "earthquakes", "tsunami", "volcanoes"],
    lat: 46.2,
    lon: -124.0,
    zoom: 5,
    lede: "A locked megathrust, a volcanic arc, and a tsunami story written in drowned forests.",
    body: [
      "The Juan de Fuca plate dives under North America. That is convergence: a trench offshore, earthquakes on the megathrust, and a chain of stratovolcanoes inland — Rainier, St Helens, Hood, Shasta. The 1700 Cascadia earthquake is dated from Japanese tsunami records and from drowned coastal forests in Oregon and Washington. The next one is a regional planning problem, not a myth.",
      "Subduction makes magma by adding water to the mantle wedge. Viscosity and gas make stratovolcanoes explosive. Shield volcanoes, like Hawaii, are a different chemistry and a different setting. The volcanoes lab’s viscosity slider is this contrast.",
      "A tsunami here would start with seafloor slip, not with a meteor. The tsunami lab is the physics: a water column lifted, a wave that is fast in deep water and tall in shallow water. Coastal schools in this region drill for that wave.",
      "Hold this case next to San Andreas. Same coast, different boundary, different volcano story, different tsunami story. That is the whole point of colouring plates.",
    ],
    exam: {
      prompt: "Describe how a Cascadia megathrust earthquake can generate both a volcanic arc (over time) and a tsunami (in minutes).",
      hint: "Watered mantle → arc over geologic time. Seafloor slip → tsunami in minutes.",
    },
    sources: [
      { label: "USGS Cascadia" },
      { label: "NOAA / NWS tsunami" },
    ],
  },
  {
    slug: "yellowstone",
    title: "Yellowstone",
    place: "Wyoming",
    region: "US",
    labs: ["earth-interior", "hotspots", "volcanoes"],
    lat: 44.6,
    lon: -110.5,
    zoom: 7,
    lede: "A mantle plume under a continent. Caldera, hydrothermal system, and a track of older calderas toward the southwest.",
    body: [
      "The plume is not a plate boundary. It is a hole the plate is sliding over — the continental cousin of Hawaii. Older calderas in the Snake River Plain get older toward the southwest, which is the track. The present hydrothermal system — geysers, hot springs — is magma heat under a continental crust that is still there.",
      "Seismic tomography, not a drill hole, is how we argue for the plume. The Kola Superdeep borehole, the deepest hole in rock, did not reach the mantle. We infer layering from P and S waves. Yellowstone’s magma reservoir is imaged the same way: geophysics, not a sample bottle from the core.",
      "A ‘supervolcano’ headline is not a teaching plan. The teacher script is: hotspot versus boundary, continental crust versus oceanic, rhyolite versus basalt, caldera versus stratovolcano. The interior lab’s liquid outer core is a different liquid from this melt. Students mix those liquids if you let them.",
    ],
    exam: {
      prompt: "How does the age pattern of calderas in the Snake River Plain support a hotspot under a moving plate?",
      hint: "Age increases southwest along the track. Plate moved; plume stayed relatively fixed.",
    },
    sources: [
      { label: "USGS Yellowstone Volcano Observatory" },
      { label: "USGS hotspot track" },
    ],
  },
  {
    slug: "hawaii",
    title: "Hawaii hotspot track",
    place: "Hawaiʻi to Emperor seamounts",
    region: "US",
    labs: ["hotspots", "volcanoes", "plate-boundaries"],
    lat: 19.4,
    lon: -155.3,
    zoom: 6,
    lede: "A plume under an oceanic plate. Shield volcanoes, a chain that gets older toward the northwest, and a bend into the Emperor seamounts.",
    body: [
      "Loihi and the Island of Hawaiʻi are young. Maui, Oʻahu, Kauaʻi are older. The Emperor seamounts are older still and trend north. The Pacific plate is moving over a relatively fixed mantle plume. That is the track. The bend records a change in plate motion about 47 million years ago — a sentence for A-level, not a KS3 requirement.",
      "Shield volcanoes here are basalt, low viscosity, long lava flows, gentle slopes. Mauna Loa and Kīlauea are the type. They are not stratovolcanoes. Viscosity, not ‘bigger explosion’, is the difference. The volcanoes lab’s slider is this.",
      "A hotspot can sit far from a plate boundary. That is the misconception to kill: not all volcanoes sit on the Ring of Fire. Hawaii is the exhibit. Yellowstone is the continental exhibit. Iceland is the ridge-plus-plume exhibit.",
    ],
    exam: {
      prompt: "Why are Hawaiian volcanoes shields rather than stratovolcanoes, and how does the island chain record plate motion?",
      hint: "Low-viscosity basalt. Age increases away from the active plume as the plate slides.",
    },
    sources: [
      { label: "USGS Hawaiian Volcano Observatory" },
      { label: "NOAA / ocean exploration seamounts" },
    ],
  },
  {
    slug: "grand-canyon",
    title: "Grand Canyon",
    place: "Arizona",
    region: "US",
    labs: ["rock-cycle", "weathering", "landform-types"],
    lat: 36.05,
    lon: -112.14,
    zoom: 9,
    lede: "A plateau cut by a river, a stack of sedimentary rocks, and a timeline in metres of cliff.",
    body: [
      "The Grand Canyon is not a rift and not a glacial trough. It is incision: the Colorado River cutting down through the Colorado Plateau as the land was high enough and the river persistent enough. Horizontal beds of sandstone, shale, and limestone make cliffs and slopes according to resistance. The Vishnu Schist at the bottom is metamorphic basement.",
      "The rock-cycle lab’s sedimentary stack is this wall. Weathering opens joints; mass movement delivers; the river exports. The landform is a canyon in a plateau — one of the five types in the landform-types lab, cut rather than built.",
      "Do not invent a date for ‘the canyon formed in X years’ unless you cite USGS. The rocks are Proterozoic to Palaeozoic; the incision is much younger. Students should separate the age of the rock from the age of the hole.",
    ],
    exam: {
      prompt: "Distinguish the age of the rocks in the Grand Canyon walls from the age of the canyon as a landform.",
      hint: "Rocks: hundreds of millions of years. Incision: much younger uplift and downcutting.",
    },
    sources: [
      { label: "USGS / NPS Grand Canyon" },
    ],
  },
  {
    slug: "mississippi",
    title: "Mississippi and delta",
    place: "Lower Mississippi",
    region: "US",
    labs: ["rivers", "river-deposition", "hydrograph"],
    lat: 29.15,
    lon: -89.25,
    zoom: 6,
    lede: "A continental drain with levées, cut-offs, and a bird-foot delta fighting subsidence and a rising Gulf.",
    body: [
      "The long profile ends in stiller water and a huge load. Tides in the Gulf here are modest, so a delta can persist. Distributaries, levées, and a floodplain the size of a country are the lower-course kit. The 1927 flood and the Old River Control Structure are human attempts to keep the river from jumping to the Atchafalaya — a capture story at engineering scale.",
      "Meander cut-offs, oxbows, and artificial straightening sit on the same helicoidal-flow logic as the rivers lab. Raise discharge and competence rises; the floodplain takes water when the levée is overtopped or fails. Hurricane Katrina’s flooding of New Orleans was a storm-surge and levée-failure story on this coast, not a simple fluvial hydrograph — keep the mechanisms honest.",
      "Compare a Lake District beck: same processes, no delta, because the load and the coast disagree. Compare the Nile or the Ganges only if you keep the numbers sourced. This case is USGS and USACE territory.",
    ],
    exam: {
      prompt: "Explain why the Mississippi can maintain a bird-foot delta while many UK rivers end in estuaries.",
      hint: "Huge load, modest tides, shallow Gulf. UK: smaller load, larger tidal range, often drowned valleys.",
    },
    sources: [
      { label: "USGS Mississippi River" },
      { label: "USACE Mississippi River & Tributaries" },
    ],
  },
  {
    slug: "yosemite",
    title: "Yosemite Valley rim",
    place: "Sierra Nevada",
    region: "US",
    labs: ["contours", "glaciers", "moon-phases"],
    lat: 37.74,
    lon: -119.57,
    zoom: 11,
    lede: "A U-shaped valley so deep the rim is a cliff on the map: coincident contours and a spot height at Half Dome.",
    body: [
      "USGS quads make the same spur/valley argument as an OS sheet. The interval is just in feet on older plates. Yosemite Valley is a glacial trough in granite. Hanging valleys dump waterfalls (Yosemite Falls, Bridalveil). El Capitan and Half Dome are the walls. Moraines sit down-valley. Cirques and arêtes sit in the high Sierra above.",
      "The glaciers lab’s U-trough, hanging valley, and truncated spur are this place. The contours lab’s coincident lines are the cliffs. A full Moon over Half Dome is the moon-phases geometry — the same phase as Snowdonia that night, a different rise time because Earth is still rotating.",
      "Ice here is mostly gone as glaciers; the landforms remain. Students should not say ‘Yosemite is a canyon like the Grand Canyon.’ One is ice, one is a river in a plateau. Cross-profile tells them apart.",
    ],
    exam: {
      prompt: "How would a contour map distinguish Yosemite Valley from a V-shaped river gorge of similar depth?",
      hint: "U: wide flat floor, steep walls, hanging valleys. V: evenly closing contours to a stream.",
    },
    sources: [
      { label: "USGS / NPS Yosemite" },
    ],
  },
  {
    slug: "katrina-sandy",
    title: "Katrina and Sandy",
    place: "New Orleans · New York Bight",
    region: "US",
    labs: ["tropical-cyclone", "coasts"],
    lat: 29.95,
    lon: -90.07,
    zoom: 5,
    lede: "Two North Atlantic cyclones, two different coasts, one shared physics: low pressure, wind, surge, and a shoreline that was already under stress.",
    body: [
      "Hurricane Katrina (2005) hit the Gulf Coast as a large tropical cyclone. The catastrophe in New Orleans was a surge and a levée-and-floodwall failure on a city below some water surfaces, on a sinking delta. The eye and eyewall of a tropical cyclone are the lab; the social and engineering failure is the case. Keep them both in the script, and do not invent fatality numbers — cite NOAA.",
      "Hurricane Sandy (2012) was a late-season hybrid that struck the New York–New Jersey Bight. Storm surge in a funnel-shaped coast, high tide, and a dense urban shoreline. It was not ‘just rain’. Surge is a water-level story; rainfall is a hydrograph story. Students mix them.",
      "The tropical-cyclone lab shows the eye, eyewall, and rainbands. It does not claim that every UK windy day is a hurricane. Midlatitude cyclones are a different machine (the fronts lab). Sandy’s hybrid nature is a teacher’s caution, not a KS3 requirement.",
      "UK pair: North Sea storm surges (1953, and the Thames Barrier’s reason for existing). Same surge idea, extra-tropical storms. Honest language: do not call a UK winter storm a hurricane unless the Met Office does.",
    ],
    exam: {
      prompt: "Distinguish storm surge from river flooding in the Katrina disaster, and say which lab models the cyclone itself.",
      hint: "Surge: sea level driven by wind and pressure. River/levée: inland water. Lab: tropical cyclone eye/eyewall.",
    },
    sources: [
      { label: "NOAA / NHC Katrina and Sandy reports" },
      { label: "USGS surge and high-water marks" },
    ],
  },
  {
    slug: "dust-bowl",
    title: "Dust Bowl",
    place: "Southern Great Plains",
    region: "US",
    labs: ["soil-erosion", "weathering", "aeolian"],
    lat: 36.68,
    lon: -101.48,
    zoom: 5,
    lede: "A drought, a plough, and a wind that took the A horizon off the plains.",
    body: [
      "The 1930s Dust Bowl is the US soil-erosion case. Deep ploughing of prairie, drought, and strong winds. Rain splash and rill were not the headline; wind was. Without vegetation, the A horizon had no anchor. Black blizzards moved soil across state lines. The soil-erosion lab’s vegetation toggle is this sentence.",
      "Aeolian landforms — yardangs, barchans — are the world-example kit, not a Great Plains default. On the plains the process was deflation and transport of farmed silt and sand, not a desert textbook dune field. Keep the landform names honest.",
      "UK pair: peaty upland erosion and blown sand on some coasts, at a smaller scale. The physics of an unsheltered particle is the same. The history is American.",
      "Do not invent tonnages. USDA and NOAA historical summaries are the sources. The teaching point is land use plus climate plus wind, not a morality play.",
    ],
    exam: {
      prompt: "Explain how vegetation removal made Great Plains soils vulnerable to wind erosion in the 1930s.",
      hint: "Roots and cover trap particles and raise roughness. Bare dry A horizon → deflation.",
    },
    sources: [
      { label: "NOAA / NCEI drought and Dust Bowl" },
      { label: "USDA NRCS soil erosion history" },
    ],
  },
  {
    slug: "colorado",
    title: "Colorado River reservoirs",
    place: "Powell and Mead",
    region: "US",
    labs: ["water-cycle", "river-hydrology"],
    lat: 36.06,
    lon: -114.74,
    zoom: 6,
    lede: "A bathtub ring is abstraction plus a drier hydroclimate drawn on a canyon wall.",
    body: [
      "The ocean store did not shrink by the volume of Lake Mead. The local store did. Powell and Mead are managed reservoirs on a river whose compact was signed in a wetter early twentieth century. A bathtub ring is the last high shoreline as a stain.",
      "The water-cycle lab’s abstraction slider is this. A closed global cycle still allows a basin to be in deficit. Snowpack in the Rockies is the headwater store. A drier hydroclimate plus upstream use plus evaporation from open reservoirs is the budget.",
      "Students should not say ‘the Colorado is running out of water on Earth.’ They should say ‘the allocated flow exceeds the river that is actually there in a dry decade.’",
    ],
    exam: {
      prompt: "Using stores and transfers, explain a falling Lake Mead level without claiming the global water cycle is leaking.",
      hint: "Local store. Abstraction + evaporation + reduced inflow. Global mass conserved.",
    },
    sources: [
      { label: "USBR / USGS Colorado River" },
    ],
  },
  {
    slug: "greenwich",
    title: "Greenwich meridian",
    place: "London",
    region: "UK",
    labs: ["rotation", "graticule"],
    lat: 51.477,
    lon: -0.0015,
    zoom: 12,
    lede: "Longitude zero is a political choice laid on a rotating sphere. The 15°/hour arithmetic is not.",
    body: [
      "The Prime Meridian at the Royal Observatory is the civil fiction. Solar noon is when the Sun crosses your local meridian. Time zones are a human overlay on 360° / 24 h = 15° per hour. The terminator ignores the jogs in the zone boundaries.",
      "Stand on the meridian line and you have not stopped the planet. You have labelled a longitude. The rotation lab’s 15° callout is the physics. Greenwich is the plaque.",
      "The graticule lab puts this line on a 3D Earth with the rest of the net. Students who think the equator is ‘a line painted on the sea’ need that lab more than this plaque, but the plaque helps.",
    ],
    exam: {
      prompt: "Why is 15° of longitude equal to one hour, and why is the Greenwich meridian not required for that arithmetic?",
      hint: "360/24 = 15. Zero longitude is a convention; the spin is not.",
    },
    sources: [
      { label: "Royal Observatory Greenwich" },
    ],
  },
  {
    slug: "time-zones-us",
    title: "US lower-48 time zones",
    place: "Eastern to Pacific",
    region: "US",
    labs: ["rotation", "graticule"],
    lat: 39.8,
    lon: -98.6,
    zoom: 3,
    lede: "Four civil zones across about 60° of longitude, with jogs for state lines. The terminator ignores the jogs.",
    body: [
      "Noon in Boston is still morning in Seattle because the planet has not finished that 15° × 3 turn. Eastern, Central, Mountain, Pacific are civil bands. They jog around cities and state lines. The Sun does not.",
      "The rotation lab’s time-zone overlay is this. Toggle it on, then off. The terminator is the machinery. The colours are the timetable.",
    ],
    exam: {
      prompt: "If solar noon has just reached New York, about how long until solar noon in a place 45° of longitude further west?",
      hint: "45/15 = 3 hours.",
    },
    sources: [
      { label: "NIST / USNO" },
    ],
  },
  {
    slug: "kola",
    title: "Kola Superdeep borehole",
    place: "Kola Peninsula",
    region: "Shared",
    labs: ["earth-interior"],
    lat: 69.4,
    lon: 30.6,
    zoom: 5,
    lede: "The deepest hole in rock, about 12 km. Continental crust goes on for another 20 km. The mantle was never reached.",
    body: [
      "We know the outer core is liquid because of S-wave shadows, not because someone brought back a sample. Kola is the humility exhibit: the crust is a skin, drilling is hard, temperature and rock strength win.",
      "The interior lab’s explode and slice, then P and S waves, are how we actually know. Kola is how we do not.",
    ],
    exam: {
      prompt: "Why is the Kola borehole not evidence for the composition of the outer core?",
      hint: "12 km vs ~2900 km to the core-mantle boundary. Seismology, not drilling, is the tool.",
    },
    sources: [
      { label: "BGS / USGS interior summaries" },
    ],
  },
  {
    slug: "snowdonia-moon",
    title: "Moonrise, Snowdonia",
    place: "Eryri",
    region: "UK",
    labs: ["moon-phases"],
    lat: 53.07,
    lon: -4.08,
    zoom: 9,
    lede: "A full Moon over Tryfan is the Moon opposite the Sun. The same night, California sees the same phase.",
    body: [
      "Phase is global. Rise time is local, because Earth is still rotating. Full Moon plus a node crossing would be a lunar eclipse. Most months, the Moon misses Earth’s shadow by 5° of orbital tilt.",
      "The moon-phases lab’s UK/US night-sky inset is this sentence. Photographers wait on geometry, not on a different Moon.",
    ],
    exam: {
      prompt: "Why can two observers, one in Snowdonia and one in Yosemite, see the same lunar phase on the same date but at different clock times?",
      hint: "Phase: Sun–Moon–Earth angle. Clock time: rotation and longitude.",
    },
    sources: [{ label: "NASA Moon phases" }],
  },
  {
    slug: "yosemite-moon",
    title: "Full Moon, Yosemite",
    place: "Yosemite Valley",
    region: "US",
    labs: ["moon-phases"],
    lat: 37.74,
    lon: -119.57,
    zoom: 11,
    lede: "Photographers wait for a full Moon to clear Half Dome. They are waiting on geometry, not weather.",
    body: [
      "Full Moon plus a node crossing would be a lunar eclipse. Most months, the Moon misses Earth’s shadow by 5° of orbital tilt. The same phase is up in Snowdonia that night. Weather is local. Phase is not.",
    ],
    exam: {
      prompt: "Why is a full Moon necessary but not sufficient for a lunar eclipse?",
      hint: "Full = opposite the Sun. Eclipse also needs the Moon near a node of its 5° tilt.",
    },
    sources: [{ label: "NASA / NPS" }],
  },
  {
    slug: "outer-banks",
    title: "Outer Banks",
    place: "North Carolina",
    region: "US",
    labs: ["coasts"],
    lat: 35.25,
    lon: -75.53,
    zoom: 7,
    lede: "A barrier-island chain, longshore drift, storm inlets, and a different sediment budget from Holderness till cliffs.",
    body: [
      "The Outer Banks are sand in motion. Barrier islands sit offshore, with a lagoon or sound behind. Longshore drift moves sand along the chain. Storms punch inlets; some inlets stay, some heal. Cape Hatteras is a famous turn in the conveyor.",
      "Unlike Holderness, there is no till cliff retreating at two metres a year. The landform is a barrier, not a cliff. The budget idea is the same: supply, transport, deposition, interruption. Groynes and beach nourishment are the management cousins of Mappleton’s rocks.",
      "Constructive waves can build the berm. Destructive storm waves can overwash the island and roll it toward the mainland. Students should be able to say that a barrier is not a permanent wall.",
    ],
    exam: {
      prompt: "Compare the Holderness cliff and the Outer Banks as sediment systems. What is shared, and what is not?",
      hint: "Shared: longshore budget. Different: till cliff vs barrier sand, rates, landforms.",
    },
    sources: [
      { label: "USGS barrier islands" },
      { label: "NOAA / NPS Cape Hatteras" },
    ],
  },
  {
    slug: "mammoth-cave",
    title: "Mammoth Cave",
    place: "Kentucky",
    region: "US",
    labs: ["karst"],
    lat: 37.19,
    lon: -86.1,
    zoom: 9,
    lede: "A long carbonate cave system: the US pair to the Yorkshire Dales pavement and swallow holes.",
    body: [
      "Mammoth Cave sits in Mississippian limestones. Surface streams sink. Passages follow joints and bedding. Sinkholes pock the Chester Upland. The chemistry is carbonation, the same as Malham, at a different scale.",
      "The karst lab’s cave passage is this. Do not claim a world-length ranking unless you cite NPS. Claim the process.",
    ],
    exam: {
      prompt: "Why do sinkholes and caves cluster on carbonate rocks rather than on granite?",
      hint: "Carbonation of CaCO₃ along joints. Granite does not dissolve that way.",
    },
    sources: [{ label: "NPS / USGS Mammoth Cave" }],
  },
  {
    slug: "phoenix-heat",
    title: "Phoenix urban heat",
    place: "Arizona",
    region: "US",
    labs: ["thermal-circulation", "energy-budget"],
    lat: 33.45,
    lon: -112.07,
    zoom: 8,
    lede: "A desert city that stores heat in asphalt and roofs. The sea breeze lab’s urban-heat toggle, at city scale.",
    body: [
      "An urban heat island is a surface-energy-budget story. Dark, dry materials absorb shortwave, emit longwave, and lack the evaporative cooling of vegetation. Nights stay warmer than the surrounding desert. Phoenix is a clear US example; a UK school playground is a small one.",
      "The thermal-circulation lab’s two columns — heat one, watch the loop — is the physics. Land–sea breeze is the coastal cousin. Urban heat is the dry, paved cousin.",
    ],
    exam: {
      prompt: "Explain why a city can stay warmer than surrounding desert at night, using albedo and latent heat.",
      hint: "Low albedo, little evapotranspiration, stored heat released as longwave at night.",
    },
    sources: [{ label: "NOAA / NWS urban heat" }],
  },
  {
    slug: "uk-sea-breeze",
    title: "UK sea breeze",
    place: "South coast",
    region: "UK",
    labs: ["thermal-circulation", "wind"],
    lat: 50.8,
    lon: -1.1,
    zoom: 7,
    lede: "A coastal school feels the sea breeze at last period for a reason: land heats, a loop starts, the cool air comes in from the water.",
    body: [
      "On a sunny day the land surface warms faster than the sea. Air over land rises. Air over the sea replaces it. The return flow aloft closes the loop. By last period the onshore flow can be a forecast the Met Office will name as a sea breeze.",
      "The thermal-circulation lab is this. Toggle land–sea. Then toggle urban heat and see a different loop. Coriolis barely matters at this scale; it matters on the three-cell lab.",
    ],
    exam: {
      prompt: "Draw and label a sea-breeze circulation for a calm, sunny afternoon on the south coast.",
      hint: "Land warm, sea cool. Onshore at surface, rise over land, return aloft, sink over sea.",
    },
    sources: [{ label: "Met Office sea breezes" }],
  },
  {
    slug: "cairngorms-albedo",
    title: "Cairngorms snow albedo",
    place: "Scottish Highlands",
    region: "UK",
    labs: ["energy-budget"],
    lat: 57.08,
    lon: -3.67,
    zoom: 8,
    lede: "Fresh snow bounces a large share of incoming shortwave. Bare peat does not. The ground’s colour is the first control.",
    body: [
      "Albedo is the fraction of incoming shortwave a surface reflects. Fresh snow can reflect most of the beam. Dark peat and heather absorb. The energy-budget lab’s bounce arrows are this hillside in March versus August.",
      "Arizona desert is the US pair: high Sun, often high albedo on pale sand, but dry ground that still runs hot because there is little water to evaporate.",
    ],
    exam: {
      prompt: "Why does a snow-covered Cairngorm plateau heat the air less than a snow-free peat surface under the same incoming solar radiation?",
      hint: "Higher albedo → less absorbed shortwave → less longwave and sensible heat from the surface.",
    },
    sources: [{ label: "Met Office / CEH snow and peat" }],
  },
  {
    slug: "denver-air",
    title: "Denver mile-high air",
    place: "Colorado",
    region: "US",
    labs: ["atmosphere-layers"],
    lat: 39.74,
    lon: -104.99,
    zoom: 7,
    lede: "A kilometre and a half up, the troposphere is thinner above you and the air is already the ‘high’ part of the weather layer.",
    body: [
      "Weather lives in the troposphere. Denver sits at about 1,600 m. Air pressure is lower; the same lapse-rate story starts from a higher platform. A UK radiosonde from a Met Office station is the pair: a balloon through troposphere toward tropopause, temperature falling, then the inversion at the tropopause.",
      "The atmosphere-layers lab’s exploded shells are this. Composition readout (nitrogen, oxygen, argon, CO₂) is the same at Denver as at sea level in proportion; density is not.",
    ],
    exam: {
      prompt: "Why is Denver’s weather still ‘troposphere’ weather even though the city is a mile above sea level?",
      hint: "The tropopause is still many kilometres above the city. Weather’s layer is thick compared with a mile.",
    },
    sources: [
      { label: "NOAA / NWS Denver" },
      { label: "Met Office radiosondes" },
    ],
  },
];

export const CASE_BY_SLUG: Record<string, CaseStudy> = Object.fromEntries(
  CASES.map((c) => [c.slug, c]),
);
