/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as CaseSlugRouteImport } from './routes/case.$slug'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as PathsIndexRouteImport } from './routes/paths.index'
import { Route as PathsSlugRouteImport } from './routes/paths.$slug'
import { Route as RealmsRealmRouteImport } from './routes/realms.$realm'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsAtlasRouteImport } from './routes/tools.atlas'
import { Route as ToolsEarthMotionRouteImport } from './routes/tools.earth-motion'
import { Route as ToolsLiveWeatherRouteImport } from './routes/tools.live-weather'
import { Route as ToolsMapRouteImport } from './routes/tools.map'
import { Route as ToolsWeatherRouteImport } from './routes/tools.weather'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsSlugRoute = PathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsRealmRoute = RealmsRealmRouteImport.update({
  id: '/realms/$realm',
  path: '/realms/$realm',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAtlasRoute = ToolsAtlasRouteImport.update({
  id: '/tools/atlas',
  path: '/tools/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEarthMotionRoute = ToolsEarthMotionRouteImport.update({
  id: '/tools/earth-motion',
  path: '/tools/earth-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLiveWeatherRoute = ToolsLiveWeatherRouteImport.update({
  id: '/tools/live-weather',
  path: '/tools/live-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMapRoute = ToolsMapRouteImport.update({
  id: '/tools/map',
  path: '/tools/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWeatherRoute = ToolsWeatherRouteImport.update({
  id: '/tools/weather',
  path: '/tools/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/skills': typeof SkillsRoute
  '/teachers': typeof TeachersRoute
  '/case/$slug': typeof CaseSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/realms/$realm': typeof RealmsRealmRoute
  '/tools/atlas': typeof ToolsAtlasRoute
  '/tools/earth-motion': typeof ToolsEarthMotionRoute
  '/tools/live-weather': typeof ToolsLiveWeatherRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/weather': typeof ToolsWeatherRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/paths/': typeof PathsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/skills': typeof SkillsRoute
  '/teachers': typeof TeachersRoute
  '/case/$slug': typeof CaseSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/realms/$realm': typeof RealmsRealmRoute
  '/tools/atlas': typeof ToolsAtlasRoute
  '/tools/earth-motion': typeof ToolsEarthMotionRoute
  '/tools/live-weather': typeof ToolsLiveWeatherRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/weather': typeof ToolsWeatherRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/paths': typeof PathsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/skills': typeof SkillsRoute
  '/teachers': typeof TeachersRoute
  '/case/$slug': typeof CaseSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/paths/$slug': typeof PathsSlugRoute
  '/realms/$realm': typeof RealmsRealmRoute
  '/tools/atlas': typeof ToolsAtlasRoute
  '/tools/earth-motion': typeof ToolsEarthMotionRoute
  '/tools/live-weather': typeof ToolsLiveWeatherRoute
  '/tools/map': typeof ToolsMapRoute
  '/tools/weather': typeof ToolsWeatherRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/paths/': typeof PathsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/atlas'
    | '/explore'
    | '/glossary'
    | '/privacy'
    | '/search'
    | '/skills'
    | '/teachers'
    | '/case/$slug'
    | '/lab/$slug'
    | '/paths/$slug'
    | '/realms/$realm'
    | '/tools/atlas'
    | '/tools/earth-motion'
    | '/tools/live-weather'
    | '/tools/map'
    | '/tools/weather'
    | '/topic/$slug'
    | '/paths/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/atlas'
    | '/explore'
    | '/glossary'
    | '/privacy'
    | '/search'
    | '/skills'
    | '/teachers'
    | '/case/$slug'
    | '/lab/$slug'
    | '/paths/$slug'
    | '/realms/$realm'
    | '/tools/atlas'
    | '/tools/earth-motion'
    | '/tools/live-weather'
    | '/tools/map'
    | '/tools/weather'
    | '/topic/$slug'
    | '/paths'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/atlas'
    | '/explore'
    | '/glossary'
    | '/privacy'
    | '/search'
    | '/skills'
    | '/teachers'
    | '/case/$slug'
    | '/lab/$slug'
    | '/paths/$slug'
    | '/realms/$realm'
    | '/tools/atlas'
    | '/tools/earth-motion'
    | '/tools/live-weather'
    | '/tools/map'
    | '/tools/weather'
    | '/topic/$slug'
    | '/paths/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AtlasRoute: typeof AtlasRoute
  ExploreRoute: typeof ExploreRoute
  GlossaryRoute: typeof GlossaryRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SkillsRoute: typeof SkillsRoute
  TeachersRoute: typeof TeachersRoute
  CaseSlugRoute: typeof CaseSlugRoute
  LabSlugRoute: typeof LabSlugRoute
  PathsSlugRoute: typeof PathsSlugRoute
  RealmsRealmRoute: typeof RealmsRealmRoute
  ToolsAtlasRoute: typeof ToolsAtlasRoute
  ToolsEarthMotionRoute: typeof ToolsEarthMotionRoute
  ToolsLiveWeatherRoute: typeof ToolsLiveWeatherRoute
  ToolsMapRoute: typeof ToolsMapRoute
  ToolsWeatherRoute: typeof ToolsWeatherRoute
  TopicSlugRoute: typeof TopicSlugRoute
  PathsIndexRoute: typeof PathsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$slug': {
      id: '/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/paths/$slug'
      preLoaderRoute: typeof PathsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms/$realm': {
      id: '/realms/$realm'
      path: '/realms/$realm'
      fullPath: '/realms/$realm'
      preLoaderRoute: typeof RealmsRealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/atlas': {
      id: '/tools/atlas'
      path: '/tools/atlas'
      fullPath: '/tools/atlas'
      preLoaderRoute: typeof ToolsAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/earth-motion': {
      id: '/tools/earth-motion'
      path: '/tools/earth-motion'
      fullPath: '/tools/earth-motion'
      preLoaderRoute: typeof ToolsEarthMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/live-weather': {
      id: '/tools/live-weather'
      path: '/tools/live-weather'
      fullPath: '/tools/live-weather'
      preLoaderRoute: typeof ToolsLiveWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/map': {
      id: '/tools/map'
      path: '/tools/map'
      fullPath: '/tools/map'
      preLoaderRoute: typeof ToolsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/weather': {
      id: '/tools/weather'
      path: '/tools/weather'
      fullPath: '/tools/weather'
      preLoaderRoute: typeof ToolsWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AtlasRoute: AtlasRoute,
  ExploreRoute: ExploreRoute,
  GlossaryRoute: GlossaryRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SkillsRoute: SkillsRoute,
  TeachersRoute: TeachersRoute,
  CaseSlugRoute: CaseSlugRoute,
  LabSlugRoute: LabSlugRoute,
  PathsSlugRoute: PathsSlugRoute,
  RealmsRealmRoute: RealmsRealmRoute,
  ToolsAtlasRoute: ToolsAtlasRoute,
  ToolsEarthMotionRoute: ToolsEarthMotionRoute,
  ToolsLiveWeatherRoute: ToolsLiveWeatherRoute,
  ToolsMapRoute: ToolsMapRoute,
  ToolsWeatherRoute: ToolsWeatherRoute,
  TopicSlugRoute: TopicSlugRoute,
  PathsIndexRoute: PathsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
