import type { LabMeta } from "./types";
import { lab, q, steps } from "./make";

export const HAZARD_LABS: LabMeta[] = [
  lab({
    slug: "earthquakes",
    title: "Earthquakes",
    hook: "Focus is in the rock. Epicentre is the map dot. P, then S, then the surface wave that does the damage in town.",
    objective: "Place focus and epicentre and watch P, S, and surface waves.",
    realm: "hazards",
    ages: ["KS3", "GCSE", "NGSS MS", "HS Earth Sci"],
    curriculum: ["GCSE AQA 3.1.1.4", "NGSS MS-ESS3-2"],
    steps: steps("Focus at depth. Epicentre above.", "Play P (fast), S (shear), surface.", "S dies in liquid — interior lab."),
    questions: [
      q("The focus (hypocentre) is…", ["The map dot", "The point of slip in the rock", "The Moon", "Always at 0 km"], 1, "Epicentre is the surface point above."),
      q("P-waves…", ["Are slowest", "Are fastest and travel through solid and liquid", "Are only sound in air", "Need water"], 1, "Primary."),
      q("Surface waves…", ["Arrive first", "Often do the damage at the surface, arriving later", "Are P-waves", "Only exist in space"], 1, "Love and Rayleigh."),
      q("Magnitude versus intensity…", ["They are the same number", "Magnitude is the source size; intensity is what a place feels", "Intensity is only at the focus", "Magnitude is rainfall"], 1, "Keep it qualitative here. One is the machine. One is the town."),
    ],
    why: [
      "San Andreas and Cascadia teach the same waves on different machines. The San Andreas is a transform: Pacific plate northwest, North American southeast, strike-slip you can walk on the Carrizo Plain. 1906 San Francisco and 1989 Loma Prieta are this boundary in living memory. Cascadia is a megathrust: Juan de Fuca diving under North America, a locked subduction zone with a 1700 earthquake dated from Japanese tsunami records and drowned forests. Same P, S and surface waves. Different fault, different depth story, different tsunami story. GCSE AQA 3.1.1.4 and NGSS MS-ESS3-2 both need focus versus epicentre before anyone colours a shake map. UK students will not feel these plates under the desk; they will meet them on the paper. Hawaii and Iceland are volcano labs. Katrina and Sandy are water and wind. This lab is slip in the rock and the three-wave sequence that follows. Map dot is not the underground spark.",
      "Slip starts at the focus, also called the hypocentre: a point (really a patch) in the rock. The epicentre is the surface point vertically above it, the map dot, not a cave. Elastic strain stored on a locked fault becomes kinetic energy and heat when the fault slips. Body waves leave first. P-waves are compressional, fastest, and travel through solid and liquid — primary, the first arrival. S-waves are shear, slower, and die in liquid; that fact is the outer-core argument in the interior lab, reused here as a reminder. Surface waves (Love and Rayleigh) travel along the free surface, arrive later, and often do the damage in town because they shake the ground where buildings sit. Play in this lab: P shell grows, then S, then a surface ring and a ripple on the top face. Magnitude is a source-size scale. Intensity is what a place feels — distance, geology, building. Keep that pair qualitative. San Andreas creep versus locked segments, Cascadia’s long recurrence, shallow versus deep: all of that sits on top of focus, epicentre, P, S, surface. Get those five words right and the case pages can work.",
      "Play from t = 0. The hanging wall and footwall sit either side of a visible fault plane. A spark in the rock is the focus; a cool marker on the top face is the epicentre, joined by a vertical line. P expands as a fast shell. S follows, slower, shearing. Then a surface ring and a ripple on the ground. Orbit so you can see that the epicentre is on the map, not underground. Pause after P and ask who arrived first. Step the camera down to the focus, then up to the epicentre. Click the part: Focus, Epicentre, Fault, P, S, Surface. San Andreas and Cascadia are the locators after the sequence, not before it.",
      "Without the canvas the sequence is still the lesson. Focus (hypocentre) is the point of slip in the rock. Epicentre is the surface point above it, the map dot, not underground. P-waves are fastest and travel through solid and liquid. S-waves shear and die in liquid. Surface waves arrive later and often do the damage in town. Magnitude is the source; intensity is what a place feels. San Andreas is transform; Cascadia is subduction. Same waves, different machine. Do not put the epicentre in a cave.",
    ],
    glossary: [
      { term: "Focus", exam: "Hypocentre", def: "Where the slip starts in the rock." },
      { term: "Epicentre", def: "Surface point vertically above the focus. The map dot." },
      { term: "P-wave", exam: "Primary wave", def: "Fastest body wave. Compressional. Travels through solid and liquid." },
      { term: "S-wave", exam: "Secondary wave", def: "Shear body wave. Slower than P. Dies in liquid." },
      { term: "Surface wave", def: "Love and Rayleigh waves along the free surface. Often the damage in town." },
      { term: "Magnitude", def: "A scale for source size. Not the same as intensity." },
      { term: "Intensity", def: "What a place feels, given distance, ground and buildings." },
    ],
    misconception: { claim: "The epicentre is underground.", truth: "Epicentre is on the map. Focus is in the rock." },
    misconceptions: [
      { claim: "The epicentre is underground.", truth: "Epicentre is on the map. Focus is in the rock." },
      { claim: "The biggest wave arrives first.", truth: "P arrives first. Surface waves come later and often do the damage." },
      { claim: "Magnitude and intensity are the same number.", truth: "One is the source. One is what a town feels." },
    ],
    cases: [{ slug: "san-andreas", label: "San Andreas" }, { slug: "cascadia", label: "Cascadia" }],
    teacher: {
      script:
        "Place the focus in the rock. That is the hypocentre, where slip starts.\nThe epicentre is the map dot above it, on the surface, not underground.\nThat is the misconception.\nThe hanging wall and footwall offset along the fault as you play.\nFire the waves. P first: fastest, through solid and liquid.\nThen S: shear. S dies in liquid — the interior lab.\nThen the surface wave. It arrives later and often does the damage in town.\nAsk who arrives first. P. Ask what shakes the town. Surface.\nKeep magnitude versus intensity qualitative here. One is the source. One is what a place feels.\nSan Andreas and Cascadia: same waves, different machine. Transform versus megathrust.\nFinish in Check.",
      pitfalls: [
        "Magnitude vs intensity mix-up — keep it qualitative here.",
        "Epicentre drawn as a cave.",
        "S-waves through the outer core in this lab’s story.",
        "Calling every California quake a subduction event.",
      ],
    },
    sources: [{ label: "USGS earthquakes" }, { label: "BGS seismology" }],
    controls: {
      extra: [{ key: "depth", label: "Focus depth", min: 0, max: 1, step: 0.01, default: 0.45 }],
    },
  }),
  lab({
    slug: "volcanoes",
    title: "Volcanoes",
    hook: "Viscosity is the plot. Shield, strato, rift — three shapes from one slider.",
    objective: "Contrast shield, stratovolcano, and rift; use a viscosity slider.",
    realm: "hazards",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.1.3", "NGSS MS-ESS2-2"],
    steps: steps("Low viscosity: shield. High: strato. Rift: fissure.", "Slide viscosity.", "Hawaii vs St Helens vs Iceland fissure."),
    questions: [
      q("Shield volcanoes form from…", ["High-viscosity rhyolite only", "Low-viscosity basalt, long flows, gentle slopes", "Only ice", "Wind"], 1, "Mauna Loa."),
      q("Stratovolcanoes are steep because…", ["They are older hills", "Stickier, gassier magma builds layers of lava and ash", "Tides", "They are dunes"], 1, "Cascades."),
      q("A rift eruption…", ["Needs a hotspot always", "Can be a fissure of basalt at a divergent boundary", "Is a hurricane", "Is a meander"], 1, "Iceland."),
      q("Sticky magma explodes more readily because…", ["It is colder than space", "Gas cannot escape easily, so pressure builds", "It is always underwater", "Tides trap it"], 1, "Runny basalt degasses and pours. Viscosity is the plot."),
    ],
    why: [
      "Viscosity is the plot, not ‘bigger boom’ as a personality trait. Hawaii’s Mauna Loa and Kīlauea are shields: low-viscosity basalt, long flows, gentle slopes on a hotspot under an oceanic plate. Cascadia’s arc — St Helens, Rainier, Hood — is the sticky end-member: water from the slab, andesite and dacite, layers of lava and ash, steep cones. Iceland sits on the Mid-Atlantic Ridge plus a plume: usually basalt fissures you can walk at places like Thingvellir, and occasional explosive events when ice and evolved magma meet, as in Eyjafjallajökull 2010. GCSE AQA 3.1.1.3 and NGSS want that contrast without a league table of famous eruptions. San Andreas does not make this chain; it slides. Katrina and Sandy are a different hazard. One slider, three shapes: shield, strato, rift. UK students meet these as named case studies, not as a local cone. The chemistry and the gas decide the slope. The poster that says all volcanoes explode has already failed the lab.",
      "Magma is silicate liquid plus crystals plus dissolved gas. Viscosity is resistance to flow. Low silica, hot, crystal-poor basalt is runny: gas escapes, lava travels far, the edifice spreads into a shield. High silica, cooler, stickier melts hold gas. Pressure builds, fragmentation makes ash, and the cone steepens as lava and pyroclasts stack: a stratovolcano, a composite cone. A divergent boundary can skip the cone and erupt along a fissure — Iceland’s ridge habit, not a cartoon cube. Hotspot versus arc versus ridge is the setting; viscosity is still the plot inside the conduit. Water from a subducting slab lowers melting point in the mantle wedge and tends to give the Cascades their sticky, explosive character. A plume under ocean crust, Hawaii, tends to give basalt. Ice on a central volcano can add ash even when the ridge itself is basaltic. Supervolcano headlines are not a course. Yellowstone is a continental hotspot, a different lab. Here the crater and channel stay while the slope steepens as you raise the slider. Ask why sticky explodes and runny pours. That question is the mechanism.",
      "Leave Viscosity low. This is a shield: a crater, a wide slope, low-viscosity basalt. Drop it further and a fissure opens — Iceland’s habit, not a cube. Raise the slider. The same conduit steepens into a stratovolcano. Keep going and an ash column appears only because the melt is sticky. Slice or step to the conduit: magma is a path, not a random cone. Name Hawaii, Iceland, Cascades after the shapes, not before. Orbit. Then sit down in Check.",
      "Without the canvas viscosity is still the plot. Shield volcanoes: low-viscosity basalt, long flows, gentle slopes — Hawaii. Stratovolcanoes: stickier, gassier magma, layers of lava and ash, steep cones — Cascadia’s arc. A rift eruption can be a basalt fissure at a divergent boundary — Iceland. Not all volcanoes explode. Basalt often pours. Explosions need gas and stickiness. San Andreas is a slide, not this chain. One slider, three shapes. Do not teach supervolcano headlines as the whole course. Viscosity still decides the shape.",
    ],
    glossary: [
      { term: "Viscosity", def: "Resistance to flow. High viscosity plus gas makes explosive eruptions more likely." },
      { term: "Shield volcano", def: "Broad, gentle edifice from low-viscosity basalt. Mauna Loa type." },
      { term: "Stratovolcano", exam: "Composite cone", def: "Steep cone of lava and ash from stickier magma. Cascades type." },
      { term: "Fissure eruption", def: "Magma erupting along a crack, often basalt at a rift. Iceland habit." },
      { term: "Basalt", def: "Low-silica, typically runny lava. Builds shields and many rift flows." },
      { term: "Conduit", def: "The path magma takes through the edifice. Not a random cone." },
      { term: "Pyroclastic", def: "Fragmented material from explosive eruption: ash, pumice, blocks." },
    ],
    misconception: { claim: "All volcanoes explode.", truth: "Basalt often pours. Explosions need gas and stickiness." },
    misconceptions: [
      { claim: "All volcanoes explode.", truth: "Basalt often pours. Explosions need gas and stickiness." },
      { claim: "Bigger volcano means bigger boom.", truth: "Viscosity and gas set the style. Shields can be huge and quiet-ish." },
      { claim: "Every volcano sits on the Ring of Fire.", truth: "Hawaii is a hotspot. Iceland is a ridge plus a plume." },
    ],
    cases: [{ slug: "hawaii", label: "Hawaii shields" }, { slug: "iceland", label: "Iceland rift" }],
    teacher: {
      script:
        "Slider low. This is a shield: low viscosity basalt, a crater, a wide slope. Hawaii.\nDrop viscosity further. A fissure opens. Iceland is this, not a cartoon cube.\nRaise viscosity. The same conduit steepens into a stratovolcano. Cascades, St Helens.\nKeep raising. An ash column appears only when magma is sticky.\nSlice or step to the conduit. Magma is a path, not a random cone.\nAsk why sticky magma explodes and runny magma pours. Viscosity is the plot.\nAll volcanoes do not explode. Basalt often pours. Explosions need gas and stickiness.\nThat is the misconception.\nDo not teach supervolcano headlines as the whole course. Do not put San Andreas under a cone.\nFinish in Check.",
      pitfalls: [
        "Supervolcano headlines as the whole course.",
        "All volcanoes explode.",
        "Ring of Fire as the only address.",
        "Shields called worn-down stratovolcanoes.",
      ],
    },
    sources: [{ label: "USGS volcanoes" }, { label: "IMO" }],
    controls: {
      time: "none",
      extra: [{ key: "visc", label: "Viscosity", min: 0, max: 1, step: 0.01, default: 0.25 }],
      slice: true,
    },
  }),
  lab({
    slug: "tsunami",
    title: "Tsunami",
    hook: "Seafloor slip lifts a water column. In deep water the wave is fast and low. At the coast it stands up.",
    objective: "Play seafloor slip to a coastal wave.",
    realm: "hazards",
    ages: ["GCSE", "NGSS MS", "HS Earth Sci"],
    curriculum: ["GCSE", "NGSS MS-ESS3-2"],
    steps: steps("Slip. The column lifts.", "The wave races. Amplitude small at sea.", "Shallow water: slower, taller."),
    questions: [
      q("A tsunami starts with…", ["Wind swell", "A sudden shift of the water column, often seafloor slip", "A tide", "A sea breeze"], 1, "Not a wind wave."),
      q("In deep water a tsunami is…", ["A 30 m wall everywhere", "Fast and often unnoticed at sea", "Stationary", "Only in rivers"], 1, "Ships may not feel it."),
      q("It grows at the coast because…", ["The Moon", "Shoaling: energy in a shallower, slower water column", "Albedo", "Coriolis only"], 1, "Green’s law as a story, not a formula dump."),
      q("Katrina and Sandy’s water at the coast was…", ["A megathrust tsunami", "Storm surge from wind and pressure, not seafloor slip", "A spring tide only", "A lava delta"], 1, "Different machine. Cascadia is the tsunami drill."),
    ],
    why: [
      "A tsunami is a long-period wave from a sudden displacement of the water column, most often seafloor slip on a megathrust. Cascadia is the North American drill: Juan de Fuca under North America, a 1700 wave written in Japanese records and in drowned coastal forests. Schools on that coast practise a vertical evacuation for a reason. Hawaii feels distant Pacific tsunamis; Iceland’s ridge is usually the wrong machine. San Andreas is mostly strike-slip: it shakes, it does not typically lift a whole water column. Katrina and Sandy pushed water by wind and pressure — storm surge, a different hazard that still floods a city. Holderness and the 1953 North Sea flood are UK surge and wave attack, not a megathrust. GCSE and NGSS both need that split: displacement wave versus wind sea versus tide. Do not call a UK gale a tsunami. Do not call a hurricane a tsunami. The physics is a lifted column, a fast low wave at sea, a tall slow wave at the coast.",
      "Start with slip. A patch of seafloor jumps up (or down). The whole water column above it moves. That is the source, not a gust and not the Moon. In deep water the wavelength is huge, the amplitude is small, and the speed is high — ships may not notice. Energy is in the column, not in a wind-chopped surface. As the wave enters shallow water it shoals: speed falls roughly with the square root of depth, wavelength shortens, amplitude grows. Green’s law is that story, not a formula dump for KS3. The wave that was a ripple at sea can stand up at a harbour. Bay shape, shelf width and drawdown before the crest all matter; this lab is the cross-section, not a run-up atlas. A storm surge is wind piled against a coast plus a pressure set-up. A tide is gravity of Moon and Sun. A tsunami is displacement. Three water-level machines. Cascadia is the first. Katrina and Sandy are the second. Do not file 1953 under the first. Holderness till cliffs are ordinary storm waves plus a budget, another lab. Keep the verbs: lift, race, shoal, flood.",
      "Play from the start. The seafloor block lifts; the water column follows. Watch the pulse race across deep water: fast and low. As it reaches the shelf it slows and stands up — shoaling. Labels: Seafloor slip, Deep = fast and low, Shoaling. Orbit between the profile and the plan if both are in view. Pause at sea and ask whether a ship would feel a wall; it would not. Pause at the coast and name why it grew. Contrast once with surge: Sandy is wind and pressure, not this slip. Cascadia drills are this lab. Then sit down.",
      "Without the canvas the machine is still displacement, not wind. Seafloor slip lifts a water column. In deep water a tsunami is fast and low, often unnoticed at sea. At the coast it shoals: slower, taller, energy in a shallower column. It is not a wind storm surge. Surge is wind and pressure. Tide is the Moon and Sun. Tsunami is a sudden shift of water, often a megathrust. Cascadia is the drill. Katrina and Sandy are surge. Do not call the 1953 North Sea flood a tsunami. Green’s law is the story, not a formula dump.",
    ],
    glossary: [
      { term: "Tsunami", def: "Long-period wave from a sudden water displacement, often seafloor slip." },
      { term: "Shoaling", def: "Wave slowing and growing as it enters shallow water." },
      { term: "Storm surge", def: "Sea-level rise from wind pile-up and low pressure. Not a tsunami." },
      { term: "Megathrust", def: "The big subduction fault. Cascadia’s tsunami source." },
      { term: "Wavelength", def: "Crest to crest. A tsunami’s is huge in deep water." },
      { term: "Drawdown", def: "Sea pulling back before some tsunami crests. Not a reliable gift of time." },
      { term: "Run-up", def: "How high the water reaches on land. Not the same as deep-water amplitude." },
    ],
    misconception: { claim: "A tsunami is a wind storm surge.", truth: "Different machine. Surge is wind and pressure. Tsunami is displacement." },
    misconceptions: [
      { claim: "A tsunami is a wind storm surge.", truth: "Different machine. Surge is wind and pressure. Tsunami is displacement." },
      { claim: "A tsunami is a 30 m wall everywhere, including mid-ocean.", truth: "In deep water it is fast and low. It stands up at the coast." },
      { claim: "The 1953 North Sea flood was a tsunami.", truth: "It was a storm surge. Wrong machine." },
    ],
    cases: [{ slug: "cascadia", label: "Cascadia" }, { slug: "katrina-sandy", label: "Surge is not tsunami" }],
    teacher: {
      script:
        "Play the seafloor slip. The water column lifts.\nThe wave races. In deep water it is fast and low, often unnoticed at sea.\nShallow water: slower, taller. Shoaling: energy in a shallower, slower water column.\nA tsunami is not a wind storm surge. Surge is wind and pressure. Tsunami is displacement.\nThat is the misconception.\nDo not call the 1953 North Sea flood a tsunami.\nCascadia drills are this lab. Holderness is a different wave.\nSandy is surge, not tsunami. Contrast them once.\nGreen’s law is the story, not a formula dump.\nFinish in Check.",
      pitfalls: [
        "Calling 1953 North Sea a tsunami.",
        "A mid-ocean wall in every drawing.",
        "Surge and tsunami as synonyms.",
        "Tide and tsunami mixed because both change water level.",
      ],
    },
    sources: [{ label: "NOAA tsunami" }, { label: "USGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "tropical-cyclone",
    title: "Tropical cyclone",
    hook: "Eye, eyewall, rainbands. Warm sea is the fuel. A UK depression is usually a different machine.",
    objective: "Orbit eye/eyewall/rainbands and keep UK language honest.",
    realm: "hazards",
    ages: ["KS3", "GCSE", "NGSS MS", "APES"],
    curriculum: ["GCSE hazards", "NGSS MS-ESS3-2", "APES"],
    steps: steps("Cross-section: eye calm, eyewall violent, bands.", "Intensity slider.", "Katrina/Sandy vs a UK windy Tuesday."),
    questions: [
      q("The eyewall is…", ["The calm centre", "The ring of strongest winds and rain around the eye", "A front in Yorkshire", "A dune"], 1, "Damage ring."),
      q("Tropical cyclones need…", ["Snow cover", "Warm ocean and low shear, among other things", "A glacier", "Pangaea"], 1, "School list, not a forecast."),
      q("A UK winter storm is usually…", ["A tropical cyclone", "A midlatitude cyclone with fronts", "An eyewall", "A tsunami"], 1, "Fronts lab."),
      q("Saffir–Simpson rates…", ["Every Met Office named storm", "Tropical cyclones, not UK extra-tropical gales", "Tsunamis", "Earthquakes"], 1, "Do not put that scale on a Yorkshire wind."),
    ],
    why: [
      "Katrina and Sandy are the locators. Katrina (2005) was a large tropical cyclone on the Gulf Coast; the catastrophe in New Orleans was surge plus levée failure on a sinking delta. Sandy (2012) was a late-season hybrid that struck the New York–New Jersey Bight: surge in a funnel, high tide, a dense shoreline. Both are North Atlantic heat engines with an eye, an eyewall and rainbands — until Sandy’s hybrid caution. A UK winter storm is usually a midlatitude cyclone with fronts, not an eyewall. Met Office names storms; they are still extra-tropical unless stated. Do not brand a Yorkshire gale as a hurricane. Do not put Saffir–Simpson on a UK depression. Hawaii sees true tropical cyclones in season; Iceland and Cascadia are other machines; San Andreas is slip. GCSE hazards and NGSS want the structure named and the UK language kept honest. Warm sea is the fuel. A front is a different lab. Same word ‘cyclone’, two engines.",
      "A tropical cyclone is an organised warm-core storm over a warm ocean. The eye is a calm, often clear centre of descending air. The eyewall is the ring of strongest convection, wind and rain — the damage ring. Spiral rainbands sit outside. Fuel is latent heat from warm water, plus low vertical shear so the tower can stand, plus enough Coriolis to spin (not on the equator). That is a school list, not a forecast model. Intensity in this lab is a slider, not a 2026 track. Play spins the spiral. Slice the storm to see the eye well. Storm surge is wind pile-up and pressure, the water-level cousin of Katrina and Sandy; rainfall is a hydrograph story inland. A midlatitude cyclone is a different machine: comma cloud, warm front, cold front, energy from horizontal temperature contrast. Toggle UK low in this lab and the eye dies into that comma. Saffir–Simpson is a tropical-cyclone wind scale. It does not grade a Met Office named storm over Wales. Sandy’s hybrid nature is a teacher’s caution, not a KS3 requirement. Keep the verbs: warm sea, eye, eyewall, bands. Then say what a UK Tuesday is not.",
      "Leave the Hurricane / UK low button on Hurricane. Orbit the eye, then the eyewall, then the rainbands. Slice to cut the well. Raise Intensity; the engine is still a school box over warm sea. Play to spin the spiral. Toggle UK low: the eye goes, fronts appear, the readout says comma-shaped mid-latitude low. That toggle is the language lesson. Name the eyewall out loud while it exists. Do not put Saffir–Simpson on the UK shape. Katrina and Sandy after the structure, not instead of it. Then Check.",
      "Without the canvas the structure is still the lesson. Eye: calm centre. Eyewall: ring of strongest winds and rain. Rainbands outside. Fuel: warm ocean and low shear, among other things — a school list, not a forecast. A UK winter storm is usually a midlatitude cyclone with fronts, not an eyewall. Met Office names storms; they are still extra-tropical unless stated. Katrina and Sandy are the locators. Sandy is a hybrid caution. Do not brand a UK gale as a hurricane. Do not put Saffir–Simpson on a Yorkshire wind. Different engine.",
    ],
    glossary: [
      { term: "Tropical cyclone", exam: "Hurricane / typhoon", def: "Warm-core organised storm over a warm ocean. Name depends on basin." },
      { term: "Eye", def: "Calm centre of a tropical cyclone, often with descending air." },
      { term: "Eyewall", def: "Ring of strongest convection, wind and rain around the eye." },
      { term: "Rainband", def: "Spiral band of showers and storms outside the eyewall." },
      { term: "Storm surge", def: "Sea-level rise from wind and pressure in a cyclone. Not a tsunami." },
      { term: "Saffir–Simpson", def: "Wind-scale for tropical cyclones. Not for UK extra-tropical gales." },
      { term: "Midlatitude cyclone", exam: "Depression / extra-tropical cyclone", def: "Frontal storm driven by horizontal temperature contrast. UK winter default." },
    ],
    misconception: { claim: "Every windy UK day is a hurricane.", truth: "Different engine. Met Office names storms; they are still extra-tropical unless stated." },
    misconceptions: [
      { claim: "Every windy UK day is a hurricane.", truth: "Different engine. Met Office names storms; they are still extra-tropical unless stated." },
      { claim: "The eye is the most dangerous place.", truth: "The eyewall is the damage ring. The eye is calm. The far side still comes." },
      { claim: "Saffir–Simpson grades Met Office named storms.", truth: "That scale is for tropical cyclones. A UK depression is a different machine." },
    ],
    cases: [{ slug: "katrina-sandy", label: "Katrina / Sandy" }, { slug: "typhoon-mangkhut", label: "Typhoon Mangkhut" }],
    teacher: {
      script:
        "Slice the storm. Eye calm, eyewall the ring of strongest winds and rain, then rainbands.\nName the eyewall out loud. Damage sits there, not in the eye.\nRaise Intensity. The engine is warm ocean and low shear, among other things — a school list, not a forecast.\nToggle UK low. The eye dies. Fronts appear. A comma, not a hurricane.\nEvery windy UK day is not a hurricane. Different engine.\nThat is the misconception.\nA UK winter storm is usually a midlatitude cyclone with fronts. Met Office names storms; they are still extra-tropical unless stated.\nDo not put Saffir–Simpson on a UK gale.\nKatrina and Sandy are the locators. Sandy is a hybrid caution.\nKeep UK language honest, then sit down in Check.",
      pitfalls: [
        "Saffir–Simpson for UK gales.",
        "Eye as the damage zone.",
        "Naming every Met Office storm a hurricane.",
        "Surge called a tsunami because both wet a street.",
      ],
    },
    sources: [{ label: "NOAA NHC" }, { label: "Met Office" }],
    controls: {
      time: "none",
      extra: [{ key: "intensity", label: "Intensity", min: 0.3, max: 1, step: 0.05, default: 0.7 }],
      slice: true,
    },
  }),
];
