import type { LabMeta } from "./types";
import { lab, q, steps } from "./make";

export const SOIL_LABS: LabMeta[] = [
  lab({
    slug: "rock-cycle",
    title: "Rock cycle",
    hook: "Igneous, sedimentary, metamorphic. Arrows, not a one-way ladder. Temperature and pressure bias the path.",
    objective: "Animate the trio and use T/P sliders to bias the path.",
    realm: "soils",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "GCSE rocks", "NGSS MS-ESS2-1"],
    steps: steps("Three rocks. Arrows.", "Raise T/P: toward metamorphic/melt.", "Weathering toward sediment."),
    questions: [
      q("Metamorphic rock needs…", ["Only wind", "Heat and/or pressure on existing rock, without full melt (school)", "A beach day", "A tide"], 1, "Then it can still melt."),
      q("Sedimentary rock typically starts as…", ["Magma only", "Weathered bits deposited then lithified", "The inner core", "Clouds"], 1, "Grand Canyon walls."),
      q("The cycle is…", ["One-way", "A set of paths; rock can loop", "A hurricane", "A time zone"], 1, "Not a ladder."),
      q("Raising temperature and pressure without full melt produces…", ["A soil horizon", "Metamorphic rock", "A named storm", "A spit"], 1, "Full melt is igneous again."),
    ],
    why: [
      "The Jurassic Coast and the Grand Canyon are one rock cycle at walking distance. Dorset’s Lias, Oolite and chalk are a sedimentary sequence you can stand on in an afternoon; Arizona’s walls are sandstone, shale and limestone stacked above Vishnu Schist. A UK party names beds. A US party names formations. Both sentences are about type, not about a birthday. GCSE and NGSS both ask students to move material among igneous, sedimentary and metamorphic without treating the poster as a one-way ladder. Age is independent of type: a Palaeozoic limestone is old and sedimentary; a Holocene basalt is young and igneous. Somerset Levels alluvium was rock somewhere up-catchment. Dust Bowl silt was a mineral in a parent. Yorkshire Dales limestone is a carbonate bed waiting for carbonation. A cliff, a soil and a quarry are the same budget in different rooms. Temperature and pressure light melt and metamorphism; weathering and lithification light the other arrows. UK coast, US canyon: same machine, different outcrop.",
      "Igneous rock crystallises from melt. Intrusive bodies cool slowly and grow visible crystals; extrusive lava cools fast and is often finer. Weathering and erosion then break any rock into sediment. Deposition, burial, compaction and cementation lithify that sediment into sedimentary rock: beds you can count on a Dorset cliff or a canyon wall. If burial and tectonics raise temperature and pressure without a full melt, minerals recrystallise in the solid state. That is metamorphic rock, often foliated when directed stress is present. Raise heat further and the rock melts; magma is igneous waiting to happen again. Those are paths, not a ranking and not a staircase. Granite can weather to sand. Sandstone can become quartzite. Quartzite can melt. Limestone can become marble without ever being called young. In this lab the sliders bias the arrows: high temperature and pressure favour metamorphism and melt; cooler conditions keep the weathering arrow lit. School diagrams that draw a circle with three boxes are a cartoon of that network. The honest sentence is that any type can become any other if the conditions exist. Full melt is igneous. Change in the solid is metamorphic. Bits stuck together are sedimentary. That distinction is the plot.",
      "Orbit the trio. A granite plug with crystals sits on top. Horizontal sedimentary beds sit to the right. Foliated metamorphic beds sit to the left. Magma glows below. Play to watch the magma pulse. Raise Temperature and Pressure together. When their mean is high, hot arrows toward melt and metamorphism brighten and cool weathering arrows dim. Drop both sliders and the cool arrows return. Read T and P on the studio readout. Labels name the three rocks. Step the camera for a closer look at one type. The arrows loop both ways. Do not teach them as a ladder.",
      "Without the canvas you still have the cycle in sentences. Igneous crystallises from melt. Sedimentary is deposited bits lithified into beds. Metamorphic is existing rock changed in the solid by heat and pressure. Arrows run both ways: weathering toward sediment, burial and heat toward metamorphism and melt. The Jurassic Coast is a sedimentary sequence. Grand Canyon walls are that idea with metamorphic basement at the river. Sedimentary is not always young. Age is independent of type. Temperature and pressure bias the path; they do not invent a fourth rock. A one-way ladder is the diagram to refuse.",
    ],
    glossary: [
      { term: "Igneous", def: "Rock crystallised from melt. Intrusive cools slowly; extrusive cools at the surface." },
      { term: "Sedimentary", def: "Rock from deposited fragments or precipitates, then lithified." },
      { term: "Metamorphic", def: "Existing rock changed in the solid by heat and/or pressure, without full melt." },
      { term: "Lithification", def: "Compaction and cementation that turn sediment into sedimentary rock." },
      { term: "Foliation", def: "Layered mineral fabric from directed stress during metamorphism." },
      { term: "Magma", def: "Molten rock below the surface. Lava is the same material once it erupts." },
      { term: "Weathering (to sediment)", def: "Breakdown that feeds the sedimentary path. Not the same as erosion." },
    ],
    misconception: { claim: "Sedimentary is ‘young’ always.", truth: "Age is independent of type." },
    misconceptions: [
      { claim: "Sedimentary is ‘young’ always.", truth: "Age is independent of type." },
      { claim: "The cycle is a one-way ladder: igneous, then sedimentary, then metamorphic.", truth: "Any type can become any other if the conditions exist. Arrows loop." },
      { claim: "Metamorphic means the rock melted and froze again.", truth: "School story: change in the solid. Full melt is igneous again." },
    ],
    cases: [{ slug: "grand-canyon", label: "Grand Canyon" }, { slug: "jurassic-coast", label: "Jurassic Coast" }],
    teacher: {
      script:
        "Name the trio out loud: igneous, sedimentary, metamorphic. Point at granite, beds, foliated rock.\nThe arrows loop both ways. This is not a one-way ladder.\nRaise Temperature and Pressure. Watch the hot arrows toward metamorphic rock and melt.\nDrop both sliders. Cool weathering arrows toward sediment come back.\nSedimentary is not always young. Age is independent of type.\nThat is the misconception. Palaeozoic limestone is old and still sedimentary.\nMetamorphic needs heat and/or pressure on existing rock, without full melt in the school story. Then it can still melt.\nSedimentary typically starts as weathered bits deposited then lithified. Grand Canyon walls. Jurassic Coast beds.\nDo not teach a staircase diagram. Do not invent a fourth rock.\nFinish in Check.",
      pitfalls: [
        "One-way diagram.",
        "Age equals type.",
        "Calling marble a sediment because it was once limestone.",
        "Full melt labelled metamorphic.",
      ],
    },
    sources: [{ label: "USGS rocks" }, { label: "BGS" }],
    controls: {
      time: "none",
      extra: [
        { key: "temp", label: "Temperature", min: 0, max: 1, step: 0.05, default: 0.3 },
        { key: "pressure", label: "Pressure", min: 0, max: 1, step: 0.05, default: 0.3 },
      ],
    },
  }),
  lab({
    slug: "soil-profile",
    title: "Soil profile",
    hook: "O A E B C R — a stack, not dirt. Compare brown earth, mollisol, oxisol.",
    objective: "Name horizons and compare three profiles.",
    realm: "soils",
    ages: ["GCSE", "A-level", "NGSS MS", "APES"],
    curriculum: ["GCSE", "APES 4.3", "A-level"],
    steps: steps("Stack O to R.", "Switch UK brown earth, US mollisol, tropical oxisol.", "Oxisol: deep, leached, red. Mollisol: thick A. Brown earth: UK woodland/farm default."),
    questions: [
      q("The R horizon is…", ["Leaf litter", "Bedrock", "The ozone layer", "A front"], 1, "Rock."),
      q("A thick dark A is typical of…", ["Oxisol", "Mollisol (grassland)", "Bare dune only", "Glacier ice"], 1, "Prairies."),
      q("An oxisol is…", ["A UK peat always", "A highly weathered tropical soil", "A lava", "A tide"], 1, "Not a UK default."),
      q("The E horizon is…", ["Always peat", "A leached, often paler eluviated layer", "The inner core", "A storm surge"], 1, "Present in the brown earth; weak or gone in the mollisol and oxisol here."),
    ],
    why: [
      "A soil is a stack written by climate, organisms, relief, parent rock and time, not a single colour of mud. UK woodland and farm default is a brown earth: modest O, mixed A, a weak pale E, then B, C and bedrock. Yorkshire Dales soils over Carboniferous limestone are often thin; R is close to the boot. The US grassland pair is a mollisol: a thick dark A, little or no E, the prairie store that the Dust Bowl spent. An oxisol is the tropical end-member: deep, leached, red, not a Peak District peat. GCSE, A-level and APES all need named horizons. Geography posters that show one UK profile as universal leave a class unable to read a Great Plains pit or a laterite cut. The stack is the win because colour alone does not name a soil. O is litter. A is mineral mixed with organic. E is leached. B is accumulation. C is parent. R is rock. Say the letters before you say the place.",
      "Horizons form because water, roots, fauna and chemistry move material down and sometimes up. Organic matter collects at the top as O, then mixes into A. In wetter, forested temperate climates clay and iron can be washed from an E horizon, leaving it paler; they accumulate in B. Grasslands keep adding roots and organic matter to A, so the dark layer thickens and E may never read. In hot, wet tropics intense leaching and oxidation build a deep red B and eat the rest of the story; nutrients sit in the biomass more than in the clay. Parent rock still matters: limestone in the Dales weathers to a thin rendzina-like cover; loess and glacial till on the Great Plains gave a deep mineral start. Time is a budget. A young dune has little profile; an old tropical surface has a thick one. This lab’s three slabs are types, not every soil on Earth. Brown earth, mollisol, oxisol. Name what is thick, what is missing, and what colour the B is. That is profile literacy: three climates, three stacks, not one UK pit drawn as the world.",
      "Scrub the Profile slider through 0, 1 and 2. Brown earth, mollisol, oxisol. Read the name and the note on the slab. Orbit so O sits at the top and R at the floor. Name each horizon out loud as the letters appear. Compare A thickness: thin-to-modest on the brown earth, thick and dark on the mollisol, thinner on the oxisol above a deep red B. Look for E: present and pale on the UK default, gone on the other two here. Step the camera to a side-on cut. Do not leave until the class can point at R and not call it compost.",
      "Without the canvas the stack is still the lesson. O organic, A mixed mineral and organic, E leached, B accumulation, C parent, R bedrock. Brown earth is the UK woodland and farm default with a weak pale E. Mollisol is grassland with a thick dark A — Dust Bowl country when the cover goes. Oxisol is a highly weathered tropical soil, deep and red, not a UK peat. Yorkshire Dales limestone soils can be thin over R. Soil is not one kind of dirt. Horizons and climate write different profiles. Name the letters. Then name which layer is thick.",
    ],
    glossary: [
      { term: "Horizon", def: "A layer in a soil profile with its own colour, texture and chemistry." },
      { term: "O horizon", def: "Organic layer at the top: litter and decomposing material." },
      { term: "A horizon", def: "Upper mineral soil mixed with organic matter. Topsoil in farm talk." },
      { term: "E horizon", def: "Eluviated, often paler layer from which clay and iron have been washed." },
      { term: "B horizon", def: "Subsoil where materials accumulate. Colour and clay often change here." },
      { term: "R horizon", def: "Bedrock. Not soil." },
      { term: "Mollisol", exam: "Chernozem / grassland soil", def: "Grassland soil with a thick dark A. Prairie and steppe store." },
      { term: "Oxisol", def: "Highly weathered tropical soil; deep, leached, often red." },
    ],
    misconception: { claim: "Soil is just dirt of one kind.", truth: "Horizons and climate write different profiles." },
    misconceptions: [
      { claim: "Soil is just dirt of one kind.", truth: "Horizons and climate write different profiles." },
      { claim: "The dark layer is always the whole soil.", truth: "A is one horizon. B, C and R still sit underneath." },
      { claim: "Every country has the same stack as a UK brown earth.", truth: "Mollisols and oxisols are different machines. Teach three, not one." },
    ],
    cases: [{ slug: "yorkshire-dales", label: "Thin limestone soils" }, { slug: "dust-bowl", label: "Mollisol at risk" }],
    teacher: {
      script:
        "Name O to R out loud: organic, A, E, B, C, then bedrock.\nScrub the Profile slider: UK brown earth, US mollisol, tropical oxisol.\nMollisol: thick dark A, grassland. Oxisol: deep, leached, red. Brown earth: UK woodland and farm default.\nPoint at E on the brown earth. It is weak or gone on the other two here.\nSoil is not just dirt of one kind. Horizons and climate write different profiles.\nThat is the misconception.\nDo not teach one UK profile as universal. Yorkshire Dales can be thin over limestone. Dust Bowl is mollisol at risk.\nThe R horizon is rock. O is litter, not the whole story.\nA stack, not a colour of mud.\nFinish in Check.",
      pitfalls: [
        "Teaching one UK profile as universal.",
        "Calling the whole stack ‘topsoil’.",
        "Oxisol as a Peak District peat.",
        "R horizon as compost.",
      ],
    },
    sources: [{ label: "USDA NRCS" }, { label: "BGS soils" }],
    controls: { time: "none", extra: [{ key: "profile", label: "Profile", min: 0, max: 2, step: 1, default: 0 }] },
  }),
  lab({
    slug: "soil-texture",
    title: "Soil texture triangle",
    hook: "Sand, silt, clay. Plot a sample. Name the class. Loam is a place on the triangle, not a brand.",
    objective: "Move a point on the texture triangle and read the class.",
    realm: "soils",
    ages: ["GCSE", "A-level", "APES", "NGSS MS"],
    curriculum: ["GCSE", "APES 4.3"],
    steps: steps("Triangle. Three axes.", "Drag sand/silt/clay.", "Read loam, clay, sand…"),
    questions: [
      q("Clay particles are…", ["The coarsest", "The finest of the three", "Always yellow", "Ice"], 1, "Feel: sticky."),
      q("Loam is…", ["Pure clay", "A balanced mix near the middle — good for many farms", "Bedrock", "A cloud"], 1, "Not a brand of bag."),
      q("A soil with 90% sand is…", ["Clay", "Sand / sandy class", "Peat by definition", "A mollisol always"], 1, "Triangle."),
      q("Sand, silt and clay on the triangle must…", ["Sum to 50%", "Sum to 100%", "Ignore silt", "Be equal always"], 1, "Silt is the remainder. Move sand and clay; silt follows."),
    ],
    why: [
      "Texture is a particle-size mix, not a colour and not a bag from a garden centre. Plot sand, silt and clay, then name the USDA class. Loam is a place near the middle of the triangle, not a brand. That sentence is the UK and US share: GCSE talks sand, silt and clay; APES and NRCS use the same triangle. Somerset Levels clays and peats sit toward fine; they hold water and stick. Dust Bowl silts sat on the wind because the particles were small enough to lift once the cover went. A Yorkshire Dales rendzina over limestone can be thin and stony, not a loam by slogan. Grand Canyon colluvium and Jurassic Coast cliff falls start as rock fragments and weather toward these three sizes. Farmers care because texture sets drainage, workability and how fast a rill can cut. A sandy soil drinks and dries. A clay holds and ponds. Loam is the compromise many crops like. Colour can lie. Particle size does not.",
      "Sand, silt and clay are size classes of mineral particles. Sand is the coarsest of the three and feels gritty. Silt feels floury. Clay is the finest and feels sticky when wet because the particles have huge surface area and often a charge. Organic matter is a separate story; peat is not a point on this mineral triangle. The USDA texture triangle is a ternary plot: the three percentages must sum to 100. A class name — sand, sandy loam, loam, clay loam, clay, silt loam — is a region on that plot, not a personality. Loam sits near the middle: enough sand to drain, enough clay and silt to hold nutrients and water. Move toward a corner and the class follows the dominant size. Feel tests in the field (gritty, smooth, ribbon length) are the same triangle without the printed chart. This lab is the chart. It does not measure a real sample; it teaches the geometry so a field sentence can be plotted. Texture is not structure (crumbs and blocks) and not colour (iron, organic matter). Keep those words apart.",
      "Show the USDA triangle, not a 3D cone. Move Sand % and Clay %. Silt is the remainder so the three sum to 100. The point walks. Read the class name out loud from the readout: loam, clay, sandy loam, silt. Push sand toward 90 and name a sandy class. Push clay up until the point enters clay. Come back toward the middle and say loam as a place, not a brand of bag. Ask for a field sample in words — ‘more sand than clay’ — then plot it. Orbit if you need the labels; the skill is the point, not the camera. Finish when the class can refuse ‘brown soil’ as a texture answer.",
      "Without the canvas the triangle is still a ternary plot. Sand, silt and clay sum to 100 percent. Clay is the finest of the three; sand is the coarsest. Loam is a mixed class near the middle, not a brand of bag. Somerset Levels often sit toward clay and peat; Dust Bowl silt was fine enough to fly. Texture is particle size, not colour and not pottery. A 90 percent sand sample is a sandy class. Plot a sentence, then name the region. That is the whole check.",
    ],
    glossary: [
      { term: "Texture", def: "The sand, silt and clay proportions of the mineral soil." },
      { term: "Sand", def: "Coarsest of the three mineral sizes. Gritty. Drains fast." },
      { term: "Silt", def: "Medium size. Feels floury. Easily carried by wind and water." },
      { term: "Clay", def: "Finest mineral size. Sticky when wet. Holds water and nutrients." },
      { term: "Loam", def: "A mixed class near the middle of the USDA triangle, not a brand." },
      { term: "USDA texture triangle", def: "Ternary chart that names a class from sand, silt and clay percentages." },
      { term: "Ternary plot", def: "Three components that must sum to 100 percent. Silt is the remainder here." },
    ],
    misconception: { claim: "Clay means pottery only.", truth: "It is a particle size." },
    misconceptions: [
      { claim: "Clay means pottery only.", truth: "It is a particle size." },
      { claim: "Loam is a brand of bag.", truth: "Loam is a place near the middle of the triangle." },
      { claim: "Brown soil is a texture class.", truth: "Colour is iron and organic matter. Texture is sand, silt, clay." },
    ],
    cases: [{ slug: "somerset-levels", label: "Clay / peat levels" }, { slug: "dust-bowl", label: "Silt on the wind" }],
    teacher: {
      script:
        "Show the USDA triangle, not a 3D cone.\nMove sand, then clay. Silt is the remainder. The point walks. Read the class name out loud.\nLoam is a place near the middle, not a brand of bag.\nClay is a particle size, not a kiln. That is the misconception.\nPush sand toward 90 percent. Name a sandy class. Push clay up. Name clay.\nAsk for a field sample in words: ‘more sand than clay’ — then plot it.\nSomerset Levels sit toward fine. Dust Bowl silt sat on the wind.\nColour is not texture. Brown is not a class.\nFinish in Check.",
      pitfalls: [
        "RGB colour as texture.",
        "Loam as a shop brand.",
        "Forgetting silt must make the three sum to 100.",
        "Peat treated as a mineral corner.",
      ],
    },
    sources: [{ label: "USDA texture triangle" }],
    controls: {
      time: "none",
      extra: [
        { key: "sand", label: "Sand %", min: 0, max: 100, step: 1, default: 40 },
        { key: "clay", label: "Clay %", min: 0, max: 100, step: 1, default: 20 },
      ],
    },
  }),
  lab({
    slug: "weathering",
    title: "Weathering",
    hook: "Mechanical, chemical, biological — three blocks, side by side, not a ranking of virtue.",
    objective: "Compare frost, carbonation, and roots on three rocks.",
    realm: "soils",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "GCSE", "NGSS MS-ESS2-1"],
    steps: steps("Three blocks.", "Frost wedges. Carbonation pits. Roots.", "Climate chooses the mix."),
    questions: [
      q("Frost shattering is…", ["Chemical", "Mechanical", "A tide", "A front"], 1, "Water freezes, expands."),
      q("Carbonation attacks…", ["Granite first always", "Carbonate rocks with weak carbonic acid", "Gold", "Ice only"], 1, "Karst cousin."),
      q("Biological weathering includes…", ["Only lions", "Roots, lichens, burrowers", "Tsunamis", "Time zones"], 1, "Living agents."),
      q("Weathering versus erosion…", ["The same word", "Weathering breaks in place; erosion moves the bits", "Erosion only happens at sea", "Weathering is a forecast"], 1, "Break versus transport."),
    ],
    why: [
      "Weathering is rock breakdown in place. It is not the Met Office forecast and it is not erosion. UK limestone country makes the chemical case: Yorkshire Dales pavements, grykes and swallow holes are carbonation along joints, rainwater plus carbon dioxide as a weak acid. The US pair in this lab is the Grand Canyon stack: joints, unloading, and freeze on the rim open the walls; the river then exports what falls. Jurassic Coast cliffs add salt, spray and lithology changes along the shore. Somerset Levels sit on already-weathered fines. Dust Bowl silt was a weathered particle that wind later moved — weathering first, transport second. GCSE and NGSS both want three agents named without a league table: mechanical, chemical, biological. Climate chooses the mix. Frost-heavy uplands favour ice in cracks. Warm wet carbonate country favours carbonation. Roots and lichens work wherever they can sit. Three blocks, side by side, not a ranking of virtue.",
      "Mechanical weathering breaks rock without changing the minerals. Frost shattering is the school example: water in a joint freezes, expands, and wedges the block. Unloading and thermal stress do similar work on canyon rims and granite sheets. Chemical weathering changes the minerals. Carbonation is the carbonate special: carbonic acid from rain and soil air attacks calcite, widening joints into grykes and feeding caves. Hydrolysis and oxidation work on silicates and iron; they matter, but this lab’s chemical block is the karst cousin you can see. Biological weathering is living agents: roots pry joints, lichens etch, burrowers mix. It is not a separate physics; it is mechanical and chemical work done by organisms. The three overlap. A root in a Dales gryke is biological and mechanical on a chemically opened crack. Weathering produces sediment and soil parent material; erosion carries it. Mix those verbs and the Grand Canyon becomes a riddle: the walls weather and fail, the river removes. Climate sets rates, not moral rank. Cold wet, warm wet, and rooted surfaces write different mixes of the same three blocks on any one hillside.",
      "Play. Three blocks advance together. Left: frost wedges a granite cube as ice thickens in the crack. Middle: carbonation pits a carbonate face — the karst cousin. Right: a root thickens in a joint. Orbit so each agent is named. They are not a ranking. Pause and ask which block would dominate in the Dales (chemical on limestone) and which on a freezing canyon rim (mechanical). Do not skip the labels Physical, Chemical, Biological. The readout says three mechanisms side by side. That is the lesson. Then sit down.",
      "Without the canvas the three agents still stand. Mechanical: frost shattering, water freezes and expands in a crack. Chemical: carbonation, weak carbonic acid on carbonate rock — Yorkshire Dales karst. Biological: roots, lichens, burrowers. Weathering is rock breakdown, not the weather forecast. Weathering breaks in place; erosion moves the bits. Climate chooses the mix; there is no league table. Grand Canyon joints and Dales grykes are the locators. Name break versus transport before you leave the page. Play is optional; the three agents are not.",
    ],
    glossary: [
      { term: "Mechanical weathering", exam: "Physical weathering", def: "Break without composition change. Frost, unloading, thermal stress." },
      { term: "Chemical weathering", def: "Change the minerals. Carbonation, hydrolysis, oxidation." },
      { term: "Biological weathering", def: "Living agents: roots, lichens, burrowers. Mechanical and chemical work by organisms." },
      { term: "Frost shattering", exam: "Freeze–thaw", def: "Water in a joint freezes, expands, and wedges the rock." },
      { term: "Carbonation", def: "Weak carbonic acid attacking carbonate rock. Karst’s chemistry." },
      { term: "Weathering", def: "Rock breakdown in place. Not the atmosphere’s mood." },
      { term: "Erosion", def: "Movement of weathered material by water, wind, ice or gravity." },
    ],
    misconception: { claim: "Weathering is weather.", truth: "Weathering is rock breakdown. Weather is the atmosphere’s mood." },
    misconceptions: [
      { claim: "Weathering is weather.", truth: "Weathering is rock breakdown. Weather is the atmosphere’s mood." },
      { claim: "Weathering and erosion are the same word.", truth: "Weathering breaks in place. Erosion moves the bits." },
      { claim: "Chemical weathering is ‘stronger’ than mechanical.", truth: "Climate chooses the mix. Not a ranking of virtue." },
    ],
    cases: [{ slug: "yorkshire-dales", label: "Carbonation" }, { slug: "hong-kong-landslide", label: "Hong Kong granite saprolite" }],
    teacher: {
      script:
        "Point at each of the three blocks: mechanical, chemical, biological.\nPlay. Frost wedges: water freezes, expands. Mechanical.\nCarbonation pits carbonate rock with weak carbonic acid. Chemical. Karst cousin. Dales.\nRoots, lichens, burrowers. Biological.\nClimate chooses the mix. Not a ranking of virtue.\nWeathering is not weather. Weathering is rock breakdown. Weather is the atmosphere’s mood.\nThat is the misconception.\nDo not mix erosion with weathering. Weathering breaks. Erosion moves. Grand Canyon walls weather; the river exports.\nFinish in Check.",
      pitfalls: [
        "Erosion vs weathering mix-up.",
        "Weathering as the forecast.",
        "Ranking the three agents as good, better, best.",
        "Carbonation taught on granite as the default.",
      ],
    },
    sources: [{ label: "BGS weathering" }, { label: "USGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "soil-erosion",
    title: "Soil erosion",
    hook: "Rain splash, rill, wind. Vegetation on, the A horizon stays. Vegetation off, it leaves.",
    objective: "Toggle cover and watch splash, rill, and wind.",
    realm: "soils",
    ages: ["KS3", "GCSE", "NGSS MS", "APES"],
    curriculum: ["GCSE", "APES 4.3", "NGSS"],
    steps: steps("Bare soil. Splash. Rill. Wind.", "Vegetation on.", "Dust Bowl is this toggle in history."),
    questions: [
      q("Rain splash…", ["Builds mountains", "Detaches particles at the surface", "Is a tide", "Is a geyser"], 1, "First move."),
      q("A rill is…", ["A glacier", "A small channel cut by running water", "A front", "A planet"], 1, "Then gully."),
      q("Vegetation reduces erosion because…", ["It heats magma", "Cover and roots hold particles and slow water/wind", "It creates tsunamis", "It reverses plates"], 1, "The toggle."),
      q("Wind erosion of dry bare soil is…", ["A tsunami", "Deflation and transport of loose particles", "A lava flow", "A spring tide"], 1, "Dust Bowl headline. Water still cuts rills when it rains."),
    ],
    why: [
      "An A horizon is a budget, not an infinite floor. Cover and roots hold it. Bare ground gives it away. The Dust Bowl on the southern Great Plains is the US scale of that sentence: prairie plough, drought, wind, and silt that left the county. UK pairs are smaller and wetter — peaty upland scars, Somerset Levels fields that lose fines when winter rain sits on bare maize, Jurassic Coast and Dales slopes that rill after a wet week. Same physics, different storm. GCSE and APES both want splash, rill and wind named before anyone reaches for a sermon. Raindrop impact detaches. Flow concentrates into rills, then gullies. Wind lifts dry loose grains: deflation. Vegetation raises roughness, intercepts drops, and ties particles with roots. Grand Canyon walls are rock weathering plus export; this lab is the soil skin. Process first. History second. The 1930s are this toggle in the archive, not a morality play without a mechanism.",
      "Detachment, then transport, then deposition somewhere else. Rain splash is the first detachment on bare soil: a drop hits, a particle jumps, a crust can form. Once water flows, shear in tiny threads cuts rills — small channels you can step across — which can deepen into gullies. Gradient, texture and storm intensity set the rate. Clay and silt travel in suspension; sand hops. Wind needs dry, loose, unsheltered grains; it is deflation and saltation, the Dust Bowl headline, not a desert-dune textbook by default. Vegetation works three ways: canopy intercepts splash, stems slow water and wind, roots bind. Take the cover off and the same storm writes channels on the plot. Keep it on and the A horizon stays. The lab exaggerates rill depth so the class can see them; real rills are often centimetres. That caption is on the studio. Texture from the triangle lab matters here: silt is easy to lift; a Somerset clay may slake and crust; a sandy A can both drain and blow. Land use is a roughness choice. The physics does not moralise. It just moves particles when nothing holds them.",
      "Two plots sit side by side. Left is bare: play the storm and watch splash drops, then rills cut the surface, then a wind arrow. Right is cover: cones of vegetation, the A horizon intact. Play through a storm cycle. Orbit from the bare rills to the vegetated plot. Read the studio line: storm fraction, bare rills, vegetated plot stays. Name splash, rill, deflation out loud before you sit down. If Vegetation is on the bar, leave the comparison as two plots; the mechanism is cover versus none. Dust Bowl is the history after the process.",
      "Without the canvas the toggle is still the lesson. Bare soil: rain splash detaches, rills cut, wind can lift dry fines. Vegetation on: cover and roots hold the A horizon and slow water and wind. A rill is a small erosional channel; a gully is the next size. Deflation is wind removing loose particles. Soil is not infinite. Dust Bowl spent a prairie A horizon. Somerset Levels and UK uplands are the same idea at smaller, wetter scale. Process first. Then the history. Name splash, rill, wind. Then sit down.",
    ],
    glossary: [
      { term: "Rain splash", def: "Drop impact that detaches particles at the soil surface." },
      { term: "Rill", def: "Small erosional channel cut by running water. Can grow into a gully." },
      { term: "Gully", def: "Larger than a rill; a channel you cannot remove with ordinary tillage." },
      { term: "Deflation", def: "Wind removing loose particles from a surface." },
      { term: "A horizon", def: "Upper mixed mineral-organic soil. The budget this lab spends." },
      { term: "Cover", def: "Vegetation or residue that intercepts splash and raises roughness." },
      { term: "Saltation", def: "Grains hopping in wind or water. Sand’s usual travel mode." },
    ],
    misconception: { claim: "Soil is infinite.", truth: "A horizon is a budget. Dust Bowl spent it." },
    misconceptions: [
      { claim: "Soil is infinite.", truth: "A horizon is a budget. Dust Bowl spent it." },
      { claim: "Only wind erodes soil.", truth: "Splash and rill are water. Wind is the dry extra. Name all three." },
      { claim: "Vegetation is decoration.", truth: "Cover and roots are the hold. Bare is the experiment." },
    ],
    cases: [{ slug: "dust-bowl", label: "Dust Bowl" }, { slug: "loess-plateau", label: "Loess Plateau" }],
    teacher: {
      script:
        "Two plots. Bare on the left, cover on the right.\nPlay the storm. Splash detaches, then rills cut, then wind on the bare plot.\nRain splash is the first move. A rill is a small channel. Then gully.\nThe vegetated plot holds. Cover and roots slow water and wind.\nSoil is not infinite. An A horizon is a budget. Dust Bowl spent it.\nThat is the misconception.\nDust Bowl is this toggle in history. Peaty UK uplands and Somerset bare fields are the same idea at smaller scale.\nProcess first, then the history. Do not moralise without the mechanism.\nName splash, rill, deflation before you sit down.\nFinish in Check.",
      pitfalls: [
        "Moralising without process.",
        "Wind-only story on a wet UK field.",
        "Calling every channel a canyon.",
        "Inventing Dust Bowl tonnages.",
      ],
    },
    sources: [{ label: "USDA NRCS" }, { label: "NOAA Dust Bowl" }],
    controls: { time: "none", toggles: [{ key: "veg", label: "Vegetation", defaultOn: true }] },
  }),
];
