import type { LabMeta } from "./types";
import { lab, q, steps, mc } from "./make";

/** Eight curriculum-gap labs. Built only after the original 54 were projector-ready. */
export const WAVE6_LABS: LabMeta[] = [
  lab({
    slug: "mass-movement",
    title: "Mass movement",
    hook: "Holderness till does not wait for a wave. After rain the cliff rotates on a curved shear and the toe shoves the beach.",
    objective: "Name crown, shear surface and toe on a rotational slump, and say what rain does to the strength of till.",
    realm: "landforms",
    ages: ["GCSE", "A-level", "NGSS MS", "HS Earth Sci"],
    curriculum: ["GCSE AQA 3.1.3.2", "NGSS MS-ESS2-2"],
    steps: steps("Name crown, scar, shear, toe on a still cliff.", "Raise pore pressure. The block rotates.", "Rain weakens till. Waves only remove the toe."),
    questions: [
      q("A rotational slump moves on…", ["A vertical cliff face only", "A curved shear surface, like a spoon scoop", "A sand dune slipface", "A mid-ocean ridge"], 1, "The back tilts; the toe shoves."),
      q("Rain makes till more likely to fail because…", ["It freezes the cliff", "Pore water pressure reduces effective strength", "It adds longshore drift", "It raises viscosity of magma"], 1, "Wet till is weaker till."),
      q("If I raise the rain slider, what should the block do?", ["Stand taller", "Rotate: crown drops, toe shoves seaward", "Turn into a shield volcano", "Become a contour"], 1, "Rotation is the plot."),
      q("Palos Verdes slides are the same machine as Holderness because…", ["Both sit on basalt shields", "Weak coastal sediment fails on a curved surface after water is added", "Both are transform faults", "Both are rain shadows"], 1, "Place changes. Mechanism does not."),
    ],
    why: [
      "Holderness loses metres of till each year. Waves undercut, but the cliff also fails on its own after rain: a rotational slump, crown dropping, toe shoving the beach. Palos Verdes, California, is the US pair — weak coastal sediment, water in the pores, a curved shear. AQA coasts and NGSS mass wasting both want this as a process you can turn, not a photograph of a scar. If a class only blames the North Sea, they will miss the wet week that actually dropped the block.",
      "Input is water in the pores. Till is glacial sediment: strong when dry-ish, weak when saturated. Effective strength falls as pore pressure rises. Failure finds a curved surface. The head drops and tilts back; the toe shoves out. That is a slump, not a rockfall and not a flow. What moves: the block, rotating about a hinge. What does not: the idea of a shear surface. What is conserved: mass of the failed slice, until waves pick the toe apart. The lie the model tells: one clean spoon-shaped cut, sped up from days to a slider. Real Holderness is many slices, many wet weeks. Vertical exaggeration so the back row can see the rotation. Waves in the coasts lab remove debris. This lab is the failure itself.",
      "Leave rain low. Name crown, scar, shear, toe. Raise pore pressure. Watch the block rotate — do not skip to the beach. Keyboard: Space play, arrows, L labels, R reset, P projector. The rain slider is the plot. Ask what the third row thinks makes the cliff fall before you move it.",
      "Without the canvas: a rotational slump rides a curved shear. Rain raises pore pressure and the till fails. Crown drops, toe shoves. Holderness till; Palos Verdes coastal slides. Waves remove the toe later. Rockfall is a different machine: free fall of jointed rock. This lab is the spoon scoop. That is enough for Check.",
    ],
    glossary: [
      { term: "Rotational slump", def: "A slice of slope that rotates on a curved shear. Crown drops; toe shoves." },
      { term: "Shear surface", def: "The failure plane. Curved in a slump. Not a vertical cliff face." },
      { term: "Crown", def: "The upslope crack and head of the failed block." },
      { term: "Toe", def: "The downslope bulge. On a coast, waves pick it apart." },
      { term: "Pore pressure", def: "Water pressure in the gaps. Raised, it reduces effective strength." },
      { term: "Till", def: "Unsorted glacial sediment. Holderness cliffs are till. Weak when wet." },
      { term: "Mass movement", exam: "Mass wasting", def: "Downslope movement of rock or soil under gravity. Water is a trigger, not the transport." },
    ],
    misconception: { claim: "The sea ate the whole cliff in one bite.", truth: "Waves remove debris. Failure often starts as a wet slump on a curved shear." },
    misconceptions: [
      mc("The sea ate the whole cliff in one bite.", "Waves remove debris. Failure often starts as a wet slump on a curved shear."),
      mc("Landslides are just fast rockfalls.", "A slump rotates. A flow mixes. A fall is free. Name the machine."),
      mc("Dry cliffs are the dangerous ones.", "Pore water is the usual trigger in till. Rain first, then the drop."),
    ],
    cases: [{ slug: "holderness", label: "Holderness till cliffs" }, { slug: "hong-kong-landslide", label: "Hong Kong slopes" }],
    teacher: {
      script:
        "Name crown, scar, shear, toe on a still cliff. Do not play yet.\\nAsk the third row what will make it fall. Wait.\\nRaise rain. The block rotates. Crown drops. Toe shoves.\\nThat is a slump, not a bite from the sea.\\nHolderness till. Palos Verdes is the same machine.\\nWaves pick the toe apart later — coasts lab, not this one.\\nPore pressure reduces strength. Say that in school words.\\nSpace, L, P. Then Check.",
      pitfalls: [
        "Blaming only waves.",
        "Calling every failure a rockfall.",
        "Treating dry cliffs as the hazard.",
      ],
    },
    sources: [{ label: "BGS mass movement" }, { label: "USGS landslides" }],
    controls: {
      time: "none",
      extra: [{ key: "rain", label: "Pore pressure", min: 0, max: 1, step: 0.02, default: 0.15 }],
    },
  }),
  lab({
    slug: "rain-shadow",
    title: "Rain shadow",
    hook: "The Lake District is wet on the west. Penrith, just over the ridge, is drier. The mountain is a barrier, not a cloud factory.",
    objective: "Lift moist air over a ridge, watch it cool and drop rain windward, and say why the leeward slope is dry.",
    realm: "atmosphere",
    ages: ["KS3", "GCSE", "NGSS MS", "APES"],
    curriculum: ["GCSE AQA 3.1.2", "NGSS MS-ESS2-4", "APES 4.8"],
    steps: steps("Moist air hits the ridge.", "Raise the barrier. Windward rain, leeward dry.", "Sierra Nevada is the same machine at a larger scale."),
    questions: [
      q("Air rising on the windward slope…", ["Heats and dries", "Cools, and water can condense", "Turns into a plate", "Becomes a tsunami"], 1, "Adiabatic cooling. Clouds on the upslope."),
      q("A rain shadow sits…", ["On the windward coast always", "Leeward of a barrier, where air has already dropped its water", "Only at the equator", "Inside the outer core"], 1, "The mountain took the rain first."),
      q("If I raise ridge height, what happens?", ["Both sides get wetter equally", "Windward precipitation increases; the lee dries further", "The ocean vanishes", "Coriolis switches off"], 1, "A taller barrier is a sharper shadow."),
      q("Owens Valley east of the Sierra is dry for the same reason Penrith is drier than Keswick because…", ["Both sit in a transform fault", "Moist air rose, rained, and descended dry", "Both are till cliffs", "Both are at 60°N"], 1, "Barrier first. Latitude second."),
    ],
    why: [
      "Keswick is wet. Penrith, over the Helvellyn ridge, is drier. The Lake District is a barrier in the westerlies, not a magic cloud. The Sierra Nevada does the same job at a continental scale: California’s Central Valley and the Owens Valley sit in the lee. GCSE weather and APES 4.8 both want orographic lift as a 3D machine, not a textbook cross-section you cannot turn. If a class thinks mountains ‘make rain’, they will not understand a desert next door.",
      "Input is moist air forced up. As the parcel rises it expands and cools. Relative humidity climbs; cloud and rain on the windward face. Over the crest the air descends, compresses, warms, and dries. That is the rain shadow. What moves: the parcel, the cloud, the rain streaks. What does not: the ridge, until you raise it. What is conserved: water in the parcel until it rains out. The lie: a single ridge, a single wind, no season. Real Lake District weather has fronts as well. Real Sierra has a rain shadow and a seasonal snowpack. This lab isolates the barrier. Coriolis is not invited. The three-cell lab is the planetary machine; this is the hill in the way.",
      "Point at the windward cloud before any place names. Raise Ridge height. Watch the lee dry. Keyboard: Space, L, R, P. The wind slider is optional weather; the ridge is the plot. Name Keswick then Penrith, then Sierra then Owens, after the air has moved.",
      "Without WebGL: moist air rises, cools, rains on the windward slope, then descends dry. That is a rain shadow. Lake District west versus Penrith. Sierra Nevada versus Owens Valley. Mountains do not make rain from nothing; they force air up. A taller ridge is a sharper shadow. That is enough for Check.",
    ],
    glossary: [
      { term: "Orographic rainfall", def: "Rain forced by air rising over high ground." },
      { term: "Rain shadow", def: "Dry region leeward of a barrier, after the air has already dropped water." },
      { term: "Windward", def: "The upslope side that faces the incoming moist air." },
      { term: "Leeward", exam: "Lee", def: "The downslope side. Air descends, warms, dries." },
      { term: "Adiabatic cooling", def: "A rising parcel expands and cools without heat being taken out by a fridge. School mechanism for cloud on the upslope." },
      { term: "Föhn / chinook", def: "Warm dry descent on the lee. A named wind, same machine." },
      { term: "Barrier", def: "The ridge that forces the lift. Height matters. Geology of the rock does not, in this lab." },
    ],
    misconception: { claim: "Mountains make rain.", truth: "Mountains force air up. The water was already in the air." },
    misconceptions: [
      mc("Mountains make rain.", "Mountains force air up. The water was already in the air."),
      mc("The desert next door means the mountain is in a different climate belt.", "Often it is the same air, after the rain fell."),
      mc("Leeward slopes are wet because clouds spill over.", "Descent warms and dries. Spillover happens; it is not the shadow."),
    ],
    cases: [{ slug: "lake-district", label: "Lake District west vs Penrith" }, { slug: "colorado", label: "Sierra / Owens rain shadow" }],
    teacher: {
      script:
        "Point at moist air hitting the ridge. Do not name places yet.\\nAsk where the rain will fall. Wait.\\nRaise the barrier. Windward cloud. Lee dries.\\nKeswick wet, Penrith drier. Same air.\\nSierra Nevada, then Owens Valley. Same machine, bigger ridge.\\nMountains do not make rain from nothing.\\nSpace, L, P. Then Check.",
      pitfalls: [
        "Mountains as cloud factories.",
        "Confusing rain shadow with latitude belts.",
        "Calling every dry valley a desert climate type.",
      ],
    },
    sources: [{ label: "Met Office orographic rain" }, { label: "NOAA / WRCC Sierra precipitation" }],
    controls: {
      time: "none",
      extra: [
        { key: "ridge", label: "Ridge height", min: 0.3, max: 1, step: 0.02, default: 0.7 },
        { key: "wind", label: "Moist wind", min: 0.2, max: 1, step: 0.05, default: 0.7 },
      ],
    },
  }),
  lab({
    slug: "groundwater",
    title: "Groundwater",
    hook: "A Chalk well in Yorkshire and an Ogallala centre-pivot in Kansas both drink a store you cannot see. The water table is a surface, not a underground lake.",
    objective: "Find the water table in a cut hillside, lower it with a well, and say what an aquifer is — and is not.",
    realm: "water",
    ages: ["GCSE", "A-level", "NGSS MS", "APES"],
    curriculum: ["GCSE", "A-level water cycle", "NGSS MS-ESS2-4", "APES 4.2"],
    steps: steps("Read the water table on the cut.", "Pump the well. The cone of depression.", "Confined versus unconfined in one sentence."),
    questions: [
      q("The water table is…", ["An underground lake with a shore", "The top of the saturated zone in the pores", "A river under the ground always", "The outer core"], 1, "Pores full of water. Not a cave lake."),
      q("An aquifer is…", ["Any hole", "A rock or sediment that stores and yields useful water", "Only granite", "A rain shadow"], 1, "Chalk and Ogallala sands both qualify. Clay often does not."),
      q("If I pump the well, what happens to the water table nearby?", ["It rises into a fountain", "It lowers in a cone of depression", "The ocean falls", "Till becomes magma"], 1, "You are mining a store."),
      q("Yorkshire Chalk and the Ogallala are paired in this lab because…", ["Both are lava tubes", "Both are major aquifers people actually drink, one UK, one US", "Both are till cliffs", "Both sit on San Andreas"], 1, "Same machine. Different rock."),
    ],
    why: [
      "Yorkshire’s Chalk feeds springs and public supply. The Ogallala, under the High Plains, feeds centre-pivots that wrote the Dust Bowl’s agricultural sequel. Both are groundwater: water in pores, a water table you can draw, a well that mines a store. A-level water and APES groundwater both fail students who picture an underground river with banks. If you cannot see the table on a cut face, you will not understand a drought, a spring line, or why a well goes dry.",
      "Input is recharge from rain, and a pump. Pores below the water table are saturated. Above it, unsaturated. An unconfined aquifer has the table as its top. A confined aquifer sits under an aquitard; pressure can push a flowing well. What moves: the table, the cone around the well. What does not: the rock. What is conserved: water as a budget — pump faster than recharge and the table falls. The lie: a glass tank with a blue lake. Real Chalk is a dual-porosity rock, fractures plus matrix. Real Ogallala is sediment, not a cave. This cutaway is a teaching tank. Springs appear where the table hits the hillside. That sentence is the field trip.",
      "Read the table on the cut before you pump. Lower the well slider. Watch the cone. Toggle confined if you need the aquitard lid. Keyboard: L, R, P, arrows on the table. Ask where a spring would break out before you reveal the label.",
      "Without the canvas: groundwater lives in pores. The water table is the top of the saturated zone, not an underground lake. A well mines that store and draws a cone of depression. Chalk in Yorkshire; Ogallala under Kansas. Recharge slowly; pump fast and the table falls. A spring is the table meeting the hill. That is enough for Check.",
    ],
    glossary: [
      { term: "Water table", def: "Top of the saturated zone. A surface through the pores, not a lake shore." },
      { term: "Aquifer", def: "Rock or sediment that stores and yields useful water." },
      { term: "Aquitard", def: "A layer that slows flow. Clay, often. The lid on a confined aquifer." },
      { term: "Cone of depression", def: "Lowering of the table around a pumping well." },
      { term: "Recharge", def: "Water added to the aquifer, usually from rain and infiltration." },
      { term: "Spring line", def: "Where the water table meets the hillside and water emerges." },
      { term: "Confined aquifer", def: "Saturated rock under an aquitard. Pressure can drive a flowing well." },
    ],
    misconception: { claim: "Groundwater is an underground river or lake.", truth: "It is water in pores. The table is a surface through sediment or rock." },
    misconceptions: [
      mc("Groundwater is an underground river or lake.", "It is water in pores. The table is a surface through sediment or rock."),
      mc("Wells create water.", "Wells mine a store. Pump faster than recharge and the table falls."),
      mc("All rock is aquifer.", "Granite and clay often yield little. Chalk and clean sand often yield a lot."),
    ],
    cases: [{ slug: "yorkshire-dales", label: "Yorkshire Chalk / limestone water" }, { slug: "dust-bowl", label: "Ogallala under the High Plains" }],
    teacher: {
      script:
        "Point at the cut. The blue is pores, not a cave lake.\\nName the water table. Ask where a spring would break out.\\nPump the well. The cone of depression.\\nYou are mining a store. Recharge is slow.\\nYorkshire Chalk. Ogallala sands. Same machine.\\nToggle confined once so they hear aquitard.\\nL, P. Then Check.",
      pitfalls: [
        "Underground rivers as the default picture.",
        "Wells as magic water creators.",
        "Every rock called aquifer.",
      ],
    },
    sources: [{ label: "BGS groundwater" }, { label: "USGS Ogallala / High Plains aquifer" }],
    controls: {
      time: "none",
      extra: [
        { key: "table", label: "Water table", min: 0.15, max: 0.85, step: 0.02, default: 0.55 },
        { key: "pump", label: "Pump", min: 0, max: 1, step: 0.05, default: 0 },
      ],
      toggles: [{ key: "confined", label: "Confined lid" }],
    },
  }),
  lab({
    slug: "isostasy",
    title: "Isostasy",
    hook: "Scotland is still rising after the ice. Hudson Bay is still rising too. The crust floats. Load it, it sinks. Unload it, it comes back.",
    objective: "Load a crustal block with ice, watch it sink into the mantle, unload it, and name rebound.",
    realm: "interior",
    ages: ["A-level", "HS Earth Sci", "NGSS MS"],
    curriculum: ["A-level plate tectonics background", "NGSS HS-ESS2-1"],
    steps: steps("A crustal block floats on a denser mantle.", "Add ice. The block sinks.", "Remove ice. Rebound. Scotland and Hudson Bay."),
    questions: [
      q("Isostasy means…", ["Plates do not move", "The crust floats in a denser mantle, like wood in water", "The Moon pulls continents", "Wind piles till"], 1, "Archimedes for lithosphere."),
      q("After an ice sheet melts, the land…", ["Stays down forever", "Rises as the mantle flows back — glacial rebound", "Turns into a hotspot", "Becomes a rain shadow"], 1, "Scotland and Hudson Bay are still coming up."),
      q("If I add ice on the slider, the crustal block should…", ["Float higher", "Sink, displacing mantle", "Evaporate", "Slide like San Andreas"], 1, "Load down. Unload up."),
      q("Raised beaches in western Scotland and the rising shore of Hudson Bay are the same story because…", ["Both are till slumps", "Both unloaded ice and the crust is still rebounding", "Both are transform faults", "Both are Chalk aquifers"], 1, "Ice was the load. Time is still paying it back."),
    ],
    why: [
      "Western Scotland has raised beaches. The ice went; the land is still coming up. Hudson Bay’s shore is doing the same work. A-level and NGSS treat isostasy as why mountains have roots and why ice can bend a continent. If a class thinks crust sits on a rigid floor, rebound is a miracle and gravity anomalies are a rumour. Holderness till is a load too small to see. An ice sheet is not.",
      "Input is a load: ice, or sediment, or a mountain root. Lithosphere is rigid enough to act as a raft; the mantle beneath is solid but it creeps. Add ice, the raft sinks, mantle flows out. Remove ice, the raft rises, mantle flows back. That is glacial isostatic adjustment. What moves: the block’s height, the mantle under it. What does not: the fact of buoyancy. What is conserved: mass — ice mass leaves, rock mass stays. The lie: a wood-block-in-honey tank, sped up from millennia to a slider. Real rebound is still going, millimetres a year. The mantle is not lava. It is the same solid rock as the interior lab, creeping. Sea level in this scene is a local line so you can see emergence. Global sea level is a different budget.",
      "Start with no ice. Note the waterline. Add ice. The block sinks. Remove ice. Watch rebound. Keyboard: Space, arrows on the load, L, R, P. Ask whether the mantle is liquid before you say creep. Caption stays: mantle is solid rock that flows slowly.",
      "Without the canvas: crust floats on a denser mantle. Ice is a load. Load down, unload up. Scotland’s raised beaches and Hudson Bay’s rising shore are rebound still in progress. The mantle creeps; it is not a magma ocean. Mountains have roots for the same reason. That is enough for Check.",
    ],
    glossary: [
      { term: "Isostasy", def: "Buoyancy of the crust (and lithosphere) in a denser mantle. Load down, unload up." },
      { term: "Glacial rebound", exam: "Glacial isostatic adjustment", def: "Land rising after ice has gone. Scotland, Hudson Bay, Fennoscandia." },
      { term: "Raised beach", def: "An old shoreline now above the sea. A rebound fossil." },
      { term: "Lithosphere", def: "The rigid raft: crust plus the stiff top of the mantle." },
      { term: "Asthenosphere", def: "Weaker mantle below that can creep. Solid, not a magma ocean." },
      { term: "Root", def: "Thick crust under a mountain, the submerged part of the raft." },
      { term: "Eustatic", def: "Global sea-level change. Not the same as local rebound." },
    ],
    misconception: { claim: "The ground under our feet is a rigid floor that never moves up or down.", truth: "It floats. Ice can sink it. Melt can raise it, slowly." },
    misconceptions: [
      mc("The ground under our feet is a rigid floor that never moves up or down.", "It floats. Ice can sink it. Melt can raise it, slowly."),
      mc("Rebound means the mantle is lava.", "The mantle is solid rock that creeps. Same story as the interior lab."),
      mc("Raised beaches mean the sea fell everywhere.", "Local land rose. Global sea level is a different number."),
    ],
    cases: [{ slug: "lake-district", label: "Scottish / Lake District rebound" }, { slug: "yosemite", label: "North American ice load" }],
    teacher: {
      script:
        "A block floating on a denser mantle. Wood in water, school Archimedes.\\nAdd ice. The block sinks. Ask why before you name isostasy.\\nRemove ice. Rebound.\\nScotland’s raised beaches. Hudson Bay’s rising shore.\\nThe mantle creeps. It is not lava. Point at the interior lab if they protest.\\nMillimetres a year in the real world. This slider is a lie of time.\\nL, P. Then Check.",
      pitfalls: [
        "Rigid-floor crust.",
        "Mantle as magma ocean.",
        "Mixing eustatic sea level with local rebound.",
      ],
    },
    sources: [{ label: "BGS glacial rebound" }, { label: "USGS / NRC Hudson Bay uplift" }],
    controls: {
      time: "none",
      extra: [{ key: "ice", label: "Ice load", min: 0, max: 1, step: 0.02, default: 0.55 }],
    },
  }),
  lab({
    slug: "wilson-cycle",
    title: "Wilson cycle",
    hook: "The Atlantic is opening. One day it will close. The Caledonides and the Appalachians are an older ocean that already did.",
    objective: "Scrub rift → ocean → subduction → collision and treat the Caledonides and Appalachians as one old ocean’s scar.",
    realm: "interior",
    ages: ["A-level", "HS Earth Sci"],
    curriculum: ["A-level plate tectonics", "NGSS HS-ESS2-1"],
    steps: steps("A continent rifts.", "An ocean opens, like today’s Atlantic.", "It closes. Collision. Caledonides / Appalachians."),
    questions: [
      q("The Wilson cycle is…", ["One year of weather", "Oceans opening and closing over geologic time", "A rain shadow", "A soil texture class"], 1, "Tuzo Wilson. Supercontinents as a loop."),
      q("The Caledonides and Appalachians record…", ["A hotspot like Hawaii", "An older ocean that opened and then collided shut", "A till slump", "A Chalk aquifer"], 1, "One orogeny, two country names."),
      q("If I scrub the stage slider toward collision, the ocean should…", ["Widen forever", "Close, with trenches, then mountains", "Turn into ice", "Become a time zone"], 1, "Close, then stack."),
      q("Iceland on today’s Mid-Atlantic is which stage?", ["Collision", "Young ocean / ridge, still opening", "A rain shadow", "A slump toe"], 1, "The Atlantic is the open-ocean chapter."),
    ],
    why: [
      "Scotland’s Caledonian mountains and the US Appalachians are not two mysteries. They are one old ocean that opened and shut, then weathered. Today’s Atlantic is the open chapter of the same play. A-level tectonics and HS-ESS2 want the cycle as a process you can scrub, not a named era to memorise. If Pangaea is taught as a one-off, the next collision is a surprise.",
      "Input is time, in stages. A continent rifts — East African flavour, but this is a teaching strip. Ocean crust is born at a ridge; the basin widens. One margin can become a trench; the ocean starts to close. Collision stacks crust; a mountain belt. Erosion and isostasy then wear it. What moves: the stage. What does not: the menu of jobs from the plate-boundaries lab. What is conserved: lithosphere created and later destroyed. The lie: six clean stages, no microplates, a straight strip not a sphere. Real Wilson cycles overlap. Real Caledonian–Appalachian geometry is a puzzle of terranes. This lab is the loop, not the map. Iceland is today’s ridge, not a collision. Himalaya is collision now. The UK rides a quiet margin of a still-opening Atlantic.",
      "Scrub Stage from rift to collision. Pause on ocean. Point at Iceland as that chapter. Pause on collision. Caledonides, Appalachians. Keyboard: arrows on the stage, L, R, P. Do not skip a stage. Name the job at each stop before the place.",
      "Without the canvas: oceans open and close. Rift, ocean, trench, collision, wear. Caledonides and Appalachians are a closed ocean’s scar. The Atlantic is still opening. Iceland is a ridge. Himalaya is collision. Pangaea was a gathering, not the only one. That is enough for Check.",
    ],
    glossary: [
      { term: "Wilson cycle", def: "The opening and closing of ocean basins, named for Tuzo Wilson." },
      { term: "Rift", def: "A continent splitting. The birth of an ocean." },
      { term: "Passive margin", def: "A quiet continent–ocean edge after rifting, like much of the modern Atlantic." },
      { term: "Orogeny", def: "A mountain-building episode, often from collision." },
      { term: "Caledonides", def: "Palaeozoic collision belt through Scotland and Norway. Pair of the Appalachians." },
      { term: "Appalachians", def: "The North American scar of that same old ocean’s close." },
      { term: "Terrane", def: "A crustal piece with its own history, later stitched on. This lab omits them on purpose." },
    ],
    misconception: { claim: "Pangaea was the only time continents gathered, and the Atlantic will stay.", truth: "Oceans open and close. The Caledonides already did this play." },
    misconceptions: [
      mc("Pangaea was the only time continents gathered, and the Atlantic will stay.", "Oceans open and close. The Caledonides already did this play."),
      mc("Mountains are just wrinkled crust with no ocean in their past.", "Collision belts often close an ocean first."),
      mc("Iceland is a collision orogeny.", "Iceland is a ridge on an opening ocean."),
    ],
    cases: [{ slug: "iceland", label: "Atlantic still opening" }, { slug: "san-andreas", label: "A different job on a different edge" }],
    teacher: {
      script:
        "Start at rift. A continent splitting.\\nScrub to open ocean. Iceland lives here.\\nScrub toward a trench. The ocean starts to close.\\nCollision. Caledonides. Appalachians. One scar, two names.\\nAsk whether Pangaea was the only gathering. It was not.\\nThe Atlantic will not stay this width forever on geologic time.\\nArrows on the stage. L, P. Then Check.",
      pitfalls: [
        "Pangaea as a one-off.",
        "Iceland as a collision.",
        "Mountains with no ocean in their past.",
      ],
    },
    sources: [{ label: "BGS Caledonian" }, { label: "USGS Appalachians" }],
    controls: {
      time: "none",
      extra: [{ key: "stage", label: "Stage", min: 0, max: 5, step: 1, default: 2 }],
    },
  }),
  lab({
    slug: "soil-catena",
    title: "Soil catena",
    hook: "One Yorkshire hillside, four soils. Crest is thin and dry. Toe is thick and wet. The hill is the factory.",
    objective: "Read a crest-to-toe sequence of profiles on one slope and say what water and sediment do at each station.",
    realm: "soils",
    ages: ["GCSE", "A-level", "APES"],
    curriculum: ["GCSE soils", "A-level soils", "APES 4.3"],
    steps: steps("Four pits on one hill.", "Crest thin, backslope eroded, toe thick.", "Iowa loess hills do the same work."),
    questions: [
      q("A catena is…", ["A texture class", "A sequence of soils down one slope, linked by water and sediment", "A plate boundary", "A rain shadow"], 1, "One hill. Several profiles."),
      q("The crest soil is often thinner because…", ["It is nearer the Moon", "Water and sediment leave; the toe receives them", "It is always clay", "It sits on an aquifer lake"], 1, "Export at the top. Import at the bottom."),
      q("If I steepen the slope slider, the backslope should…", ["Thicken with peat", "Thin as erosion wins", "Become a shield volcano", "Gain a confined lid"], 1, "Steeper, more export."),
      q("A Yorkshire valley side and an Iowa loess hill pair because…", ["Both are mid-ocean ridges", "Both show crest-to-toe change on one material", "Both are till slumps only", "Both are Wilson stages"], 1, "Catena is the hill, not the county."),
    ],
    why: [
      "A single Yorkshire hillside can show a thin crest ranker, a washed backslope, and a thick wet toe. Iowa’s loess hills do the same: crest dry, toe gleyed. GCSE and APES soils are often taught as a texture triangle plus a profile poster. The catena is why those profiles differ in a field you can walk. If a class thinks soil type is only climate, they will not read a slope.",
      "Input is a slope and water. Crest: more free drainage, more erosion, thinner A and B. Backslope: transit, often the most eroded. Footslope and toe: water and sediment arrive, horizons thicken, mottles if wet. What moves: water and particles downslope. What does not: the parent material in this teaching strip. What is conserved: mass — what leaves the crest arrives below, unless a river takes it. The lie: four pits, one parent, no farmer, no time except a slider for steepness. Real Yorkshire has till over limestone in places, and land use. Real Iowa has loess thickness changing on its own. This lab isolates the hill as the factory. Texture triangle is a different lab. Profile names are a different lab. Here the sequence is the point.",
      "Name the four stations before any soil name. Crest, shoulder, backslope, toe. Steepen the slope. Watch the crest thin and the toe thicken. Keyboard: L, R, P, slope slider. Ask which pit is wettest before you reveal mottles.",
      "Without the canvas: a catena is soils down one slope. Crest exports; toe imports. Thinner and drier up top; thicker and wetter at the foot. Yorkshire valley side; Iowa loess hill. Climate sets the palette; the hill rearranges it. That is enough for Check.",
    ],
    glossary: [
      { term: "Catena", def: "A sequence of soils down a slope, linked by water and sediment." },
      { term: "Crest", def: "The top. Often thinner, freer drained." },
      { term: "Backslope", def: "The steep transit zone. Erosion often wins." },
      { term: "Toe", exam: "Footslope / toeslope", def: "The base. Water and sediment arrive. Horizons thicken." },
      { term: "Gley", def: "Grey, mottled soil from waterlogging. Common at toes." },
      { term: "Ranker", def: "A thin soil over rock, often on a crest or steep slope. School UK term." },
      { term: "Colluvium", def: "Sediment moved downslope by gravity and wash, dumped toward the toe." },
    ],
    misconception: { claim: "Soil type is only climate.", truth: "On one hillside the climate is the same. Water and sediment still rewrite the profile." },
    misconceptions: [
      mc("Soil type is only climate.", "On one hillside the climate is the same. Water and sediment still rewrite the profile."),
      mc("The thickest soil is at the crest because it is oldest.", "The toe often thickens because it receives what the crest lost."),
      mc("A profile poster is the whole soil course.", "A catena is why neighbouring pits disagree."),
    ],
    cases: [{ slug: "yorkshire-dales", label: "Yorkshire hillside catena" }, { slug: "dust-bowl", label: "Iowa / High Plains hillslope soils" }],
    teacher: {
      script:
        "Four pits on one hill. Name crest, shoulder, backslope, toe.\nAsk which is wettest. Wait for the room.\nCrest is thin. Toe is thick. Water and sediment moved downhill.\nSteepen the slope. Export increases. The toe thickens further.\nYorkshire Dales. Iowa loess. Same machine, different rock.\nClimate is not the only author of a soil. Position on the slope writes thickness.\nThis is not the texture triangle. That lab names sand, silt, clay. This lab names place.\nL labels. P projector. Then Check.",
      pitfalls: [
        "Climate-only soils.",
        "Thickest soil assumed at the crest.",
        "Texture triangle treated as a catena.",
      ],
    },
    sources: [{ label: "Cranfield / LandIS soils" }, { label: "USDA NRCS catenas" }],
    controls: {
      time: "none",
      extra: [{ key: "slope", label: "Slope", min: 0.2, max: 1, step: 0.05, default: 0.55 }],
    },
  }),
  lab({
    slug: "periglacial",
    title: "Periglacial landforms",
    hook: "The Cairngorms still carry freeze–thaw scars. Alaska still has ice wedges growing. Cold without a glacier is its own factory.",
    objective: "Grow an ice wedge and patterned ground with freeze–thaw, and distinguish this machine from a glacier’s U-trough.",
    realm: "landforms",
    ages: ["GCSE", "A-level", "HS Earth Sci"],
    curriculum: ["GCSE AQA cold environments", "A-level glacial / periglacial"],
    steps: steps("A cold ground, no ice sheet required.", "Freeze–thaw opens a wedge. Patterned ground.", "Not a U-trough. That is the glacier lab."),
    questions: [
      q("Periglacial means…", ["Under a glacier always", "Cold-climate processes at the edge of, or without, glacier ice", "A plate boundary", "A texture class"], 1, "Beside the ice. Not the ice."),
      q("An ice wedge grows because…", ["A river cuts it", "Winter cracks fill with water or snow, freeze, and widen the crack year on year", "Wind piles sand", "A hotspot punches it"], 1, "Crack, fill, freeze, repeat."),
      q("If I raise freeze–thaw cycles, patterned ground should…", ["Vanish", "Sharpen as wedges and sorting work", "Become a shield volcano", "Turn into a rain shadow"], 1, "More cycles, clearer pattern."),
      q("Cairngorm blockfields and Alaskan ice-wedge polygons pair because…", ["Both are mid-ocean ridges", "Both are freeze–thaw factories without needing a valley glacier on the spot", "Both are Chalk aquifers", "Both are Wilson collision"], 1, "Cold ground. Not a U-trough."),
    ],
    why: [
      "The Cairngorm plateau is a museum of freeze–thaw: blockfields, nivation hollows, soils that move when they thaw. Alaska’s coastal plain grows ice-wedge polygons you can see from the air. GCSE cold environments mix glacial and periglacial until students call every cold landform a glacier. This lab is the other machine. If they only remember U-troughs, they will misread a patterned-ground question and a Yorkshire-Dales limestone pavement alike — karst is yet another lab.",
      "Input is freeze and thaw, again and again. Water in a crack expands when it freezes; the crack widens; summer melt lets more water in. Ice wedges grow. Stones are heaved and sorted into polygons and stripes. Nivation hollows deepen under lingering snow. What moves: ice in the crack, stones toward polygon edges. What does not: a valley glacier. What is conserved: the ground as the stage — this is not ice flowing downhill. The lie: neat hexagons, a single season on a slider. Real polygons take centuries. Real Cairngorms are relict in today’s milder climate; Alaska is live. Vertical exaggeration on the wedge so the back row can see thickness. The glacier lab’s ice has a tongue. This ice is in the ground.",
      "Leave cycles low. A quiet ground. Raise freeze–thaw. Wedges thicken; polygons read. Keyboard: Space, arrows, L, R, P. Ask whether a glacier is required before you reveal the caption. Toggle labels on the wedge and the polygon, not on a U-trough.",
      "Without the canvas: periglacial is cold-ground process without a glacier doing the carving. Freeze–thaw grows ice wedges and patterned ground. Cairngorms relict; Alaska live. A U-trough is the glacier lab. A clint-and-gryke pavement is karst. That is enough for Check.",
    ],
    glossary: [
      { term: "Periglacial", def: "Cold-climate processes at the ice margin, or in cold ground with no glacier." },
      { term: "Ice wedge", def: "A crack that fills and freezes, widening year on year." },
      { term: "Patterned ground", def: "Sorted stones in polygons or stripes from freeze–thaw heave." },
      { term: "Nivation", def: "Erosion under a lingering snow patch. A hollow, not a cirque on its own." },
      { term: "Blockfield", exam: "Felsenmeer", def: "A sheet of frost-shattered blocks on a plateau." },
      { term: "Active layer", def: "The top that thaws in summer over permafrost." },
      { term: "Permafrost", def: "Ground that stays frozen through the year. Not the same as a glacier." },
    ],
    misconception: { claim: "Every cold landform was carved by a glacier.", truth: "Freeze–thaw in the ground is a different factory. Look for wedges and polygons, not a U-trough." },
    misconceptions: [
      mc("Every cold landform was carved by a glacier.", "Freeze–thaw in the ground is a different factory. Look for wedges and polygons, not a U-trough."),
      mc("Ice wedges are tiny rivers.", "They are cracks that freeze. Water is a filler, not a channel."),
      mc("The Cairngorms have no periglacial story because the ice has gone.", "Relict forms remain. Alaska is the live pair."),
    ],
    cases: [{ slug: "cairngorms-albedo", label: "Cairngorm freeze–thaw" }, { slug: "yosemite", label: "Alaska / high-Sierra cold ground" }],
    teacher: {
      script:
        "A cold ground. No valley glacier on stage.\\nAsk whether freeze–thaw can build landforms without ice flowing. Wait.\\nRaise cycles. Ice wedges thicken. Polygons sort.\\nCairngorms relict. Alaska live.\\nA U-trough is the glacier lab. Do not steal it.\\nCaption: ice is in the ground, and it has thickness.\\nSpace, L, P. Then Check.",
      pitfalls: [
        "All cold = glacial.",
        "Ice wedges as rivers.",
        "Relict Cairngorms treated as empty of this story.",
      ],
    },
    sources: [{ label: "BGS periglacial" }, { label: "USGS / NSIDC permafrost" }],
    controls: {
      time: "none",
      extra: [{ key: "cycles", label: "Freeze–thaw", min: 0, max: 1, step: 0.02, default: 0.45 }],
    },
  }),
  lab({
    slug: "storm-surge",
    title: "Storm surge",
    hook: "The 1953 North Sea flood was wind piling water onto a shelf. Katrina’s surge was the same machine on the Gulf. It is not a tsunami.",
    objective: "Pile water with wind on a shallow shelf, and contrast that with a tsunami’s seafloor slip.",
    realm: "hazards",
    ages: ["GCSE", "NGSS MS", "HS Earth Sci", "APES"],
    curriculum: ["GCSE AQA 3.1.1.4", "NGSS MS-ESS3-2"],
    steps: steps("A shallow shelf. Wind toward the coast.", "Water piles. The surge.", "Tsunami lab is seafloor slip. Do not mix them."),
    questions: [
      q("A storm surge is…", ["A seafloor earthquake wave", "Wind-driven pile-up of water on a shallow shelf, plus low pressure", "A spring tide only", "A rain shadow"], 1, "Wind and shelf. Not slip."),
      q("A tsunami starts with…", ["Wind swell", "A sudden shift of the water column, often seafloor slip", "A till slump only", "A Chalk well"], 1, "Different lab. Different machine."),
      q("If I raise the wind slider toward the coast, the water should…", ["Flatten", "Pile higher on the shelf", "Freeze into an ice wedge", "Open an ocean"], 1, "Wind setup."),
      q("1953 eastern England and Katrina’s Gulf Coast pair because…", ["Both were tsunamis", "Both were wind and pressure piling water onto a shallow coast", "Both were Wilson collisions", "Both were rain shadows"], 1, "Same machine. Different ocean."),
    ],
    why: [
      "January 1953: a North Sea storm, a surge, Canvey and the Netherlands. August 2005: Katrina, a Gulf shelf, a surge into New Orleans. GCSE flooding and NGSS hazards mix surge and tsunami until a class calls every wall of water an earthquake. This lab is wind on a shelf. The tsunami lab is seafloor slip. If you cannot tell them apart, you will fail the ‘what to do’ question as well as the physics.",
      "Input is wind toward a shallow coast, and a low-pressure lift. Water is pushed and piled; the shelf makes a wall because it is shallow. Tide can add. What moves: the sea surface, piled against the land. What does not: the seafloor. What is conserved: the water — it came from the basin, piled here. The lie: one wind arrow, a rectangular shelf, no barrier islands. Real 1953 had a surge on a high tide. Real Katrina had levees and a bowl. This lab isolates wind setup. A tsunami is fast in deep water and stands up at the coast because the seafloor moved. Different starting sentence. Colour-blind safe: we do not encode ‘danger’ as red versus green only; the pile height is the readout.",
      "Point at the shelf. Wind toward the coast. Raise wind. Watch the pile. Keyboard: Space, L, R, P, wind slider. Say out loud: the floor did not slip. Send them to the tsunami lab for the other machine. Ask which one you can forecast from a weather map.",
      "Without the canvas: storm surge is wind and low pressure piling water on a shallow shelf. Tsunami is seafloor slip. 1953 North Sea; Katrina on the Gulf. Tides can add. The floor stays put in a surge. That is enough for Check, and enough to refuse ‘every flood is a tsunami’.",
    ],
    glossary: [
      { term: "Storm surge", def: "Wind-driven pile-up of water, plus low pressure, on a shallow coast." },
      { term: "Wind setup", def: "The slope of the sea surface forced by wind stress." },
      { term: "Inverse barometer", def: "Low pressure lets the sea surface rise a little. Wind usually does more." },
      { term: "Shelf", def: "Shallow seafloor beside a continent. It lets a surge stand up." },
      { term: "Tsunami", def: "A wave from a sudden water-column shift, often seafloor slip. A different lab." },
      { term: "Still-water flood", def: "The surge height before wind waves are added on top." },
      { term: "Barrier island", def: "A sandy shield. It can take the first pile, then fail. Outer Banks flavour." },
    ],
    misconception: { claim: "Every sudden coastal flood is a tsunami.", truth: "A surge is wind on a shelf. A tsunami is a moved seafloor. Forecasts and drills differ." },
    misconceptions: [
      mc("Every sudden coastal flood is a tsunami.", "A surge is wind on a shelf. A tsunami is a moved seafloor. Forecasts and drills differ."),
      mc("Surge is just big wind waves.", "Waves ride on top. The surge is the still-water pile."),
      mc("Deep water makes a bigger surge.", "A shallow shelf is what lets the pile stand up."),
    ],
    cases: [{ slug: "holderness", label: "North Sea 1953 / East coast" }, { slug: "katrina-sandy", label: "Katrina / Sandy surge" }],
    teacher: {
      script:
        "A shallow shelf. Wind toward the coast.\\nAsk what will happen to the water. Wait.\\nRaise wind. The surface piles. The floor did not slip.\\n1953 North Sea. Katrina on the Gulf.\\nTsunami is the other lab. Seafloor slip. Fast in deep water.\\nYou can see a surge coming on a weather map. Say that.\\nSpace, L, P. Then Check.",
      pitfalls: [
        "Surge = tsunami.",
        "Surge = wind waves only.",
        "Deep water as the amplifier.",
      ],
    },
    sources: [{ label: "Met Office / EA 1953" }, { label: "NOAA / NHC storm surge" }],
    controls: {
      time: "none",
      extra: [{ key: "wind", label: "Onshore wind", min: 0, max: 1, step: 0.02, default: 0.4 }],
    },
  }),
];
