import type { LabMeta } from "./types";
import { lab, q, steps } from "./make";

export const WATER_LABS: LabMeta[] = [
  lab({
    slug: "drainage-basin",
    title: "Drainage basin",
    hook: "Click the divide. Source, tributary, confluence, mouth — one budget with a rim.",
    objective: "Trace a watershed and name source, tributary, confluence, and mouth as stations on one basin, not four separate rivers.",
    realm: "water",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "GCSE rivers", "NGSS MS-ESS2-4"],
    steps: steps(
      "Toggle the basin overlay. The rim is the watershed — the drainage divide. Trace it before any names.",
      "Name the stations: source, tributary, confluence, mouth. Hide labels and point again.",
      "Rain on one side of the rim is this river; the other side is someone else’s. The basin is the hillside, not just the channel.",
    ),
    questions: [
      q("A watershed is…", ["The mouth", "The drainage divide", "The ocean", "A tide"], 1, "The rim. Not a garden shed."),
      q("A confluence is…", ["A waterfall", "Where tributaries meet", "A spit", "A front"], 1, "Join. Two channels, one thereafter."),
      q("The mouth is…", ["The source", "Where the river meets sea, lake, or a larger river", "Always a delta", "A cirque"], 1, "Exit. Tides and load decide whether a delta sits there."),
      q("The drainage basin includes…", ["Only the blue channel on the map", "The whole hillside that drains to this river, bounded by the divide", "The ocean store", "A water company office"], 1, "Channel plus slopes, soils and floodplain. The rim is the budget edge."),
    ],
    why: [
      "The Thames and the Mississippi are the same diagram at different size. A GCSE class that can name source, tributary, confluence and mouth on a Thames tributary tree can read the Mississippi without a new theory. The Severn and the Thames share a divide: rain on one side is this river, rain on the other is someone else’s. Colorado’s basin is the same rim at a drier number — dams and abstraction sit inside a watershed, they do not redraw it. Flood warnings, water-company licences, and a school fieldwork sheet all start with one question: which hillside drains here? The basin is the collecting surface, not the blue line on the OS sheet. US counties and UK Environment Agency catchments are administrative names laid on this physical machine. Holderness is a different coast; this lab is the inland bowl that feeds a river to a mouth.",
      "A drainage basin is the area of land drained by a river and its tributaries, bounded by a watershed — the drainage divide. Precipitation that falls inside the rim becomes this river’s budget; the other side belongs to a neighbour. Source is where channelised flow begins, often a spring or a gathering of rills. A tributary is a joining stream. A confluence is where they meet. The mouth is where the river exits to sea, lake, or a larger river, and it is not always a delta. The channel is only the drain. Hillsides, soils, floodplain and channel together are the basin. Overlay on: the rim lights as a line you can trace. Overlay off: you still have to point at it on the hill. Vertical exaggeration is labelled ×8 so the bowl reads from the back of the room; a real Thames divide can be a low ridge or a field boundary, not a crater rim. Size is not type. Stations stay the same from a Lake District beck to the Mississippi. Rain on one side of the rim is this river. Rain on the other is someone else’s. Do not confuse the watershed with a building. Do not teach the blue OS line as the whole catchment.",
      "Toggle Basin overlay on. Trace the rim before any station names. Hide labels with L and ask the class to point: source, tributary, confluence, mouth. Toggle the overlay off and make them find the divide on the hill alone. Orbit the bowl; it is a 3D catchment, not a 2D paint fill. Step the camera from source hill to mouth so each station fills the frame. The green rim is the overlay, not a painted county. Keyboard: L labels, R reset. No year slider — this is a static machine. Finish in Check.",
      "Without the 3D view: a rim, a source, tributaries joining at a confluence, a mouth. Rain inside the rim is this river; rain outside is another. The basin is the hillside that drains here, not just the channel. Thames and Mississippi are the same stations at different kilometres. A watershed is a divide, not a garden shed. Vertical exaggeration is a teaching lie; the real divide can be a hedge. Overlay on or off, the divide is still the budget edge. Dams on the Colorado sit inside the rim. Mouth is the exit — estuary or delta as the coast allows.",
    ],
    glossary: [
      { term: "Watershed", exam: "Drainage divide", def: "The rim of a drainage basin. Rain inside is this river; rain outside is another." },
      { term: "Drainage basin", exam: "Catchment", def: "The area of land drained by a river and its tributaries, bounded by the watershed." },
      { term: "Source", def: "Where channelised flow begins — a spring, a gathering of rills, or a lake outlet." },
      { term: "Tributary", def: "A stream that joins a larger channel." },
      { term: "Confluence", def: "The meeting of two streams." },
      { term: "Mouth", def: "Where the river exits to sea, lake, or a larger river. Not always a delta." },
      { term: "Interfluve", def: "The higher ground between neighbouring channels, inside the basin." },
    ],
    misconception: { claim: "The basin is just the channel.", truth: "It is the whole hillside that drains here." },
    misconceptions: [
      { claim: "The basin is just the channel.", truth: "It is the whole hillside that drains here." },
      { claim: "A watershed is a building that stores water.", truth: "Watershed means drainage divide — the rim. Say the word as a divide." },
      { claim: "The mouth is always a delta.", truth: "The mouth is the exit. Tides and waves can steal the load; many UK rivers end in estuaries." },
    ],
    cases: [{ slug: "thames", label: "Thames / Severn" }, { slug: "mississippi", label: "Mississippi" }],
    teacher: {
      script:
        "Toggle Basin overlay on. Trace the rim. That rim is the watershed, the drainage divide.\nIt is not a garden shed. Say the word as a divide.\nHide the labels. Name source, tributary, confluence, mouth.\nThe basin is not just the channel. It is the whole hillside that drains here.\nRain on one side is this river. The other side is someone else’s.\nA confluence is where tributaries meet. The mouth is the exit, not always a delta.\nThames and Mississippi are the same diagram at different size. Colorado is the same rim, drier numbers.\nHide the overlay once and ask the class to point at the divide. Then put it back.\nOrbit so the bowl reads as a catchment, not a paint fill. Exaggeration is ×8; say so.\nFinish in Check.",
      pitfalls: [
        "Confusing watershed with water-shed as in shed building.",
        "Teaching the basin as only the blue channel on the map.",
        "Calling every mouth a delta.",
      ],
    },
    sources: [{ label: "UKCEH" }, { label: "USGS" }],
    controls: { time: "none", toggles: [{ key: "overlay", label: "Basin overlay", defaultOn: true }] },
  }),
  lab({
    slug: "hydrograph",
    title: "Storm hydrograph",
    hook: "Rain is the input. The river’s reply has a rising limb, a peak, a lag, a falling limb.",
    objective: "Read rising limb, peak, lag and falling limb, and toggle urban versus rural to change the shape.",
    realm: "water",
    ages: ["GCSE", "A-level", "NGSS MS", "APES"],
    curriculum: ["GCSE", "A-level hydrology", "APES"],
    steps: steps(
      "Play the storm. Rain falls, then the river replies: rising limb, peak, lag, falling limb.",
      "Raise Urban cover. The hydrograph gets flashier: shorter lag, higher peak. Drop it toward rural: fatter, later.",
      "Lag is rain peak to discharge peak. The hill has to drain. Stage is height; discharge is volume per time.",
    ),
    questions: [
      q("Lag time is…", ["Peak rainfall to peak discharge", "Sunrise", "Tide", "A year"], 0, "Hours after rain. The hill has to drain."),
      q("Urban land use typically…", ["Lengthens lag", "Shortens lag and raises peak", "Stops rain", "Creates glaciers"], 1, "Impermeable surfaces. Water cannot wait in the soil."),
      q("A falling limb is…", ["The start of rain", "Discharge declining after the peak", "A cliff", "Wind"], 1, "Somerset can sit here for weeks."),
      q("Stage and discharge are…", ["The same number with two names", "Height of the water surface versus volume of water per time — do not mix them", "Rain and snow", "Lag and peak"], 1, "A high stage in a narrow channel is not the same discharge as that height in a wide one."),
    ],
    why: [
      "Somerset Levels can sit on a falling limb for weeks after the rain has stopped. A paved UK high street and a US urban drain flash in hours. Same storm-hydrograph machine, different numbers. Lag time is why a village floods after the radar looks quiet, and why a city gully roars while the cloud is still overhead. Land use is a control, not a personality: impermeable roofs shorten lag and raise the peak; vegetated soil lengthens lag and fattens the falling limb. Environment Agency flood warnings and USGS stream gauges both plot this graph. The Levels are peat, clay and tide-lock; Katrina-Sandy urban flooding is a different surface on the same axes. Do not mix the two as one story. The graph is the reply of a catchment to a pulse of rain.",
      "A storm hydrograph plots discharge against time after rainfall. Rain is the input. The river’s reply has four named parts: a rising limb as the catchment starts to contribute, a peak, a lag from rainfall peak to discharge peak, and a falling limb as the hill empties. The river does not peak when the rain peaks. The hillside, soil and channel have to drain. Urban cover raises the fraction of impermeable surface: water cannot wait in the soil, so lag shortens and the peak rises — a flashier graph. Rural cover does the opposite: fatter, later. Baseflow is the slow groundwater contribution under the storm pulse. Stage is height of the water surface; discharge is volume per time. Do not mix them. A high stage in a narrow urban drain is not the same discharge as that height on the Parrett. Somerset’s almost-flat long profile and saturated peat stretch the falling limb. A flashy urban drain does not. Throughflow and overland flow are the hill’s pipes; impermeable cover skips the slow ones. This lab holds storm size still so land use is the knob you turn. This lab is hours, not the year — that is the regime lab.",
      "Play the storm (space). Watch rain fall, then the river’s reply on the graph: rising limb, peak, lag, falling limb. Raise Urban cover toward 1 and run it again: shorter lag, higher peak, roofs instead of trees. Drop Urban cover toward rural and compare. Freeze on the peak and read the lag tag in hours. There is no labelled time slider — space still plays the pulse, arrows still scrub it. Name the four parts out loud before you leave the graph. Keyboard: space play, arrows scrub the storm, L labels, R reset. Urban cover lives in the bar. Finish in Check.",
      "Without the 3D view: rain is the input; the river replies after a lag. Rising limb, peak, falling limb. Urban surfaces shorten lag and raise the peak. Rural catchments are fatter and later. Stage is height; discharge is volume per time. Somerset can sit on a falling limb for weeks. A hydrograph is hours. A regime graph is the year. Impermeable roofs skip the soil store. Baseflow sits under the pulse. The hill is a schematic catchment, not a traced Parrett.",
    ],
    glossary: [
      { term: "Hydrograph", def: "Discharge plotted against time after rain. A storm hydrograph is hours; a regime graph is the year." },
      { term: "Lag time", def: "Time from peak rainfall to peak discharge. The hill has to drain." },
      { term: "Rising limb", def: "The increase in discharge as the catchment starts to contribute." },
      { term: "Peak discharge", def: "The highest discharge in the storm reply." },
      { term: "Falling limb", def: "Discharge declining after the peak as the catchment empties." },
      { term: "Baseflow", def: "Slow groundwater contribution under the storm pulse." },
      { term: "Stage", def: "Height of the water surface. Not the same as discharge." },
      { term: "Discharge", exam: "Q", def: "Volume of water per time passing a point. Cubic metres per second in school units." },
    ],
    misconception: { claim: "The river peaks when the rain peaks.", truth: "Lag. The hill has to drain." },
    misconceptions: [
      { claim: "The river peaks when the rain peaks.", truth: "Lag. The hill has to drain." },
      { claim: "Stage and discharge are the same thing.", truth: "Stage is height. Discharge is volume per time. A narrow drain and a wide floodplain disagree." },
      { claim: "Urban land use stops flooding by putting water in pipes.", truth: "Pipes and roofs shorten lag and raise the peak. The water still has to go somewhere." },
    ],
    cases: [{ slug: "somerset-levels", label: "Somerset Levels" }, { slug: "shanghai-huangpu", label: "Shanghai / Huangpu" }],
    teacher: {
      script:
        "Watch the storm input. Then the river’s reply: rising limb, peak, lag, falling limb.\nLag time is rain peak to discharge peak. The hill has to drain.\nThe river does not peak when the rain peaks. That is the misconception.\nRaise Urban cover. The hydrograph gets flashier: shorter lag, higher peak.\nImpermeable surfaces. Water cannot wait in the soil.\nDrop Urban cover toward rural. Fatter, later.\nDo not mix stage and discharge. Stage is height. Discharge is volume per time.\nSomerset Levels can sit on a falling limb for weeks. A flashy urban drain does not.\nName rising, peak, lag, falling out loud before you leave the graph.\nFinish in Check.",
      pitfalls: [
        "Mixing stage and discharge.",
        "Teaching the river as peaking with the rain.",
        "Calling every flood a flash flood — Somerset’s falling limb can last weeks.",
      ],
    },
    sources: [{ label: "UKCEH" }, { label: "USGS NWIS" }],
    controls: {
      time: "none",
      extra: [
        { key: "urban", label: "Urban cover", min: 0, max: 1, step: 0.05, default: 0.2 },
        { key: "rain", label: "Rain", min: 0.2, max: 1.6, step: 0.05, default: 1 },
      ],
    },
  }),
  lab({
    slug: "river-hydrology",
    title: "River regime",
    hook: "A UK upland nival/pluvial mix vs the Mississippi: the same year, different graphs.",
    objective: "Compare two annual regimes and say what rain, snowmelt and dams do to the year’s personality.",
    realm: "water",
    ages: ["A-level", "GCSE", "APES"],
    curriculum: ["A-level", "GCSE"],
    steps: steps(
      "Play the year. Two traces: a UK upland and the Mississippi. Name the bump.",
      "UK upland: rain plus a snowmelt bump, nival and pluvial mixed. Mississippi: a broader continental year, managed by dams.",
      "Regime is the year’s personality, not one storm. Hydrograph is hours; this is the year.",
    ),
    questions: [
      q("A nival regime is driven by…", ["Tides", "Snowmelt", "Hurricanes only", "Albedo in space"], 1, "Spring peak. UK highland snow, Colorado snowpack, Alpine melt."),
      q("A pluvial regime follows…", ["Rainfall seasonality", "Only earthquakes", "The Moon’s nodes", "Hotspots"], 0, "UK west is often pluvial. The Mississippi year is a broader continental mix."),
      q("The Mississippi’s year is…", ["A Lake District beck", "A continental drain with snowmelt and rain, managed by dams", "A karst spring only", "A geyser"], 1, "Do not invent numbers."),
      q("A storm hydrograph and a regime graph differ because…", ["They are the same plot", "One is hours after a rain pulse; the other is the typical year", "One is wind", "One is a tide gauge"], 1, "Do not paste a storm limb onto a monthly axis and call it a regime."),
    ],
    why: [
      "A Lake District beck and the Mississippi are the same year on different graphs. UK upland catchments often mix winter rain with a spring snowmelt bump; the west coast is frequently pluvial. The Mississippi is a continental drain with snowmelt, rain and a dam-managed year — do not invent cubic metres. Colorado’s snowpack is a nival store that becomes spring discharge; dams then flatten what the mountain wrote. Regime is why a reservoir rule-curve and a UK abstraction licence care about the month, not the Thursday storm. Hydrograph is hours. This lab is the year. All rivers do not peak in summer. Alps, Rockies and a Cumbrian winter disagree with a tropical wet season, and that is the point of two traces on one axis.",
      "Regime is the typical annual variation of discharge — the year’s personality, not one storm. A nival regime is snowmelt-dominated: a spring peak as the pack goes. A pluvial regime follows rainfall seasonality: UK western winters often sit here. Many UK upland rivers are a mix: rain in the wings, a snowmelt bump in spring. The Mississippi trace in this lab is a broader continental year, rain-fed with a snowmelt contribution and flattened in the real world by dams. Play the year and watch two ribbons: UK highland nival-green, Mississippi pluvial-blue. A marker walks the month. A snow sphere lights on the UK trace in spring. All rivers do not peak in summer. It depends on rain, snow, ice and management. A glacier-fed river can peak later still. Colorado’s pack is the same nival idea at drier numbers; dams then rewrite the month. Do not paste a storm hydrograph onto a monthly axis. Hours and months are different machines. One graph is not all climates. The traces are school shapes, not NRFA or USGS station numbers — do not invent a peak flow and write it in an exam.",
      "Play the year. Two traces: nival UK highland and Mississippi pluvial. Pause on the UK spring bump and name it snowmelt. Scrub the Year slider month by month and ask which trace would change if you turned snow off in the story. Hide labels (L) and make the class assign nival versus pluvial. Watch the marker walk J to D; a snow sphere lights on the UK ribbon in spring. Keyboard: space play, arrows scrub the year, L labels, R reset. Speed 1× / 2× / 4× is in the bar. Finish in Check.",
      "Without the 3D view: two annual traces. UK upland: rain plus a snowmelt bump. Mississippi: a broader continental year, managed by dams in the real river. Nival is snowmelt. Pluvial follows rain. Regime is the year; a storm hydrograph is hours. All rivers do not peak in summer. Colorado’s snowpack is a nival store that dams can flatten. The ribbons are school shapes, not station numbers. Do not invent cubic metres. One graph is not all climates. Say so plainly.",
    ],
    glossary: [
      { term: "Regime", def: "Typical annual variation of discharge. The year’s personality, not one storm." },
      { term: "Nival", def: "Snowmelt-dominated regime. Spring peak as the pack goes." },
      { term: "Pluvial", def: "Rainfall-seasonality regime. UK west is often pluvial." },
      { term: "Snowmelt", def: "Stored winter snow becoming spring discharge. A nival bump." },
      { term: "Discharge", exam: "Q", def: "Volume per time. Regime plots it by month, not by hour." },
      { term: "Baseflow", def: "The slow groundwater contribution that sits under the year’s wiggles." },
      { term: "Dam regulation", def: "Storage that flattens or shifts the natural year. Mississippi and Colorado both live with it." },
    ],
    misconception: { claim: "All rivers peak in summer.", truth: "Depends on rain, snow, dams, ice." },
    misconceptions: [
      { claim: "All rivers peak in summer.", truth: "Depends on rain, snow, dams, ice." },
      { claim: "A storm hydrograph and a regime graph are the same plot.", truth: "Hours versus the year. Do not paste a rising limb onto a monthly axis." },
      { claim: "One graph will do for all climates.", truth: "UK upland mix, Mississippi continental year, Colorado snowpack: different machines, same idea." },
    ],
    cases: [{ slug: "lake-district", label: "UK upland" }, { slug: "mississippi", label: "Mississippi" }],
    teacher: {
      script:
        "Play the year. Two traces: a UK upland and the Mississippi.\nName the bump. UK upland: rain plus a snowmelt bump, nival and pluvial mixed.\nA nival regime is snowmelt. A pluvial regime follows rainfall seasonality.\nThe Mississippi is a continental drain with snowmelt and rain, managed by dams. Do not invent numbers.\nRegime is the year’s personality, not one storm. Hydrograph is hours; this is the year.\nAll rivers do not peak in summer. That is the misconception.\nIt depends on rain, snow, dams, ice. Colorado’s pack is a nival store; dams then flatten.\nOne graph is not all climates. Say so.\nAsk which trace would change if you turned snow off in the story.\nFinish in Check.",
      pitfalls: [
        "One graph for all climates.",
        "Pasting a storm hydrograph onto a monthly axis.",
        "Inventing peak-flow numbers the traces do not give.",
      ],
    },
    sources: [{ label: "NRFA" }, { label: "USGS" }],
    controls: { time: "year" },
  }),
  lab({
    slug: "ocean-currents",
    title: "Ocean currents",
    hook: "Gyres are the loops. The Gulf Stream is a warm ribbon the UK notices in the air, not as a miracle heater of every garden.",
    objective: "See surface gyres and a Gulf Stream ribbon, and keep UK winter language honest: one term in a budget, not a magic radiator.",
    realm: "water",
    ages: ["GCSE", "A-level", "NGSS MS", "APES"],
    curriculum: ["GCSE", "A-level", "APES 4.5"],
    steps: steps(
      "Orbit the globe. Five gyres are the loops. Subtropical highs help.",
      "Point at the Gulf Stream ribbon: a warm western-boundary current of the North Atlantic.",
      "UK mild winters are a mix of latitude, westerlies, and ocean heat. Do not overclaim. Florida and Holderness sit on the same ocean, different coasts.",
    ),
    questions: [
      q("A gyre is…", ["A waterfall", "A large looping surface current system", "A fault", "A dune"], 1, "Subtropical highs help. Five big subtropical loops on a school globe."),
      q("The Gulf Stream is…", ["A cold coastal current off Peru", "A warm western-boundary current of the North Atlantic", "A river in Ohio", "Wind only"], 1, "Ribbon. Narrow, fast, warm on the western side of the gyre."),
      q("UK mild winters are…", ["100% Gulf Stream and nothing else", "A mix of latitude, westerlies, and ocean heat — do not overclaim", "Caused by deserts", "Caused by Yellowstone"], 1, "Honest language. One term in a budget."),
      q("A western-boundary current is typically…", ["Broad, slow and cold", "Narrow, fast and warm on the western side of a subtropical gyre", "A river mouth", "A tide"], 1, "Gulf Stream, Kuroshio. The eastern side of the same gyre is broader and cooler — Canary in the North Atlantic."),
    ],
    why: [
      "Florida and Holderness sit on the same ocean, different coasts. Miami feels a warm western-boundary ribbon; a Holderness till cliff feels North Sea weather on the other side of the gyre. UK mild winters are a mix of latitude, westerlies and ocean heat — the Gulf Stream helps, it does not magically heat every British garden. A GCSE class that treats the ribbon as a radiator will misread both a January frost in Leeds and a hurricane season off Florida. Surface gyres move heat, salt and floating debris; they are not a personality of the sea. News maps that colour the Atlantic red and call it a heater skip the rest of the budget: the westerlies, the latitude, the heat already in the basin. Honest language is the skill. Same ocean, different coast, one physical machine.",
      "A gyre is a large looping surface current system. Five subtropical gyres sit under subtropical highs on a school globe: North Atlantic, South Atlantic, North Pacific, South Pacific, Indian. Wind stress and the Earth’s rotation pile water; western-boundary currents then run narrow, fast and warm — Gulf Stream, Kuroshio. Eastern-boundary currents on the same loop are broader and cooler — Canary in the North Atlantic. The Gulf Stream is a warm western-boundary current of the North Atlantic, drawn here as a ribbon from the Florida Strait toward north-west Europe. Colour in this lab is a temperature story, not a paint chart. UK mild winters are latitude, westerlies and ocean heat together. The ribbon is one term in that budget, not the reason Britain has weather at all. It is not a miracle heater of every garden. Florida and Holderness share the basin and disagree at the beach. This is a surface schematic, not a GCM, not the deep conveyor — that is the thermohaline lab. Particles on the ribbon are tracers, not a census of every eddy. The globe is true-ish shape; current tubes are fat so they read from the back row.",
      "Orbit the globe. Name the North Atlantic loop before the ribbon. Point at the Gulf Stream, then the UK, then Florida, then Holderness. Hide labels (L) and ask which coast sits on the warm western boundary. Step the camera if the set has wandered. Particles on the ribbon are tracers so the loop reads; they are not a forecast. Keyboard: L labels, R reset. No year slider — gyres are the standing machine. Honest language, then sit down. Finish in Check.",
      "Without the 3D view: five gyres as loops; the Gulf Stream as a warm western-boundary ribbon. UK mild winters are latitude, westerlies and ocean heat. The ribbon helps; it is not a magic radiator. Florida and Holderness sit on the same ocean, different coasts. Western-boundary currents are narrow and fast; eastern-boundary currents are broader and cooler. This is a surface schematic, not the deep conveyor and not a climate model. Colour is a temperature story. The tubes are fat on purpose so the set reads.",
    ],
    glossary: [
      { term: "Gyre", def: "A basin-scale looping surface current system. Five subtropical gyres on a school globe." },
      { term: "Western boundary current", def: "Narrow, fast, warm current on the western side of a subtropical gyre — Gulf Stream, Kuroshio." },
      { term: "Eastern boundary current", def: "Broader, cooler return on the eastern side of the same gyre — Canary in the North Atlantic." },
      { term: "Gulf Stream", def: "Warm western-boundary current of the North Atlantic. A ribbon, not a miracle heater." },
      { term: "Canary Current", def: "Cooler eastern-boundary current of the North Atlantic gyre." },
      { term: "Subtropical high", def: "The high-pressure cell that helps organise a subtropical gyre." },
      { term: "Surface current", def: "Wind-driven flow in the upper ocean. Not the deep density conveyor." },
    ],
    misconception: { claim: "The Gulf Stream is why Britain has weather at all.", truth: "It is one term in a budget." },
    misconceptions: [
      { claim: "The Gulf Stream is why Britain has weather at all.", truth: "It is one term in a budget." },
      { claim: "The Gulf Stream is a magic radiator for every British garden.", truth: "Latitude, westerlies and ocean heat share the work. The ribbon helps; it does not run the seasons." },
      { claim: "All ocean currents are the deep conveyor.", truth: "These are surface gyres. The density-driven loop is a different lab." },
    ],
    cases: [{ slug: "holderness", label: "North Sea / UK" }, { slug: "florida-insolation", label: "Florida current" }],
    teacher: {
      script:
        "Orbit the globe. Five gyres are the loops.\nA gyre is a large looping surface current system. Subtropical highs help.\nPoint at the Gulf Stream ribbon: a warm western-boundary current of the North Atlantic.\nUK mild winters are a mix of latitude, westerlies, and ocean heat. Do not overclaim.\nThe Gulf Stream is not why Britain has weather at all. It is one term in a budget.\nThat is the misconception. Not a magic radiator.\nFlorida and Holderness sit on the same ocean, different coasts.\nThe ribbon matters. It is not the only reason we are not tundra.\nHonest language, then sit down.\nFinish in Check.",
      pitfalls: [
        "Gulf Stream as a magic radiator.",
        "Treating surface gyres as the deep conveyor.",
        "Overclaiming UK winter as 100% Gulf Stream.",
      ],
    },
    sources: [{ label: "NOAA ocean" }, { label: "Met Office" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "thermohaline",
    title: "Thermohaline conveyor",
    hook: "Density is colour. Cold salty water sinks. The conveyor is slow and global.",
    objective: "Follow the school conveyor, read density as colour, and flag that this is a schematic — not a pipe you can visit, not a Tuesday switch.",
    realm: "water",
    ages: ["A-level", "APES", "HS Earth Sci"],
    curriculum: ["A-level", "APES", "NGSS HS-ESS2"],
    steps: steps(
      "Read density as colour. Blue-dark: cold dense. Red-warm: light. Swatches sit on the floor.",
      "Play the loop: surface, NADW sink, deep return, Indo-Pacific upwell.",
      "School conveyor — not a pipe you can visit. Centuries, not a day. Headlines are not a lab.",
    ),
    questions: [
      q("Thermohaline means…", ["Wind only", "Temperature and salinity control density", "Tides only", "Ice albedo only"], 1, "Both. Heat and salt. Density decides who sinks."),
      q("Deep water forms in…", ["The equatorial shallows only", "Cold, often salty high-latitude seas", "The Sahara", "Lake District tarns"], 1, "North Atlantic / Southern Ocean story. Iceland sits near a famous sink region in the school map."),
      q("The conveyor is…", ["A 2-minute current", "A slow global density circulation — simplified here", "A river", "A hurricane"], 1, "Flag the simplification. Centuries, not a day."),
      q("Freshwater input at high latitude…", ["Always switches the conveyor off next Tuesday", "Can change density and therefore sinking; it is a caution, not a countdown", "Turns the Gulf Stream into a river", "Creates a gyre from nothing"], 1, "Mississippi-scale freshwater is a caution in the school story, not cinema."),
    ],
    why: [
      "Iceland sits near a famous sink region in the school story of North Atlantic Deep Water. Cold, often salty water can become dense enough to dive; that dive is one engine of a slow global loop. A UK A-level class that treats the conveyor as a pipe under the Atlantic will misread both a Met Office ocean brief and a US east-coast headline. Mississippi-scale freshwater at high latitude is a density caution, not a countdown clock. Holderness waves and the Gulf Stream ribbon are surface machines; this lab is density in the deep. The timescale is centuries, not a day. Nuclear-test tracers and ocean arrays read this loop; a classroom globe cannot. The skill is to follow the school conveyor, name temperature and salinity as the density pair, and refuse cinema that switches it off next Tuesday.",
      "Thermohaline means temperature and salinity control density. Cold water is denser; salty water is denser; the combination can sink. Deep water forms in cold, often salty high-latitude seas — North Atlantic and Southern Ocean in the school map — not in equatorial shallows. Iceland sits near a famous North Atlantic sink region. Play the loop: warm, lighter water at the surface, a dive where it is cold-saline, a deep return, then upwelling in the Indo-Pacific story. Colour is density: darker cold-saline, warmer light. Swatches on the floor are the key: warm/light versus cold-saline. NADW is the school name for the North Atlantic dive. This is a school conveyor, not a pipe you can visit, not a single ribbon in the real ocean, not the AMOC in a research paper. Flag the simplification out loud. It can change. That is not the same sentence as cinema. Freshwater input — a big river, ice melt — can lower density and argue with sinking. Mississippi as a freshwater caution belongs here as a mechanism, not a prophecy. Gyres are wind-driven surface loops; this is the density machine underneath, slower by orders of magnitude. Centuries, not a day.",
      "Read the swatches first: warm/light versus cold-saline. Then play the loop. Point at the NADW sink, the deep return, the Indo-Pacific upwell. Hide labels (L) and ask which limb is sinking. Orbit so the globe and the schematic tubes both read. A dark sphere marks the North Atlantic dive near Iceland’s story. Keyboard: space play, L labels, R reset. Particles are tracers on a cartoon, centuries sped into a lesson. Flag the schematic out loud before you leave. Finish in Check.",
      "Without the 3D view: cold salty water sinks; warm light water stays up. Temperature and salinity set density. Deep water forms in high-latitude seas, not on the equator. Iceland sits near a famous sink in the school story. The conveyor is a slow global schematic — centuries, not a day, not a pipe, not a Tuesday switch. Freshwater can change density; that is a caution, not a countdown. Gyres are a different lab. Colour is density, not a travel poster.",
    ],
    glossary: [
      { term: "Thermohaline", def: "Density-driven ocean circulation from heat (thermo) and salt (haline)." },
      { term: "Density", def: "Mass per volume. Cold and salty both raise seawater density." },
      { term: "NADW", exam: "North Atlantic Deep Water", def: "Cold, often salty water that can sink in the North Atlantic school story." },
      { term: "Deep water formation", def: "Sinking where the surface becomes dense enough. High-latitude seas, not equatorial shallows." },
      { term: "Upwelling", def: "Return of deeper water toward the surface. Indo-Pacific in this schematic." },
      { term: "Conveyor", def: "School cartoon of a global density loop. Not a pipe. Not a GCM." },
      { term: "Salinity", def: "Salt content. More salt, higher density, all else equal." },
    ],
    misconception: { claim: "It will switch off next Tuesday.", truth: "It can change; headlines are not a lab." },
    misconceptions: [
      { claim: "It will switch off next Tuesday.", truth: "It can change; headlines are not a lab." },
      { claim: "The conveyor is a pipe you could visit in a submarine.", truth: "It is a school cartoon of a slow, messy, global density circulation. Flag the simplification." },
      { claim: "Deep water forms in the warm equatorial shallows because the Sun is strongest there.", truth: "Sinking wants density. Cold, often salty high-latitude seas, not the equator." },
    ],
    cases: [{ slug: "iceland", label: "North Atlantic" }, { slug: "mississippi", label: "Freshwater input caution" }],
    teacher: {
      script:
        "Read density as colour. Dark: cold dense. Warm: light.\nThermohaline means temperature and salinity control density.\nPlay the loop: surface, sink, deep return, upwell.\nDeep water forms in cold, often salty high-latitude seas, not in equatorial shallows.\nIceland sits near a famous sink region in the school story.\nThis is a school conveyor, not a pipe you can visit. Flag the simplification.\nIt will not switch off next Tuesday. Headlines are not a lab.\nIt can change. That is not the same sentence as cinema.\nFreshwater input is a caution, not a countdown. Mississippi belongs here as density, not prophecy.\nFinish in Check.",
      pitfalls: [
        "Day-after-tomorrow cinema as fact.",
        "Teaching the conveyor as a pipe under the Atlantic.",
        "Putting deep-water formation on the equator because the Sun is ‘stronger’ there.",
      ],
    },
    sources: [{ label: "NOAA AMOC" }, { label: "UK Met Office ocean" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "carbon-cycle",
    title: "Carbon cycle",
    hook: "Fast stores and slow stores. The fossil-fuel tap is a human transfer from slow to fast.",
    objective: "Name stores, watch arrows, and open a fossil-fuel tap as a transfer from a slow geologic store into the fast cycle.",
    realm: "water",
    ages: ["GCSE", "A-level", "NGSS MS", "APES"],
    curriculum: ["GCSE", "A-level carbon", "APES 1.4 / 4.6"],
    steps: steps(
      "Name the stores: atmosphere, biosphere, ocean, rock, fossil. Then the arrows.",
      "Photosynthesis, respiration, dissolution, weathering. Fast thin arrows; slow rock arrows.",
      "Open the Fossil-fuel tap. Atmosphere store grows. Slow store falls. The tap moves carbon; it does not invent atoms.",
    ),
    questions: [
      q("Fossil fuels are…", ["A fast plant store", "A slow geologic store we tap into the fast cycle", "Oxygen", "Albedo"], 1, "The tap. Atoms already in the rock."),
      q("The ocean store…", ["Does not talk to the air", "Exchanges carbon with the atmosphere", "Is only plastic", "Is granite"], 1, "Both ways. Dissolution and return."),
      q("Weathering is a…", ["Fast daily flux always", "Slow transfer toward rock/ocean stores", "Hurricane", "Tide"], 1, "A-level slow cycle."),
      q("Burning fuel…", ["Creates new carbon atoms", "Moves carbon from a slow geologic store into the atmosphere", "Destroys the ocean store", "Stops photosynthesis"], 1, "Conservation of atoms. The tap is a transfer, not a factory."),
    ],
    why: [
      "A-level water and carbon is one pair of diagrams: stores, fluxes, a budget. Thames-side power and heating are a fossil tap on the slow store; a US Dust Bowl land-use story is carbon in soil and vegetation, still the same boxes. The atmosphere store is the small, fast box that people breathe and plants use; rock and fossil are huge and slow. Opening the tap grows the air box and shrinks the slow box. That is why a school carbon diagram and a NOAA flask record are the same machine at different honesty. Do not preach a policy. Stay on the physical transfer. The ocean talks to the air both ways. Weathering is slow. Photosynthesis and respiration are fast. A UK GCSE class that thinks burning creates new carbon atoms will misread every later climate sentence. The atoms were already in the rock.",
      "Carbon sits in stores: atmosphere, biosphere, ocean, sediment and rock, fossil fuel. A flux is a transfer between stores. Fast cycle: photosynthesis pulls carbon into the biosphere; respiration and decay send it back; the ocean exchanges with the air both ways. Slow cycle: weathering, burial, rock. Fossil fuel is a slow geologic store. The Fossil-fuel tap in this lab is a human flux from that slow box into the atmosphere — a thick arrow, not a new element. Open the tap: the atmosphere sphere grows; the fossil box shrinks. Burning does not create carbon atoms; it moves them. Weathering is not a daily flux. Do not serve an arrow salad with no named stores. Box sizes here are teaching volumes, not IPCC petagrams — do not invent a number and write it as fact. The water cycle lab is mass conserved in H2O; this lab is mass conserved in C. Pair them. Land-use change is another flux on the same diagram, still a transfer, still not a sermon. Stay on the boxes and the arrows. The thick orange arrow is the tap. Fast arrows stay thin.",
      "Name stores first, out loud: atmosphere, biosphere, ocean, rock, fossil. Then chase one fast arrow and one slow arrow. Open the Fossil-fuel tap and watch the air box grow as the slow box falls. Hide labels (L) and ask which box is the tap’s source. Scrub the slider back to low so the class sees the reverse. Keyboard: L labels, R reset. The slider lives in the bar. Particles on the thick arrow are the anthropogenic flux, not a new element. Finish in Check.",
      "Without the 3D view: five stores — atmosphere, biosphere, ocean, rock, fossil. Fluxes between them. Fast: photosynthesis and respiration. Slow: weathering and burial. The fossil tap moves carbon from a slow geologic store into the air; it does not invent atoms. The ocean exchanges with the atmosphere both ways. Box sizes are teaching, not a litre census. Stay on the physical machine. Land-use change is another flux on the same diagram, still a transfer, still not a sermon. The tap is a transfer.",
    ],
    glossary: [
      { term: "Store", exam: "Reservoir", def: "A place carbon sits: atmosphere, biosphere, ocean, rock, fossil." },
      { term: "Flux", def: "A transfer between stores." },
      { term: "Photosynthesis", def: "Fast flux from atmosphere into the biosphere." },
      { term: "Respiration", def: "Fast flux from biosphere back to the atmosphere." },
      { term: "Weathering", def: "Slow transfer toward rock and ocean stores. Not a daily flux." },
      { term: "Fossil fuel", def: "A slow geologic store of carbon. The tap moves it into the fast cycle." },
      { term: "Fast cycle", def: "Atmosphere–biosphere–ocean exchanges on human timescales." },
      { term: "Slow cycle", def: "Rock, burial, weathering. Geologic time unless we tap it." },
    ],
    misconception: { claim: "Burning fuel creates new carbon atoms.", truth: "It moves them from a slow store to the air." },
    misconceptions: [
      { claim: "Burning fuel creates new carbon atoms.", truth: "It moves them from a slow store to the air." },
      { claim: "The ocean store does not talk to the air.", truth: "It exchanges carbon with the atmosphere both ways." },
      { claim: "Weathering is a fast daily flux like respiration.", truth: "Weathering is slow. Fast and slow are different arrows on the same diagram." },
    ],
    cases: [{ slug: "thames", label: "UK energy / stores" }, { slug: "dust-bowl", label: "Land-use carbon" }],
    teacher: {
      script:
        "Name the stores: atmosphere, biosphere, ocean, rock, fossil.\nThen the arrows: photosynthesis, respiration, dissolution, weathering.\nA store is a reservoir. A flux is a transfer. Do not serve an arrow salad.\nOpen the Fossil-fuel tap. The atmosphere store grows. The slow store falls.\nFossil fuels are a slow geologic store we tap into the fast cycle.\nBurning fuel does not create new carbon atoms. It moves them from a slow store to the air.\nThat is the misconception. Stay on the physical transfer.\nWeathering is a slow transfer toward rock and ocean stores, not a daily flux.\nThe ocean exchanges carbon with the atmosphere both ways.\nFinish in Check.",
      pitfalls: [
        "One arrow salad with no named stores.",
        "Teaching burning as creating new carbon atoms.",
        "Inventing petagram numbers the boxes do not give.",
      ],
    },
    sources: [{ label: "NOAA carbon" }, { label: "IPCC FAQ as school context — no invented stats" }],
    controls: { time: "none", extra: [{ key: "fossil", label: "Fossil-fuel tap", min: 0, max: 1, step: 0.05, default: 0.2 }] },
  }),
  lab({
    slug: "enso",
    title: "ENSO and the Walker cell",
    hook: "The Walker cell can flip. El Niño is a warm pool shift, not a personality. UK weather language stays honest.",
    objective: "See the Walker cell, El Niño and La Niña as Pacific ocean–atmosphere states, and refuse overclaim for a UK winter.",
    realm: "water",
    ages: ["A-level", "APES", "HS Earth Sci"],
    curriculum: ["A-level", "APES 4.9", "NGSS HS-ESS2"],
    steps: steps(
      "Leave the ENSO slider at 0. Normal Walker cell: rise in the west Pacific, sink in the east.",
      "Slide toward El Niño. The warm pool shifts east. Slide the other way for La Niña: the opposite extra.",
      "UK/US: teleconnections exist; they bias odds. They do not write a British month in advance.",
    ),
    questions: [
      q("The Walker cell is…", ["A polar cell", "An east–west tropical Pacific loop", "A meander", "A dune"], 1, "Zonal. Rise west, sink east, in the neutral cartoon."),
      q("El Niño’s warm pool…", ["Vanishes", "Shifts east in the tropical Pacific", "Sits over the UK", "Is a glacier"], 1, "School cartoon, not a GCM."),
      q("For UK winter, ENSO…", ["Always means a White Christmas", "May bias odds; it does not write the month in advance", "Stops the Gulf Stream", "Creates volcanoes"], 1, "No overclaim. Teleconnections are not a forecast of snow."),
      q("La Niña in this lab is…", ["A storm that hits London", "The opposite extra: cooler east Pacific, stronger Walker-like pattern", "A river regime", "A gyre"], 1, "Not a personality. A Pacific state."),
    ],
    why: [
      "El Niño is a Pacific ocean–atmosphere state, not a storm that hits London. Florida’s wet season, Pacific fisheries and an east-Pacific upwelling coast feel the warm-pool shift more clearly than a British playground. Teleconnections exist: they can bias the odds of a UK winter pattern. They do not write December in advance, and they do not promise snow. A tabloid ENSO is the wrong machine. The Walker cell is an east–west tropical loop; when it sloshes, rainfall and upwelling in the equatorial Pacific move with it. US exam language (APES) and UK A-level both need that honesty. Holderness gales and a Thames flood have their own machines. This lab is the Pacific cell and the refusal to overclaim. Same planet, different teleconnection strength. Stay on the physical state: warm pool, rise, sink, return flow.",
      "The Walker cell is an east–west tropical Pacific circulation. Neutral cartoon: air rises over the warm west Pacific, travels east aloft, sinks over the cooler east, and returns west at the surface — trade-wind sense. El Niño: the warm pool slides east; the rise shifts with it; the east Pacific warms; upwelling there weakens in the school story. La Niña: the opposite extra, a stronger Walker-like pattern, cooler east. ENSO is that coupled ocean–atmosphere state, not a personality and not a UK storm. Teleconnections are remote statistical links. They may bias UK winter odds; they do not schedule a White Christmas. Florida and Pacific fisheries are closer to the engine. This is a school cartoon of an equatorial trough, not a GCM, not a forecast, not a Gulf Stream switch. Colour and the sliding warm-pool sphere are the mechanism. Do not put the warm pool over the UK. Do not call El Niño a hurricane. The slider is a phase, from La Niña through neutral to El Niño, not a volume knob for British rain. West Pacific and east Pacific are labelled coasts on the trough. The readout names the phase.",
      "Leave ENSO at 0. Name rise in the west, sink in the east, return flow. Slide toward El Niño and watch the warm pool travel east; the Walker arrows follow. Slide the other way for La Niña. Hide labels (L) and ask which coast is west Pacific. Read the phase in the readout before you claim a UK winter. Keyboard: L labels, R reset. The ENSO slider lives in the bar, −1 to +1. No UK snow button. Finish in Check.",
      "Without the 3D view: a Walker cell — rise west, sink east — in the neutral Pacific. El Niño slides the warm pool east. La Niña is the opposite extra. ENSO is a Pacific ocean–atmosphere state with teleconnections. Those links may bias UK winter odds; they do not write the month, and they do not promise snow. Florida and Pacific fisheries feel it more clearly. School cartoon, not a GCM, not a personality. The slider is a phase, not a volume knob for British rain.",
    ],
    glossary: [
      { term: "Walker cell", def: "Zonal tropical Pacific circulation. Neutral: rise west, sink east." },
      { term: "ENSO", exam: "El Niño–Southern Oscillation", def: "Coupled ocean–atmosphere state of the tropical Pacific. Neutral, El Niño, La Niña." },
      { term: "El Niño", def: "Warm phase. The warm pool shifts east in the tropical Pacific." },
      { term: "La Niña", def: "Cool phase. The opposite extra: cooler east, stronger Walker-like pattern." },
      { term: "Warm pool", def: "The pile of warm surface water. It slides east in El Niño in this cartoon." },
      { term: "Teleconnection", def: "A remote statistical link. May bias odds; does not write a UK month in advance." },
      { term: "Upwelling", def: "East-Pacific rise of cooler water in the neutral and La Niña school story." },
    ],
    misconception: { claim: "El Niño is a storm that hits London.", truth: "It is a Pacific ocean–atmosphere state with teleconnections." },
    misconceptions: [
      { claim: "El Niño is a storm that hits London.", truth: "It is a Pacific ocean–atmosphere state with teleconnections." },
      { claim: "ENSO always means a White Christmas in the UK.", truth: "Teleconnections may bias odds. They do not write the month, and they do not promise snow." },
      { claim: "El Niño is a personality of the weather.", truth: "It is a named phase of a Pacific state. Neutral, El Niño, La Niña — not moods." },
    ],
    cases: [{ slug: "florida-insolation", label: "US ENSO flavour" }, { slug: "uk-daylength", label: "Honest UK language" }],
    teacher: {
      script:
        "Leave the ENSO slider at 0. Normal Walker cell: rise in the west Pacific, sink in the east.\nSlide toward El Niño. The warm pool shifts east in the tropical Pacific.\nSlide the other way for La Niña: the opposite extra.\nEl Niño is not a storm that hits London. It is a Pacific ocean–atmosphere state with teleconnections.\nThat is the misconception. We do not promise UK snow.\nTeleconnections exist. They bias odds. They do not write the month in advance.\nThis is a school cartoon, not a GCM.\nFlorida and Pacific fisheries feel it more clearly than a British playground.\nKeep UK weather language honest. No tabloid ENSO.\nFinish in Check.",
      pitfalls: [
        "Tabloid ENSO.",
        "Promising a UK White Christmas from the slider.",
        "Putting the warm pool over the British Isles.",
      ],
    },
    sources: [{ label: "NOAA ENSO" }, { label: "Met Office ENSO" }],
    controls: { time: "none", extra: [{ key: "enso", label: "ENSO", min: -1, max: 1, step: 0.05, default: 0 }] },
  }),
];
