import type { LabMeta } from "./types";
import { lab, q, steps } from "./make";

export const INTERIOR_LABS: LabMeta[] = [
  lab({
    slug: "continental-drift",
    title: "Continental drift",
    hook: "250 Ma the pieces fit. Fossils agree. The ocean is not a static floor continents plough through.",
    objective: "Scrub 250 Ma to now, toggle fossil/fit overlay, and treat Pangaea as the same plates earlier.",
    realm: "interior",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.1", "NGSS MS-ESS2-3"],
    steps: steps("Pangaea. Fit the coasts.", "Scrub to now. India walks north.", "Fossils and fit are evidence. Plates are the mechanism."),
    questions: [
      q("Pangaea was…", ["The first crust", "A late Palaeozoic–Mesozoic supercontinent, not the only one", "A moon", "A hurricane"], 1, "Not Earth’s starting position."),
      q("Wegener’s fit argument is strongest when…", ["You ignore shelves", "You fit continental shelves, not today’s beaches", "You use flags", "You use time zones"], 1, "Shelf edge."),
      q("Continents move because…", ["They plough a static ocean", "They are passengers on plates", "The Moon drags them", "Wind"], 1, "Ocean floor is plate too."),
      q("The Himalaya record…", ["A hotspot track like Hawaii", "Continent–continent collision after India walked north", "A mid-ocean ridge like Iceland", "Wind piles at San Andreas"], 1, "Same plates, stacked. Iceland makes crust; collision stacks it."),
    ],
    why: [
      "A GCSE class that still thinks continents plough a static ocean will misread Iceland, the Himalaya, and every earthquake map that follows. The United Kingdom is not a plate. It rides the Eurasian plate. The Mid-Atlantic Ridge at Iceland is where that plate is born, a few centimetres per year, with a country sitting on the split. San Andreas is the United States pair: the Pacific and North American plates slide past, so California’s hazard is transform motion, not a continent chewing through a frozen Pacific. Wegener’s coast fit and matching fossils across the young Atlantic are the evidence. Plates are the mechanism he did not have. Himalaya collision is the same machine stacking crust that Iceland makes at a ridge. If the ocean floor were static, those fossils would be a miracle and India would have no walk north into Eurasia. News maps that freeze today’s beaches as eternal outlines hide 250 million years of passengers. Treat Pangaea as the same plates at an earlier time, not a mythic first Earth.",
      "Continents are passengers on lithospheric plates. Oceanic lithosphere is plate too: born at ridges, destroyed at trenches. From about 300 to 180 Ma a supercontinent, Pangaea, sat assembled. It was not Earth’s starting position and not the only supercontinent in the record. After it rifted, the Atlantic opened. India walked north and stacked into Eurasia as the Himalaya. Wegener argued fit, fossils, and palaeoclimate; he lacked a driving mechanism. Seafloor spreading and subduction supply it. Fit the continental shelves, not today’s beaches: the real outline is the shelf edge, the shallow submerged margin. Matching fossils across South America and Africa sit on crust that was once adjacent. The United Kingdom was already a Eurasian passenger. San Andreas did not yet cut California as it does now. The model’s labelled lie is the cartoon you are looking at. Continents are extruded polygons. Motion is a straight interpolation from 250 Ma to the present. Two hundred and fifty million years play in one lesson. Real plate paths curve, rotate, and include microplates this scene omits. The globe is a teaching sphere, not a palaeogeographic reconstruction you could navigate. Fossil matches are dots, not assemblages. What remains true: the pieces fit at the shelf, the Atlantic is young, India has moved north, and neither continent nor ocean is a static stage.",
      "Set the Ma before present slider to 250 Ma. The pieces fit. Toggle Fossil / fit overlay on so matching fossils and the shelf argument read from the back row. When paused, that slider is the clock; Space play overrides it and walks Pangaea to now. Left and right arrows nudge time. Watch India walk north as the Atlantic widens. L toggles labels. R resets to the lab defaults. P switches projector mode. E explode and X slice do nothing here: this is a globe of passengers, not a cut apple. Pause near 0 Ma and name what changed.",
      "Without the 3D view the lesson still holds. At about 250 Ma the continental shelves fit as Pangaea. Matching fossils across the South Atlantic are the evidence; plates are the mechanism. Continents do not plough a static ocean: both are plate. Iceland makes crust at a ridge. The Himalaya stacks it at collision. San Andreas slides. The United Kingdom rides Eurasia. Kola never cored this history; we reconstruct it from fit, fossils, and the ocean floor. If JavaScript is off you still have the caption, the glossary, and Check. Draw two outlines, fit the shelves, then pull them apart. That sketch is the model.",
    ],
    glossary: [
      { term: "Pangaea", def: "Supercontinent ~300–180 Ma. Not the first, not the only, not Earth’s starting position." },
      { term: "Continental shelf", def: "Shallow submerged margin. Fit this edge, not today’s beaches." },
      { term: "Lithosphere", def: "Crust plus the rigid top of the mantle. Plates are lithosphere, not crust alone." },
      { term: "Continental drift", def: "Wegener’s description of moving continents. Plates are the mechanism he lacked." },
      { term: "Seafloor spreading", def: "New oceanic crust at a ridge. Ocean floor is plate too, born and later destroyed." },
      { term: "Subduction", def: "Oceanic plate consumed at a trench. The conveyor’s far end." },
      { term: "Supercontinent", def: "An assembly of most continents. Pangaea is one of several in Earth history." },
      { term: "Shelf fit", exam: "Continental reconstruction", def: "Matching continents at the shelf edge. Beaches are a Holocene disguise." },
    ],
    misconception: { claim: "Continents plough through static oceans.", truth: "Both are plate." },
    misconceptions: [
      { claim: "Continents plough through static oceans.", truth: "Both are plate." },
      { claim: "Pangaea was Earth’s first crust, and the only supercontinent.", truth: "It is a late Palaeozoic–Mesozoic assembly, not a starting position, and not the only one." },
      { claim: "You fit today’s beaches to prove drift.", truth: "Fit continental shelves. The holiday sand is not the outline." },
    ],
    cases: [{ slug: "iceland", label: "Iceland" }, { slug: "san-andreas", label: "San Andreas" }],
    teacher: {
      script:
        "Set Ma before present to 250 Ma. The pieces fit.\nToggle Fossil / fit overlay on. Fossils and the shelf edge are the evidence.\nFit continental shelves, not today’s beaches.\nScrub toward now. India walks north.\nPangaea is a late Palaeozoic–Mesozoic supercontinent, not Earth’s starting position, and not the only one.\nContinents do not plough a static ocean. Both are plate.\nThey are passengers. Ocean floor is plate too.\nWegener had the fit. Plates are the mechanism.\nName Iceland (makes crust), Himalaya (stacks it), San Andreas (slides).\nThe United Kingdom rides Eurasia. It is not a plate.\nPause near 0 Ma and name what changed.\nFinish in Check.",
      pitfalls: [
        "Pangaea as the only supercontinent.",
        "Fitting today’s beaches instead of continental shelves.",
        "Calling the United Kingdom a plate. It rides Eurasia.",
        "Drawing the ocean as a static floor continents plough through.",
      ],
    },
    sources: [{ label: "USGS plates" }, { label: "BGS" }],
    controls: {
      time: "none",
      extra: [{ key: "ageMa", label: "Ma before present", min: 0, max: 250, step: 1, unit: " Ma", default: 200 }],
      toggles: [{ key: "fossils", label: "Fossil / fit overlay" }],
    },
  }),
  lab({
    slug: "hotspots",
    title: "Hotspots",
    hook: "Hawaii and Yellowstone are holes the plate is sliding over — not the same as a plate edge.",
    objective: "Draw the Hawaii chain and the Yellowstone track independently.",
    realm: "interior",
    ages: ["GCSE", "A-level", "NGSS MS", "HS Earth Sci"],
    curriculum: ["GCSE", "NGSS MS-ESS2-3"],
    steps: steps("Hawaii: young island, older seamounts NW.", "Yellowstone: calderas older to the SW.", "Two plumes. One idea."),
    questions: [
      q("A hotspot volcano far from a boundary shows…", ["Plates do not move", "A plume can punch a plate interior", "The Moon", "Only mid-ocean ridges exist"], 1, "Hawaii."),
      q("Older Hawaii volcanoes lie…", ["Southeast", "Northwest along the chain", "In the UK", "On the Moon"], 1, "Pacific plate motion."),
      q("Yellowstone is…", ["A mid-ocean ridge", "A continental hotspot track", "A transform only", "A spit"], 1, "Snake River Plain ages."),
      q("Iceland is a poor copy of Hawaii because…", ["It has no volcanoes", "It sits on a mid-ocean ridge, with a plume as a bonus, not a plate-interior hole alone", "It is in the UK", "It is Cascadia"], 1, "Ridge first. Hawaii is intraplate. Two different machines."),
    ],
    why: [
      "A UK class that dumps every volcano on the Ring of Fire will fail Hawaii and Yellowstone the moment they appear on a map. Most volcanoes do sit on plate edges: Iceland on the Mid-Atlantic Ridge, Cascadia’s arc above a slab. Hawaii does not. It is a hole the Pacific plate is sliding over, a chain of islands and seamounts that get older to the northwest. Yellowstone is the continental analogue: calderas older to the southwest along the Snake River Plain. Two plumes. One idea. Do not teach one plume for both. The United Kingdom rides Eurasia far from either track, which is why British volcanoes are deep-time history, not a live hotspot. United States exam maps pair Hawaii with Yellowstone for a reason: ocean plate versus continent, same mechanism. If all volcanoes were plate-boundary volcanoes, those two tracks would be a mystery and plate motion would lose its best interior clock. Kola never sampled a plume. Age direction on the chain is the clock we actually have.",
      "A hotspot is a long-lived mantle plume that can punch magma through a plate interior. The plume stays relatively fixed in the mantle frame; the plate slides. Hawaii: the active island is young; drowned seamounts and atolls age to the northwest along the chain, recording Pacific motion of centimetres per year. Yellowstone: a continental hotspot. Calderas and rhyolite ages young at the park, older toward the southwest. Cascadia is not this story. It is a subduction zone, a volcanic arc above a slab. Iceland is a ridge with a plume bonus, which is why it has a country on it, not a simple Hawaii copy. The model’s labelled lie is the pipe. The plume is drawn as a glowing cylinder you could climb. It is not. It is a thermal anomaly, schematic. Hawaii ages are a 0–10 Ma teaching set, not the full Emperor–Hawaiian bend. Yellowstone is a slab with a track tube, not a geologic map of the Snake River Plain. Motion is sped up by millions of years so a lesson can see the slide. What remains true: two independent plumes, age direction records plate motion, and not every volcano sits on a plate edge. That exception is the proof that plates move.",
      "Leave the Hawaii toggle on. Press Space: the chain slides northwest while the plume stays. Left and right arrows scrub the same motion. Toggle Yellowstone on and read calderas older to the southwest. Two plumes — do not treat them as one. L toggles labels. R resets. P switches projector mode. E explode and X slice are idle here; there is no onion to pull apart. Ask which way each plate is going from the age direction before you name it. Then turn one track off so the class cannot blur them.",
      "Without WebGL the caption still teaches the exception. Hawaii is young at the southeast end, older seamounts northwest. The plume stays; the Pacific plate slides. Yellowstone is a second plume under a continent, ages older to the southwest. Iceland is a ridge, not this story. Cascadia is subduction, not this story. The United Kingdom is not on either track. If JavaScript is off you still have the glossary and Check. Sketch a fixed dot and a sliding plate with dated volcanoes. That drawing is the lab. Two dots if you add Yellowstone. Never one pipe feeding both.",
    ],
    glossary: [
      { term: "Hotspot", def: "Long-lived mantle plume that can punch a volcano through a plate interior." },
      { term: "Seamount", def: "Drowned volcano on the track. Older, farther from the active island." },
      { term: "Mantle plume", def: "A thermal upwelling, relatively fixed in the mantle frame. Not a climbable pipe." },
      { term: "Caldera", def: "Collapse crater after a large eruption. Yellowstone’s track is dated calderas." },
      { term: "Age-progressive chain", def: "Volcanoes that get older away from the active centre, recording plate motion." },
      { term: "Intraplate volcanism", def: "Melting inside a plate, not at a ridge, trench, or transform." },
      { term: "Partial melt", def: "A fraction of the rock is liquid. A plume is not a magma ocean." },
      { term: "Guyot", exam: "Flat-topped seamount", def: "An eroded, drowned volcano on a hotspot track, often now an atoll or bank." },
    ],
    misconception: { claim: "All volcanoes are plate-boundary volcanoes.", truth: "Hotspots are the exception that proves motion." },
    misconceptions: [
      { claim: "All volcanoes are plate-boundary volcanoes.", truth: "Hotspots are the exception that proves motion." },
      { claim: "Hawaii and Yellowstone are one plume.", truth: "Two plumes. One idea. Age tracks point different ways on different plates." },
      { claim: "Iceland is a Hawaii copy, and Yellowstone is a mid-ocean ridge.", truth: "Iceland sits on a ridge with a plume bonus. Yellowstone is a continental hotspot. Cascadia is subduction." },
    ],
    cases: [{ slug: "hawaii", label: "Hawaii" }, { slug: "yellowstone", label: "Yellowstone" }],
    teacher: {
      script:
        "Leave Hawaii on. Young island, older seamounts northwest.\nThe chain is the Pacific plate sliding over a plume, not a plate edge.\nAsk which way the plate is going from the age direction.\nToggle Yellowstone on. Calderas older to the southwest.\nTwo plumes. One idea. Do not teach one plume for both.\nAll volcanoes are not plate-boundary volcanoes. That is the misconception.\nHotspots are the exception that proves motion.\nIceland is a ridge with a plume bonus, not a Hawaii copy. Cascadia is subduction, not this.\nA plume can punch a plate interior. Hawaii is the type case.\nYellowstone is a continental hotspot track, not a mid-ocean ridge.\nFinish in Check.",
      pitfalls: [
        "One plume for both.",
        "Dumping Hawaii on the Ring of Fire.",
        "Treating Iceland as a Hawaii copy, or Yellowstone as a mid-ocean ridge.",
        "Drawing the plume as a lava pipe you could climb.",
      ],
    },
    sources: [{ label: "USGS HVO" }, { label: "USGS YVO" }],
    controls: {
      time: "none",
      toggles: [
        { key: "hawaii", label: "Hawaii", defaultOn: true },
        { key: "yellowstone", label: "Yellowstone" },
      ],
    },
  }),
  lab({
    slug: "seafloor-spreading",
    title: "Seafloor spreading",
    hook: "Magnetic stripes are a tape recorder. New crust at the ridge, older away.",
    objective: "Watch stripes move apart from the Mid-Atlantic Ridge.",
    realm: "interior",
    ages: ["GCSE", "A-level", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.1", "NGSS MS-ESS2-3"],
    steps: steps("Ridge. New stripe.", "Play: bands walk away, mirrored.", "Reversals record time. Iceland sits on this."),
    questions: [
      q("Newest crust is…", ["At the continents", "At the ridge axis", "At the trench only", "In the inner core"], 1, "Spreading centre."),
      q("Stripes are symmetric because…", ["Wind", "Both sides of the ridge add crust", "Tides", "One plate only"], 1, "Mirror."),
      q("Magnetic stripes record…", ["Rain", "Geomagnetic reversals frozen in cooling basalt", "Moon phases", "Albedo"], 1, "Vine–Matthews."),
      q("Old ocean floor is destroyed at…", ["Every beach", "Trenches such as Cascadia, not at San Andreas", "The inner core", "Kola"], 1, "Born at ridges, eaten at trenches. Transform is a different job."),
    ],
    why: [
      "Iceland is the ridge with a country on it, which is why every UK specification parks a case study there. New crust at the axis, older as you walk toward Europe or North America, centimetres per year. Magnetic stripes are the tape recorder: geomagnetic reversals frozen in cooling basalt, mirrored on both flanks. The United States pair is not a second Iceland. Cascadia consumes old Pacific crust at a trench; San Andreas is a transform that does not make ocean floor. Together they complete the conveyor: born at Iceland’s ridge, aged across the basin, destroyed or slid at the far edge. If ocean floor were all the same age, those stripes would not exist and Iceland would be a mystery island. A class that treats the Atlantic as primordial water has not met Vine–Matthews. Kola’s borehole never reached this story; this is surface basalt writing time, not a 12 km scratch in continental crust. UK and US maps both freeze today’s ocean as if it had always been there. It has not.",
      "At a mid-ocean ridge, plates diverge. Magma fills the gap; new oceanic crust records the field as it cools through the Curie point. Newest crust sits at the ridge axis. Stripes are symmetric because both sides add crust. Vine–Matthews: reversals frozen in basalt, a tape recorder of time. Spreading rate is how fast plates separate, typically centimetres per year, not a weather story. Iceland sits on the Mid-Atlantic Ridge, plume-boosted, which is why there is land. Old crust is not immortal: it ages away and is swallowed at trenches such as Cascadia. San Andreas is a different boundary — transform, no stripe factory. The Himalaya stack continent on continent; they do not print this tape. The model’s labelled lie is printed on the studio: vertical exaggeration ×12. The ridge is a mountain under the sea, but this height field is a classroom cliff. Stripes are colour bands, not a magnetometer record. Spreading that fills a lesson is millions of years of centimetres per year. Transform offsets on the ridge are a sine wobble, not a fracture-zone chart. What remains true: young at the axis, old away, mirrored polarity, Iceland on the ridge. Ocean floor is not all the same age.",
      "There is no extra slider on this lab. Find the ridge axis — newest crust sits there. Press Space: new stripes walk away, mirrored. Left and right arrows nudge the same tape. L toggles labels. R resets. P switches projector mode. E explode and X slice do nothing; this is a seafloor, not an onion. Point at the mirror. Pause and say young at the axis, old on the flanks. Name Iceland as the land on this machine, Cascadia as a place old floor can die, San Andreas as a boundary that does not print stripes.",
      "Without the 3D view a ridge axis, magnetic stripes as a mirror, and age increasing away still teach the tape. Newest crust at the axis; both sides add crust. Reversals frozen in cooling basalt are the clock. Iceland sits on this ridge. Cascadia is where old floor can die; San Andreas is not a spreading centre. The fallback caption is the whole mechanism. Draw a centre line, hatch mirrored bands, and arrow them outward. That sketch is Vine–Matthews. If JavaScript is off you still have the glossary and Check. Do not wait for WebGL to say the ocean has an age.",
    ],
    glossary: [
      { term: "Spreading rate", def: "How fast plates separate at a ridge. Centimetres per year, not a weather story." },
      { term: "Magnetic reversal", def: "The geomagnetic field flips. Cooling basalt keeps a snapshot of polarity." },
      { term: "Mid-ocean ridge", def: "Divergent plate boundary. New oceanic crust at the axis. Iceland sits on one." },
      { term: "Vine–Matthews", exam: "Vine–Matthews–Morley hypothesis", def: "Magnetic stripes as a tape recorder of reversals and spreading." },
      { term: "Oceanic crust", def: "Basalt and gabbro, ~7 km thick, young at ridges, old toward trenches." },
      { term: "Magnetic stripe", def: "A band of normal or reversed polarity, mirrored on both flanks of the ridge." },
      { term: "Curie point", def: "Temperature below which cooling rock locks in the ambient magnetic field." },
      { term: "Fracture zone", def: "A scar of transform offset on the ridge. This lab only hints at it." },
    ],
    misconception: { claim: "Ocean floor is all the same age.", truth: "Young at ridges, old at trenches." },
    misconceptions: [
      { claim: "Ocean floor is all the same age.", truth: "Young at ridges, old at trenches." },
      { claim: "Magnetic stripes are waves on the sea.", truth: "They are polarity frozen in cooling basalt, a tape recorder, not a swell." },
      { claim: "San Andreas is a spreading centre, like Iceland.", truth: "San Andreas is transform. Iceland is the ridge. Cascadia is where old floor can be swallowed." },
    ],
    cases: [{ slug: "iceland", label: "Iceland / MAR" }, { slug: "san-andreas", label: "A different boundary" }],
    teacher: {
      script:
        "Find the ridge axis. Newest crust sits there.\nPlay spreading. New stripes walk away, mirrored.\nPoint at the mirror. Both sides of the ridge add crust.\nMagnetic stripes record geomagnetic reversals frozen in cooling basalt.\nThey are not waves. That pitfall is on the board.\nOcean floor is not all the same age. Young at ridges, old at trenches.\nIceland sits on this ridge with a country on it.\nCascadia can swallow old floor. San Andreas does not make stripes.\nVine–Matthews is the tape recorder. Reversals are time.\nSpreading rate is how fast the plates separate, not a weather story.\nThe ridge height is exaggerated ×12. Say the labelled lie out loud.\nFinish in Check.",
      pitfalls: [
        "Stripes as waves.",
        "Ocean floor all the same age.",
        "Calling San Andreas a spreading centre.",
        "Forgetting the vertical exaggeration ×12 on the ridge.",
      ],
    },
    sources: [{ label: "USGS seafloor" }, { label: "NOAA" }],
    controls: { time: "none" },
  }),
];
