import type { LabMeta } from "./types";
import { lab, q, steps } from "./make";

export const LANDFORM_LABS: LabMeta[] = [
  lab({
    slug: "landform-types",
    title: "Landform types",
    hook: "A mountain is not a hill with ambition. Height, slope, and a flat top are different machines.",
    objective: "Compare mountain, hill, plateau, plain, and basin at one scale.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "GCSE landscapes", "NGSS MS-ESS2-2"],
    steps: steps("Orbit the five. Same scale bar.", "Hide labels and name them.", "Plateau is height with a flat top. Basin is a bowl. Plain is low and open."),
    questions: [
      q("A plateau is…", ["A V-valley", "An elevated area with a relatively flat top", "Always volcanic", "A spit"], 1, "Height plus a table top."),
      q("A basin is…", ["A peak", "A depression; drainage often inward or along the floor", "A delta", "An arête"], 1, "The opposite of a dome."),
      q("A mountain vs a hill is mainly…", ["Colour", "Relief, slope and local height — a continuum, not a law", "Always ice", "Always granite"], 1, "Definitions vary by country. Compare, don’t legislate."),
      q("The Grand Canyon is best described as…", ["A mountain range", "A canyon cut into a plateau", "A glacial U-trough", "A basin with no river"], 1, "Height with a table, then a hole. Not a mountain. Not ice."),
    ],
    why: [
      "Snowdonia is mountains: steep relief, cwms, a peak that is not a table. The Grand Canyon is a canyon cut into a plateau — high land with a relatively flat top, then a hole. A Yorkshire Dales knoll is smaller relief; the Mississippi floodplain is a plain. Those four, plus a basin as a bowl, are different machines, not a ranking of ambition. UK GCSE physical landscapes and NGSS MS-ESS2-2 both ask students to name a landform from height, slope, and plan shape. Fieldwork in Eryri and a rim walk at Grand Canyon fail if every high place is called a mountain. A plateau is height with a table. A basin is a depression. A plain is low and open. Mountain versus hill is a continuum of relief; definitions vary by country. The lab compares at one scale. It does not legislate. Same scale bar, different jobs: that is the whole argument.",
      "Four patches sit on one studio floor with one scale bar. Vertical exaggeration is labelled ×8 so the set reads from the back of the room; true relief on a table-sized floor would be millimetres. Mountain: high local relief, steep slopes, a peak — Snowdonia’s machine, not a hill with ambition. Hill: smaller relief, rounded slopes — a continuum, not a law; countries disagree on the cut. Plateau: elevated land with a relatively flat top. The Colorado Plateau that the Grand Canyon cuts is this shape; the canyon is the hole, not the landform type. Plain: low, gently sloping, open — Mississippi alluvium, not a failed mountain. Basin: a bowl; drainage often inward or along the floor. Height plus slope plus plan is the classifier. Colour is not. Granite does not make a mountain if the relief is small; limestone can make a plateau. The five words are not five laws of nature. The model is a comparison floor, not a traced OS sheet or a USGS quad. Orbit at one scale; hide the labels and name them; then reveal. A plateau is not a mountain with the top sawn off as a moral. It is a different slope history, and the exaggeration caption is the honesty.",
      "Orbit the five at one scale. Hide labels. Point. Wait. Then reveal. The same scale bar is the argument: a mountain is not a hill with ambition, and a plateau is height with a table. Ask which patch is the Grand Canyon’s host landform before you name plateau. Keyboard: L labels, R reset, arrows to step the camera along the patches. There is no time slider; the land does not play. Vertical exaggeration is ×8 and labelled on the caption. Finish in Check. The wrong answer is always that every high place is a mountain.",
      "Without the 3D view the sentence still holds. Mountain, hill, plateau, plain, and basin are height-and-slope machines compared at one scale. A plateau is high and flat. A basin is a bowl. A plain is low and open. Mountain versus hill is relief, not a law. Grand Canyon is a canyon in a plateau. Snowdonia is mountains. Vertical exaggeration is ×8 and labelled. Five words are not five laws of nature. Colour is not a classifier. Definitions vary by country; compare, do not legislate.",
    ],
    glossary: [
      { term: "Mountain", def: "High local relief, steep slopes, a peak. Not a hill with ambition." },
      { term: "Hill", def: "Smaller relief, often rounded. A continuum with mountain, not a fixed-height law." },
      { term: "Plateau", def: "Elevated land with a relatively flat top." },
      { term: "Plain", def: "Low, gently sloping, open land." },
      { term: "Basin", def: "A bowl. Interior drainage or a low among highs." },
      { term: "Relief", def: "The difference in height across a landscape. The classifier, not colour." },
      { term: "Canyon", def: "A deep, steep-sided incision, often cut into a plateau. The hole, not the host landform." },
    ],
    misconception: { claim: "Every high place is a mountain.", truth: "Plateaus are high and flat. Hills are smaller relief." },
    misconceptions: [
      {
        claim: "Every high place is a mountain.",
        truth: "Plateaus are high and flat. Hills are smaller relief.",
      },
      {
        claim: "The Grand Canyon is a mountain range.",
        truth: "It is a canyon cut into a plateau. The plateau is the landform type; the canyon is the hole.",
      },
      {
        claim: "Mountain versus hill is a law with a fixed height.",
        truth: "Definitions vary by country. Compare relief, slope and local height. Do not legislate.",
      },
    ],
    cases: [{ slug: "snowdonia", label: "Snowdonia" }, { slug: "grand-canyon", label: "Grand Canyon plateau" }],
    teacher: {
      script:
        "Orbit the five at one scale: mountain, hill, plateau, plain, basin.\nCover the labels. Point. Wait. Then reveal.\nA plateau is height with a relatively flat top. A basin is a bowl. A plain is low and open.\nEvery high place is not a mountain. Plateaus are high and flat. Hills are smaller relief.\nThat is the misconception.\nMountain versus hill is relief, slope and local height — a continuum, not a law.\nDefinitions vary by country. Compare, do not legislate.\nGrand Canyon is a canyon in a plateau. Snowdonia is mountains. Same lab, different places.\nVertical exaggeration is ×8 and labelled. Five words are not five laws of nature.\nFinish in Check.",
      pitfalls: [
        "Teaching five words as five laws of nature.",
        "Calling the Grand Canyon a mountain range.",
        "Treating mountain versus hill as a fixed-height law.",
      ],
    },
    sources: [{ label: "USGS landforms" }, { label: "BGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "river-erosion",
    title: "River erosion",
    hook: "A waterfall is a nick point walking upstream.",
    objective: "Match waterfall, gorge, pothole, V-valley, and play nick-point retreat.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.3.1", "NGSS MS-ESS2-2"],
    steps: steps("Upper course: V, waterfall, plunge pool.", "Play: the nick point retreats, leaving a gorge.", "Hydraulic action, abrasion, attrition. Vertical erosion dominates here."),
    questions: [
      q("Nick-point retreat leaves…", ["A delta", "A gorge upstream of the old fall", "A spit", "An oxbow"], 1, "The fall walks back; a gorge is the scar."),
      q("Potholes form by…", ["Wind only", "Pebbles swirling and abrading the bed", "Lava", "Tides"], 1, "Corrosion plus abrasion in a hollow."),
      q("V-valleys are typical of…", ["Glaciers", "Upland fluvial vertical erosion", "Fold mountains only", "Karst only"], 1, "Ice makes U. Water makes V — until ice has been there first."),
      q("The Grand Canyon formed mainly by…", ["A glacier cutting a U", "A rift pulling apart", "A river incising a plateau", "Wind carving a yardang"], 2, "Incision. Ice makes U. This is a river in a plateau. The hole is younger than the rocks."),
    ],
    why: [
      "A Lake District waterfall sits on a resistant band and walks slowly upstream. The gorge behind it is the scar. The Colorado River cut a plateau; the Grand Canyon is incision, not a rift and not a glacial U. UK GCSE rivers and NGSS MS-ESS2-2 both need that distinction. A beck in spate is vertical erosion: V-valley, plunge pool, potholes where pebbles swirl. Hydraulic action, abrasion, and attrition are the toolkit; corrosion helps on limestone. Niagara is the famous slow walk, not a waterfall that stays put. Fieldwork in Borrowdale and a rim talk at Grand Canyon fail if every valley is called a canyon and every fall is treated as furniture. Nick-point retreat is the plot. Water makes a V until ice has been there first.",
      "Upper course: steep gradient, high potential energy, vertical erosion dominating. A nick point is a break of slope — often a waterfall on a resistant band — with a plunge pool at its foot. Play the lab and the lip walks upstream; the gorge is the slot the fall leaves as it retreats. Potholes form where pebbles are trapped and swirl, abrading the bed. V-valleys are the fluvial cross-profile; ice makes a U, water a V, until ice has been there first and the beck cuts a V into a trough floor, as in the Lake District. Hydraulic action, abrasion, and attrition do the cutting. The Grand Canyon is the same machine at plateau scale: the river exports, weathering and mass movement deliver from the walls, the hole is younger than the rocks. Vertical exaggeration is labelled ×12 on the long profile so the lip and the V read from the back row. True gradient on a table would be almost flat. The valley is a schematic long profile, not a traced catchment. Waterfalls do not stay put. Niagara is the slow famous walk; a Lake District fall on Borrowdale volcanic rock is the same retreat at a smaller station.",
      "Freeze on the waterfall. Name V-valley, fall, and plunge pool before you press play. Play nick-point retreat; the fall walks upstream. Ask what the gorge is — it is the scar the lip leaves. Keyboard: space play, arrows scrub, L labels, R reset. There is no discharge slider here; that lives on the rivers long-profile lab. Vertical exaggeration is ×12 and labelled. Finish in Check. The wrong answer is that waterfalls stay put, or that every valley is a canyon.",
      "Without the 3D view: a nick point retreats; a gorge is the scar; potholes are pebbles swirling on the bed; V-valleys are upland fluvial; ice makes U. Lake District falls sit on resistant bands. The Colorado cut a plateau. Vertical exaggeration is ×12 and labelled. Water is not a pipe. Waterfalls walk. Niagara is the slow famous walk. Do not call every valley a canyon. Hydraulic action, abrasion, and attrition are the toolkit; vertical erosion dominates here. The age of the rock is not the age of the hole.",
    ],
    glossary: [
      { term: "Nick point", exam: "Knickpoint", def: "A break of slope, often a waterfall, that can retreat upstream." },
      { term: "Gorge", def: "Steep-sided valley, often the scar a retreating fall leaves." },
      { term: "Plunge pool", def: "Deep hollow at the foot of a fall, scoured by falling water and load." },
      { term: "Pothole", def: "Bed hollow where pebbles swirl and abrade." },
      { term: "V-valley", def: "Cross-profile of upland fluvial vertical erosion. Ice makes U." },
      { term: "Hydraulic action", def: "Force of water and trapped air on joints and the bed." },
      { term: "Abrasion", exam: "Corrasion", def: "Load scratching and grinding the bed and banks." },
      { term: "Attrition", def: "Load particles colliding and rounding each other." },
    ],
    misconception: { claim: "Waterfalls stay put.", truth: "They retreat. Niagara is the famous slow walk." },
    misconceptions: [
      {
        claim: "Waterfalls stay put.",
        truth: "They retreat. Niagara is the famous slow walk. A Lake District fall on a resistant band does the same.",
      },
      {
        claim: "Every valley is a canyon.",
        truth: "A canyon is a deep, steep-sided incision. V-valleys are upland fluvial. Ice makes U.",
      },
      {
        claim: "The age of the canyon is the age of the rocks in the walls.",
        truth: "Rocks can be hundreds of millions of years old. The hole is much younger. Incision is not the birthday of the beds.",
      },
    ],
    cases: [{ slug: "lake-district", label: "Lake District" }, { slug: "grand-canyon", label: "Grand Canyon incision" }],
    teacher: {
      script:
        "Freeze on the waterfall. Upper course: V-valley, fall, plunge pool.\nPlay nick-point retreat. The fall walks upstream.\nAsk what the gorge is. It is the scar the fall leaves as it retreats.\nWaterfalls do not stay put. Niagara is the famous slow walk.\nThat is the misconception.\nPotholes form where pebbles swirl and abrade the bed.\nHydraulic action, abrasion, attrition. Vertical erosion dominates here.\nV-valleys are upland fluvial. Ice makes U. Water makes V — until ice has been there first.\nGrand Canyon is a river cutting a plateau, not a glacial U. Vertical exaggeration is ×12 and labelled.\nDo not call every valley a canyon. Finish in Check.",
      pitfalls: [
        "Calling every valley a canyon.",
        "Teaching waterfalls as furniture that never moves.",
        "Confusing the age of the rocks with the age of the hole.",
      ],
    },
    sources: [{ label: "BGS fluvial" }, { label: "USGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "river-deposition",
    title: "River deposition",
    hook: "When the water slows, the load sits down: slip-off slope, levée, floodplain, delta, estuary.",
    objective: "Name slip-off slope, levées, floodplain, delta, estuary and say why UK rivers often end in estuaries.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "A-level"],
    curriculum: ["GCSE AQA 3.1.3.1", "A-level"],
    steps: steps("Inner bank: slip-off. Flood: levées and floodplain.", "Play the delta building into still water.", "Estuary if tides win. Delta if load wins."),
    questions: [
      q("A slip-off slope is…", ["The outer bank cliff", "Deposition on the inner bend of a meander", "A waterfall", "A stack"], 1, "Helicoidal flow dumps on the inside."),
      q("Levées form when…", ["Tides cut a cliff", "Floodwater leaves the channel and dumps coarse load on the banks", "Ice ploughs", "Wind piles sand"], 1, "Raised banks."),
      q("Many UK rivers end in estuaries because…", ["No load ever", "Tidal range and a drowned coast can outpace delta building", "No rain", "They are all glaciers"], 1, "Mississippi: huge load, modest tides."),
      q("The outer bank of a meander is mainly a site of…", ["Deposition of a point bar", "Erosion of a cut bank", "A terminal moraine", "A swallow hole"], 1, "Helicoidal flow: dump inside, cut outside."),
    ],
    why: [
      "When the water slows, the load sits down. A Lake District beck rarely builds a classic delta because the load meets a lake or a tide that can take it. The Mississippi drops a continental load into a modest-tide Gulf and keeps a bird-foot delta. Somerset Levels are floodplain and levée at UK scale. Many UK rivers end in estuaries because tidal range and a drowned coast outpace delta building. GCSE AQA 3.1.3.1 and A-level fluvial both need that split. Channel management — dredge, levée, cut-off — fights or copies these processes. Students who label a UK estuary a delta to tidy the diagram will misread Holderness’s neighbour coasts and the Mississippi alike. Slip-off slope, levée, floodplain, delta, estuary: five names, one slowing.",
      "Helicoidal flow in a meander dumps on the inner bend: that is the slip-off slope, or point bar. The outer bank is the cut bank, eroded, not deposited. In flood, water leaves the channel; coarse load dumps first on the banks and builds levées; the rest of the floodplain takes finer sediment. A delta grows where a river enters stiller water faster than tides and waves can steal the load. An estuary is a tidal mouth: mixing, often no classic delta. Estuary if tides win; delta if load wins. Mississippi: huge load, modest tides. Many UK mouths: smaller load, larger tidal range, often a drowned valley. Play the lab and the flood stage rises; overbank water is the floodplain argument. Vertical exaggeration is labelled ×8 so meander, levée and delta fingers read from the back of the room. The channel is a schematic meander, not the Parrett or the Mississippi traced. Water is a thin surface. Every river does not build a delta. Tides and waves can steal the load. Raised banks are levées, not walls invented by engineers — though engineers copy them. Somerset Levels sit on this machine at UK scale; the bird-foot at the Gulf is the same slowing with more sand.",
      "Point inner bank versus outer. Name the slip-off slope on the inside before you reveal the tag. Raise the idea of flood: coarse load on the banks is levées; the floodplain is the rest. Play until the delta fingers read, then ask estuary or delta and why a UK mouth often loses. Keyboard: space, arrows, L labels, R reset. Vertical exaggeration is ×8 and labelled. Play once, rewind, name the five landforms. Finish in Check. The wrong answer is that every river builds a delta.",
      "Without the 3D view: when water slows, load sits down. Inner bend: slip-off. Flood: levées and floodplain. Delta if load wins; estuary if tides win. Many UK rivers end in estuaries. Mississippi: huge load, modest tides. Somerset Levels are deposition at another scale. Vertical exaggeration is ×8 and labelled. Do not label a UK estuary a delta to make the diagram tidy. Helicoidal flow dumps on the inside; the outer bank is the cut. Engineers copy levées; they did not invent the process.",
    ],
    glossary: [
      { term: "Slip-off slope", exam: "Point bar", def: "Deposition on the inner bend of a meander." },
      { term: "Cut bank", def: "The outer bank, eroded by faster flow." },
      { term: "Levée", exam: "Levee", def: "Raised bank of coarse flood deposits." },
      { term: "Floodplain", def: "The floor a river builds and occasionally floods beside the channel." },
      { term: "Delta", def: "Load dropped into stiller water faster than tides and waves can steal it." },
      { term: "Estuary", def: "Tidal mouth. Mixing, often no classic delta." },
      { term: "Helicoidal flow", def: "The corkscrew current in a meander: outer erosion, inner deposition." },
    ],
    misconception: { claim: "Every river builds a delta.", truth: "Tides and waves can steal the load." },
    misconceptions: [
      {
        claim: "Every river builds a delta.",
        truth: "Tides and waves can steal the load. Many UK mouths are estuaries.",
      },
      {
        claim: "The outer bank is where the river dumps sand.",
        truth: "Outer is the cut bank. Inner is the slip-off slope. Helicoidal flow.",
      },
      {
        claim: "Levées are only built by engineers.",
        truth: "Natural levées are coarse flood deposits on the banks. Engineers copy them.",
      },
    ],
    cases: [{ slug: "mississippi", label: "Mississippi delta" }, { slug: "somerset-levels", label: "Somerset Levels" }],
    teacher: {
      script:
        "Point inner bank versus outer. Slip-off slope is deposition on the inner bend.\nRaise the idea of flood. Coarse load dumps on the banks: levées. The floodplain is the rest.\nPlay the delta building into still water.\nEvery river does not build a delta. Tides and waves can steal the load.\nThat is the misconception.\nEstuary if tides win. Delta if load wins.\nMany UK rivers end in estuaries because tidal range and a drowned coast can outpace delta building.\nMississippi: huge load, modest tides. Somerset Levels are deposition at another scale.\nVertical exaggeration is ×8 and labelled. Do not label a UK estuary a delta to make the diagram tidy.\nFinish in Check.",
      pitfalls: [
        "UK ‘deltas’ that are estuaries.",
        "Mixing inner-bank deposition with outer-bank erosion.",
        "Teaching levées as only an engineering product.",
      ],
    },
    sources: [{ label: "USGS Mississippi" }, { label: "BGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "river-capture",
    title: "River capture",
    hook: "A more aggressive neighbour can steal a headwater. The elbow is the scar.",
    objective: "Animate elbow of capture and a beheaded stream.",
    realm: "landforms",
    ages: ["GCSE", "A-level", "NGSS MS"],
    curriculum: ["GCSE", "A-level fluvial"],
    steps: steps("Two catchments. One nick point is lower.", "Play: the pirate cuts back, captures, elbow forms, the loser is beheaded.", "Wind gap / dry valley may remain."),
    questions: [
      q("An elbow of capture is…", ["A meander", "A sharp bend where the captured stream now turns into the pirate", "A delta", "A spit"], 1, "The turn is the evidence."),
      q("A beheaded stream…", ["Gains water", "Loses its headwaters and often shrinks", "Becomes a glacier", "Always dries in a day"], 1, "Misfit in a too-big valley."),
      q("Capture is more likely when…", ["Both rivers sit at the same height forever", "One has a steeper gradient or weaker rock and cuts back faster", "There is no rain", "Tides are huge"], 1, "Headward erosion."),
      q("Old River on the Mississippi is…", ["A waterfall", "Capture at engineering scale — the Atchafalaya would take the flow", "A spit", "A cirque"], 1, "USACE holds a steal the hills would finish."),
    ],
    why: [
      "Watersheds move. A more aggressive neighbour can steal a headwater, and the elbow is the scar. Old River on the Mississippi is capture at engineering scale: the Atchafalaya would take the flow if the USACE structure were not there. UK upland divides in the Lake District and the Pennines have quieter elbows and misfit beheaded streams. GCSE and A-level fluvial treat capture as headward erosion, not magic. A wind gap or dry valley may remain where the loser used to flow. Students who think a watershed is a fence that never moves will misread both a UK divide and the Old River Control Structure. The pirate is the steeper or weaker-rock neighbour. The loser shrinks. That steal is slow in the hills and sudden only in the cartoon.",
      "Two catchments. One nick point is lower. The pirate cuts back by headward erosion, captures the higher stream, and the water turns: that sharp bend is the elbow of capture. The loser is a beheaded stream, often a misfit in a too-big valley. A wind gap or dry valley may remain on the old course. Capture is more likely when one river has a steeper gradient or weaker rock and so cuts back faster. It is not instant. Play the lab: before the steal, two valleys; after, an elbow, a wind gap, a beheaded reach. Vertical exaggeration is labelled ×10 so the two valley floors and the divide read from the back of the room; true divide relief on a table would almost vanish. Water is a thin surface. The valley is a schematic long profile, not a traced catchment. Old River is the named US case: capture that engineers spend a century holding back. Lake District divides are the UK pair, slower, still the same steal. Watersheds are not painted fences. Headward erosion moves them. The elbow is the evidence; the wind gap is the ghost of the old route; the beheaded stream is the loser living in a valley cut for more water than it now has.",
      "Pause before capture. Two catchments. One nick point is lower. Predict which neighbour is the pirate before you press play. Play: the pirate cuts back, captures, an elbow forms, the loser is beheaded. Name the elbow of capture and the wind gap out loud. Keyboard: space, arrows, L labels, R reset. Vertical exaggeration is ×10 and labelled. Do not skip the pause before the steal. Finish in Check. The wrong answer is that watersheds never move, or that capture is instant magic.",
      "Without the 3D view: a lower, steeper neighbour can cut back and steal a headwater. The elbow is the turn into the pirate. The beheaded stream is the loser, often a misfit in a too-big valley. A wind gap may remain. Watersheds move by headward erosion. Old River on the Mississippi is capture at engineering scale. Lake District divides are the quieter UK pair. Vertical exaggeration is ×10 and labelled. It is not instant magic. The pirate is the steeper or weaker-rock neighbour.",
    ],
    glossary: [
      { term: "Elbow of capture", def: "Sharp turn at the capture point, where water now flows into the pirate." },
      { term: "Beheaded stream", def: "The loser, missing its headwaters, often a misfit in a too-big valley." },
      { term: "Pirate stream", def: "The aggressor that captures by headward erosion." },
      { term: "Wind gap", def: "A dry col on the old course, left after capture." },
      { term: "Headward erosion", def: "Cutting back at the source, which can move a watershed." },
      { term: "Watershed", exam: "Drainage divide", def: "The rim of a catchment. It can move." },
      { term: "Misfit stream", def: "A stream too small for the valley it occupies — often a beheaded loser." },
    ],
    misconception: { claim: "Watersheds never move.", truth: "Headward erosion moves them." },
    misconceptions: [
      {
        claim: "Watersheds never move.",
        truth: "Headward erosion moves them. The elbow is the scar.",
      },
      {
        claim: "Capture is instant magic.",
        truth: "It is slow headward cutting. A wind gap or dry valley may remain.",
      },
      {
        claim: "The beheaded stream gains water.",
        truth: "It loses its headwaters and often shrinks. Misfit in a too-big valley.",
      },
    ],
    cases: [{ slug: "mississippi", label: "Mississippi / Atchafalaya" }, { slug: "lake-district", label: "UK upland divides" }],
    teacher: {
      script:
        "Pause before capture. Two catchments. One nick point is lower.\nPredict which neighbour is the pirate.\nPlay: the pirate cuts back, captures, an elbow forms, the loser is beheaded.\nName the elbow of capture: the sharp turn into the pirate.\nName the beheaded stream: missing its headwaters, often a misfit in a too-big valley.\nName the wind gap: the ghost of the old course.\nWatersheds do move. Headward erosion moves them.\nThat is the misconception.\nCapture is more likely when one has a steeper gradient or weaker rock and cuts back faster. It is not instant magic.\nOld River is the US engineering-scale steal. Vertical exaggeration is ×10 and labelled. Finish in Check.",
      pitfalls: [
        "Teaching capture as instant magic.",
        "Drawing watersheds as fences that never move.",
        "Forgetting the wind gap as evidence.",
      ],
    },
    sources: [{ label: "USACE Old River" }, { label: "BGS" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "coasts",
    title: "Coasts",
    hook: "Constructive waves build. Destructive waves take. Longshore drift is the conveyor. Cave–arch–stack–stump is the headland’s life.",
    objective: "Toggle wave type, watch longshore particles, step cave to stump, and grow a spit.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.3.2", "NGSS MS-ESS2-2"],
    steps: steps("Constructive: strong swash. Destructive: backwash wins.", "Particles walk alongshore. A spit grows where the coast turns.", "Stage slider: cave, arch, stack, stump."),
    questions: [
      q("Longshore drift moves sediment…", ["Straight out to sea only", "Along the beach in the direction of the angled swash", "Only on rivers", "Up cliffs"], 1, "Zigzag of swash and backwash."),
      q("A stack is…", ["A spit", "An isolated pillar after an arch collapses", "A levée", "A cirque"], 1, "Cave → arch → stack → stump."),
      q("Mappleton groynes…", ["Create sand everywhere", "Trap sediment up-drift and can starve down-drift", "Stop the Earth rotating", "Build deltas"], 1, "Holderness bargain."),
      q("A sea wall along a whole coast…", ["Fixes the sediment budget forever", "Moves the problem along the budget", "Creates a delta", "Stops longshore drift worldwide"], 1, "Protection here, starvation there. Holderness and the Outer Banks share the budget idea."),
    ],
    why: [
      "Holderness till cliffs lose metres a year into the North Sea; Mappleton’s groynes trap sand up-drift and can starve down-drift. Spurn Head is the spit at the turn into the Humber. The Outer Banks of North Carolina are sand in a barrier-island chain, not a till cliff, with longshore drift, storm inlets, and Cape Hatteras as a famous turn. Same budget idea: supply, transport, deposition, interruption. The Jurassic Coast writes cave–arch–stack–stump in Lias and chalk — Durdle Door, Old Harry — a harder lithology, a slower headland life. GCSE AQA 3.1.3.2 and NGSS MS-ESS2-2 both need wave type, longshore drift, and a headland sequence, plus the honesty that a sea wall does not fix the whole coast. It moves the problem along the budget.",
      "Constructive waves: strong swash, a berm can build. Destructive waves: backwash wins, the cliff is cut. Longshore drift is the conveyor: angled swash, backwash down the steepest slope, sediment walking alongshore. A spit grows where the coast turns and the drift has somewhere to dump. Cave, arch, stack, stump is the headland’s life: joints exploited, roof fails, pillar stands, stump sits in the surf. Hydraulic action, abrasion, attrition, plus weathering from above. Holderness is glacial till — boulder clay, not lithified rock — so the sequence is fast enough to see in a school lifetime. Jurassic Coast headlands are harder rock; the sequence is the same, slower. Outer Banks: barrier sand, overwash, inlets; not a cliff, still a budget. Vertical exaggeration is labelled ×6 so cliff, berm, and headland stages read from the back of the room. Sand grains are not a grain-size model; the 3D scene is one chalk mass cut as cave, arch, stack and stump, with a water volume and a spit at the turn. Groynes and sea walls interrupt the conveyor; they do not cancel it. One landform, one process, no budget is the pitfall. Mappleton is the bargain: protection here, starvation there. Spurn is the depositional end-member, not immortal. A barrier island is not a permanent wall; storms punch inlets and the island can roll toward the mainland.",
      "Toggle Constructive waves on. Strong swash builds a berm. Toggle off: destructive, backwash wins, the till cliff is cut. Leave Longshore particles on; sediment walks alongshore in the direction of the angled swash. Freeze on the spit where the coast turns. Scrub Headland stage: cave, arch, stack, stump. Ask where a groyne would starve the spit. Keyboard: L labels, R reset. Vertical exaggeration is ×6 and labelled. Finish in Check. Mappleton groynes trap up-drift and can starve down-drift. Sea walls do not fix the whole coast.",
      "Without the 3D view: constructive waves build, destructive waves take, longshore drift is the conveyor, cave–arch–stack–stump is the headland’s life. Holderness till versus Outer Banks sand: same budget, different landform. Jurassic Coast is the harder-rock sequence. Sea walls move the problem along the budget. Vertical exaggeration is ×6 and labelled. Groynes are a bargain, not a cure. Spurn Head is a spit, not a promise. A barrier is not a permanent wall. Supply, transport, deposition, interruption: say the four words.",
    ],
    glossary: [
      { term: "Constructive wave", def: "Strong swash, weaker backwash. Can build a berm." },
      { term: "Destructive wave", def: "Backwash wins. Cuts the beach and attacks the cliff." },
      { term: "Longshore drift", def: "Alongshore transport by angled waves." },
      { term: "Spit", def: "Beach that grows out where the coast turns." },
      { term: "Stack", def: "Pillar left after an arch collapses." },
      { term: "Stump", def: "What remains in the surf after a stack fails." },
      { term: "Groyne", def: "A barrier across the beach that traps sediment up-drift and can starve down-drift." },
      { term: "Sediment budget", def: "Supply, transport, deposition, interruption. The whole-coast accounts." },
    ],
    misconception: { claim: "Sea walls fix the whole coast.", truth: "They move the problem along the budget." },
    misconceptions: [
      {
        claim: "Sea walls fix the whole coast.",
        truth: "They move the problem along the budget. Protection here, starvation there.",
      },
      {
        claim: "A stack is a spit.",
        truth: "A stack is an isolated pillar after an arch collapses. A spit is a beach that grows where the coast turns.",
      },
      {
        claim: "Holderness and the Outer Banks are the same landform.",
        truth: "Till cliff versus barrier sand. Shared budget: supply, transport, deposition, interruption.",
      },
    ],
    cases: [{ slug: "holderness", label: "Holderness" }, { slug: "outer-banks", label: "Outer Banks" }],
    teacher: {
      script:
        "Toggle Constructive waves on. Strong swash builds. Toggle off: destructive, backwash wins.\nLeave Longshore particles on. Sediment walks alongshore in the direction of the angled swash.\nFreeze on the spit. It grows where the coast turns.\nScrub Headland stage: cave, arch, stack, stump.\nA stack is an isolated pillar after an arch collapses.\nSea walls do not fix the whole coast. They move the problem along the budget.\nThat is the misconception.\nMappleton groynes trap sediment up-drift and can starve down-drift. Holderness is that bargain.\nJurassic Coast is the harder-rock sequence. Outer Banks are sand barriers, same budget idea.\nVertical exaggeration is ×6 and labelled. One landform, one process, no budget is the pitfall. Finish in Check.",
      pitfalls: [
        "One landform, one process, no budget.",
        "Calling a stack a spit, or a spit a stack.",
        "Teaching a sea wall as a whole-coast cure.",
      ],
    },
    sources: [{ label: "BGS Holderness" }, { label: "USGS barriers" }],
    controls: {
      time: "none",
      extra: [{ key: "stage", label: "Headland stage", min: 0, max: 3, step: 1, default: 1 }],
      toggles: [
        { key: "constructive", label: "Constructive waves", defaultOn: true },
        { key: "drift", label: "Longshore particles", defaultOn: true },
        { key: "groyne", label: "Groyne", defaultOn: false },
      ],
    },
  }),
  lab({
    slug: "glaciers",
    title: "Glacial landforms",
    hook: "Ice is a river that can be a kilometre thick. It leaves a cirque, an arête, a horn, a U, and a pile of till.",
    objective: "Name cirque, arête, horn, U-trough, moraines and play ice advance/retreat.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["GCSE AQA 3.1.3.3", "NGSS MS-ESS2-2"],
    steps: steps("Cirque armchair, arête knife, horn peak.", "Play ice: U-trough deepens. Moraines dump at the snout.", "Ice vs water: U vs V."),
    questions: [
      q("An arête is…", ["A spit", "A knife ridge between two cirques", "A delta", "A barchan"], 1, "Two cwms eating a ridge."),
      q("A horn is…", ["Three or more cirques eating a peak", "A stack", "A levée", "A sinkhole"], 0, "Pyramidal peak."),
      q("A U-shaped trough vs a V…", ["Same process", "Ice overdeepens a wide floor; rivers cut a V", "Wind", "Tides"], 1, "Yosemite vs a beck."),
      q("Yosemite Valley is mainly…", ["A river canyon like the Grand Canyon", "A glacial U-trough in granite", "A limestone pavement", "A barchan field"], 1, "Ice in granite. Grand Canyon is a river in a plateau. Cross-profile tells them apart."),
    ],
    why: [
      "Ice is a river that can be a kilometre thick. It leaves a cirque, an arête, a horn, a U, and a pile of till. The Lake District and Snowdonia are the UK pair: Helvellyn’s Red Tarn, Striding Edge, Crib Goch, cwms eating a ridge. Yosemite is the US pair: a deeper U in granite, hanging valleys, Half Dome, moraines down-valley. Same ice logic, different rock and a different poster. GCSE AQA 3.1.3.3 and NGSS MS-ESS2-2 both need U versus V, and the honesty that Yosemite is not a river canyon like the Grand Canyon. Glaciers exist where snow survives the year — latitude and altitude — not only at the poles. A UK upland trough with a beck in the floor is ice first, water second.",
      "A cirque (cwm, corrie) is an armchair hollow with a steep backwall. Two cirques eating a ridge leave an arête, a knife. Three or more eating a peak leave a horn, a pyramidal peak. Ice overdeepens a wide floor: a U-trough, truncated spurs, hanging valleys that dump waterfalls. Till is dumped as moraines — lateral, medial, terminal — at the ice margin. A drumlin is a streamlined till hill. Play advance: the tongue thickens and the U deepens. Play retreat: the snout dumps the pile. Ice versus water is U versus V. Yosemite is ice in granite; the Grand Canyon is a river in a plateau; do not swap the names. Vertical exaggeration is labelled ×6. Ice has thickness; it is not a white sticker on a hill. The tongue is a classroom glacier, not a traced ice stream. Lake District ice is mostly gone; the landforms remain. Yosemite’s glaciers are remnants; the valley is the scar. Glaciers are not only polar. They exist where snow survives the year. Abrasion and plucking do the cutting; freeze–thaw helps the backwall. A hanging valley is a tributary trough left high when the trunk ice overdeepened. That is why Yosemite Falls start in mid-air.",
      "Labels off. Name cirque, arête, horn before you reveal. Cirque is the armchair. Arête is the knife between two cirques. Horn is three or more eating a peak. Advance the ice; the U-trough deepens. Retreat to the snout; moraines dump till. Keyboard: space, arrows, L labels, R reset. Vertical exaggeration is ×6; ice is thick, not a sticker. Till is the pile. The landform names are the scar. Finish in Check. Yosemite is not a river canyon like the Grand Canyon. Lake District and Yosemite are the pair.",
      "Without the 3D view: ice is a thick river. Cirque armchair, arête knife, horn peak, U-trough, moraine pile. Ice versus water is U versus V. Lake District and Yosemite are the pair. Snowdonia’s Crib Goch is an arête you remember with your hands. Glaciers exist where snow survives the year, not only at the poles. Vertical exaggeration is ×6 and labelled. Ice has thickness. Do not call Yosemite a river canyon like the Grand Canyon. Till is the pile; the names are the scar.",
    ],
    glossary: [
      { term: "Cirque", exam: "Cwm / corrie", def: "Armchair hollow with a steep backwall." },
      { term: "Arête", def: "Knife ridge between cirques." },
      { term: "Horn", def: "Pyramidal peak eaten by three or more cirques." },
      { term: "U-trough", exam: "Glacial trough", def: "Wide floor and steep walls overdeepened by ice." },
      { term: "Moraine", def: "Till ridge dumped by ice at the margin." },
      { term: "Till", def: "Unsorted debris dropped by ice. The pile." },
      { term: "Hanging valley", def: "A tributary trough left high when the trunk ice overdeepened." },
      { term: "Drumlin", def: "Streamlined till hill, blunt up-ice, tapered down-ice." },
    ],
    misconception: { claim: "Glaciers only exist at the poles.", truth: "They exist where snow survives the year. Latitude and altitude." },
    misconceptions: [
      {
        claim: "Glaciers only exist at the poles.",
        truth: "They exist where snow survives the year. Latitude and altitude.",
      },
      {
        claim: "Yosemite is a river canyon like the Grand Canyon.",
        truth: "Yosemite is ice in granite — a U. Grand Canyon is a river in a plateau. Cross-profile tells them apart.",
      },
      {
        claim: "Ice is a white sticker on a hill.",
        truth: "Ice is a thick river. It has thickness. Vertical exaggeration here is ×6 and labelled.",
      },
    ],
    cases: [{ slug: "lake-district", label: "Lake District" }, { slug: "yosemite", label: "Yosemite" }],
    teacher: {
      script:
        "Labels off. Name cirque, arête, horn before you reveal.\nCirque is the armchair. Arête is the knife between two cirques. Horn is three or more eating a peak.\nAdvance the ice. The U-trough deepens.\nRetreat to the snout. Moraines dump till.\nIce versus water: U versus V. Yosemite is not a river canyon like the Grand Canyon.\nGlaciers do not only exist at the poles. They exist where snow survives the year.\nLatitude and altitude. That is the misconception.\nLake District and Yosemite are the pair. Snowdonia’s Crib Goch is an arête you remember with your hands.\nVertical exaggeration is ×6. Ice has thickness; it is not a white sticker.\nTill is the pile. The landform names are the scar. Finish in Check.",
      pitfalls: [
        "Calling Yosemite a river canyon like the Grand Canyon.",
        "Teaching glaciers as polar-only.",
        "Drawing ice as a white sticker with no thickness.",
      ],
    },
    sources: [{ label: "BGS glaciation" }, { label: "NPS Yosemite" }],
    controls: { time: "none" },
  }),
  lab({
    slug: "karst",
    title: "Karst",
    hook: "Limestone does not just break. It dissolves along joints: pavement, swallow hole, cave.",
    objective: "Read clints and grykes, a sinkhole, and a cave passage.",
    realm: "landforms",
    ages: ["KS3", "GCSE", "A-level"],
    curriculum: ["GCSE", "A-level carbonation"],
    steps: steps("Pavement: clints and grykes.", "A stream swallows. Toggle the cutaway cave.", "Carbonation plus joints. Granite does not do this."),
    questions: [
      q("Grykes are…", ["Sand dunes", "Dissolved fissures between clints on a limestone pavement", "Moraines", "Spits"], 1, "Joints widened."),
      q("A swallow hole…", ["A stack", "Where a surface stream sinks underground", "A volcano", "A time zone"], 1, "Gaping Gill is the UK poster."),
      q("Karst clusters on carbonate rocks because…", ["They are magnetic", "Carbonation of CaCO₃ along joints", "They never joint", "Wind only"], 1, "Chemistry."),
      q("The caves in this lab are…", ["Lava tubes", "Solution caves in carbonate", "Glacial tunnels only", "Faults pulled open"], 1, "Carbonation, not magma. Granite does not do this."),
    ],
    why: [
      "Limestone does not just break. It dissolves along joints: pavement, swallow hole, cave. The Yorkshire Dales are the UK classroom — Malham Cove’s clints and grykes, Gaping Gill taking Fell Beck underground, a resurgence kilometres away. Mammoth Cave, Kentucky, is the US pair: a long, lower-gradient carbonate system in Mississippian limestone, sinkholes on the Chester Upland, the same chemistry at a different map scale. GCSE and A-level carbonation both need that sequence. Soil is thin. Farmers talk limestone in the same breath as drainage. Students who think caves are lava tubes, or that every hole is a volcano, will misread both Malham and Mammoth. Granite does not do this. Chemistry, not magnetism. A surface watershed on limestone may not match the cave.",
      "Rainwater picks up carbon dioxide and becomes a weak carbonic acid. It works on calcium carbonate along bedding and joints. The surface becomes a limestone pavement: clints are the blocks, grykes the dissolved fissures. A stream that meets a swallow hole (sinkhole, doline) leaves the surface and may return as a resurgence. Cave passages follow joints and bedding; stalactites need a drip with time. Carbonation plus joints is the machine. Granite does not dissolve that way; these are solution caves in carbonate, not lava tubes. Toggle the cutaway and the chamber appears under the doline. Vertical exaggeration is labelled ×6 so pavement, grykes, and the doline cone read from the back of the room. True grykes on a table would be scratches. The pavement is a schematic block, not a traced Malham sheet. Gaping Gill is the UK poster for a swallow. Mammoth Cave is the long US system. Karst clusters on carbonate rocks because of chemistry. Sequence it: rainfall, carbonation, widened joints, swallow hole, cave passage, then a stalactite if the drip has time. Gordale Scar is a different argument — a gorge, possibly collapse or meltwater — still useful, still not a volcano.",
      "Pavement first. Clints are the blocks. Grykes are the dissolved fissures between them. A stream swallows — that is the swallow hole, where drainage leaves the surface. Toggle Cave cutaway on. A passage in carbonate, not a lava tube. Keyboard: L labels, R reset. Vertical exaggeration is ×6 and labelled. Granite does not do this. Say so. Finish in Check. Yorkshire Dales pavement and Mammoth Cave are the pair. Every hole is not a volcano. Gaping Gill is the UK poster for a swallow.",
      "Without the 3D view: carbonation of limestone along joints makes pavement, swallow holes, and solution caves. Clints and grykes. A swallow is where a stream leaves the surface. These are not lava tubes. Granite does not do this. Yorkshire Dales and Mammoth Cave are the pair. Vertical exaggeration is ×6 and labelled. Chemistry, not magnetism. Gaping Gill is the UK poster. A surface divide on karst may not match the cave beneath. Sequence rainfall to stalactite if you have time.",
    ],
    glossary: [
      { term: "Limestone pavement", def: "Clints and grykes on a bare carbonate surface." },
      { term: "Clint", def: "The block on a limestone pavement." },
      { term: "Gryke", exam: "Grike", def: "Dissolved fissure between clints." },
      { term: "Swallow hole", exam: "Sinkhole / doline", def: "Point where drainage leaves the surface." },
      { term: "Carbonation", def: "Weak carbonic acid working on calcium carbonate." },
      { term: "Resurgence", def: "Where underground drainage returns to the surface." },
      { term: "Stalactite", def: "Dripstone growing down from a cave roof, if the drip has time." },
    ],
    misconception: { claim: "Caves are lava tubes.", truth: "These are solution caves in carbonate." },
    misconceptions: [
      {
        claim: "Caves are lava tubes.",
        truth: "These are solution caves in carbonate. Carbonation along joints.",
      },
      {
        claim: "Every hole is a volcano.",
        truth: "A swallow hole is where a stream leaves the surface on limestone. Not magma.",
      },
      {
        claim: "Granite does this too if it rains hard enough.",
        truth: "Karst clusters on carbonate rocks because of chemistry, not rainfall volume alone.",
      },
    ],
    cases: [{ slug: "yorkshire-dales", label: "Yorkshire Dales" }, { slug: "mammoth-cave", label: "Mammoth Cave" }],
    teacher: {
      script:
        "Pavement first. Clints are the blocks. Grykes are the dissolved fissures between them.\nA stream swallows. That is the swallow hole, where drainage leaves the surface.\nToggle Cave cutaway on. A passage in carbonate, not a lava tube.\nThese are solution caves. Carbonation of calcium carbonate along joints.\nGranite does not do this. Every hole is not a volcano.\nThat is the misconception, plus the lava-tube mix-up.\nKarst clusters on carbonate rocks because of chemistry, not magnetism.\nYorkshire Dales pavement and Mammoth Cave are the pair.\nGaping Gill is the UK poster for a swallow. Vertical exaggeration is ×6 and labelled.\nFinish in Check.",
      pitfalls: [
        "Every hole is a volcano.",
        "Calling solution caves lava tubes.",
        "Teaching granite as a karst rock.",
      ],
    },
    sources: [{ label: "BGS karst" }, { label: "NPS Mammoth Cave" }],
    controls: { time: "none", toggles: [{ key: "cutaway", label: "Cave cutaway" }] },
  }),
  lab({
    slug: "folds-faults",
    title: "Folds and faults",
    hook: "Rocks bend or they break. Anticline, syncline, then the three fault slips.",
    objective: "Identify anticline, syncline, normal, reverse, and strike-slip, and explode the blocks.",
    realm: "interior",
    ages: ["GCSE", "A-level", "NGSS MS", "HS Earth Sci"],
    curriculum: ["GCSE AQA 3.1.1", "NGSS MS-ESS2-2"],
    steps: steps("Anticline up, syncline down.", "Explode. Normal (extension), reverse (shortening), strike-slip (San Andreas).", "Inversion can lift an old basin."),
    questions: [
      q("An anticline is…", ["A downfold", "An upfold; oldest rocks in the core", "A spit", "A cell"], 1, "A-shape."),
      q("A normal fault forms in…", ["Compression", "Extension; hanging wall down", "Only ice", "Only granite"], 1, "Stretch."),
      q("San Andreas is…", ["Normal", "Reverse", "Strike-slip (transform)", "A fold only"], 2, "Slide past."),
      q("The hanging wall is…", ["Always the downthrown block", "The block above the fault plane", "A cliff of till", "Only found in folds"], 1, "Above the plane. Footwall is below. Get the names right before the arrows."),
    ],
    why: [
      "Rocks bend or they break. Jurassic Coast folds — Lulworth, the crumpled beds in the cliffs — are the UK locator: anticline up, syncline down, in sedimentary sequence you can walk. San Andreas is the US locator for strike-slip: Pacific plate northwest, North American plate southeast, fences offset, no volcano chain. GCSE AQA 3.1.1 and NGSS MS-ESS2-2 both need two folds and three fault slips. Inversion can lift an old basin. Students who think folds only happen in soft clay, or who mix hanging wall with footwall, will misread both a Dorset cliff and a Californian fence. Given time and depth, rock flows. Then it may still break. Cascadia to the north of San Andreas is a different boundary and a different volcano story.",
      "An anticline is an upfold, oldest rocks in the core, A-shape. A syncline is a downfold. Normal fault: extension, hanging wall down. Reverse (and thrust): shortening, hanging wall up. Strike-slip: horizontal slip, transform cousin — San Andreas is the named slide. Hanging wall is the block above the fault plane; footwall is below. Get the names right before the arrows. Explode the blocks so the slip reads from the back of the room: the gap is labelled teaching, not a canyon. Beds in this lab are a sine fold of sandstone, limestone, shale, greywacke, basalt — a schematic stack, not a traced Lulworth log. Folds are not only for soft clay. Given time and depth, rock flows; then it may still break. Inversion can lift an old basin into a high. Jurassic Coast folds are the walkable UK pair. San Andreas is strike-slip, not a fold only, and not Cascadia’s subduction. Three fault slips, two folds, one explode control. The explode gap is the honesty caption: we pull the walls apart so the class can see hanging wall versus footwall. Real faults are not that open. Colour of the beds is a legend, not a law of lithology.",
      "Name the fold. Anticline up, oldest in the core. Syncline down. Explode the blocks. Normal: hanging wall down. Reverse: hanging wall up. Strike-slip: lateral. Point at the San Andreas colour and say transform cousin, slide past. Keyboard: E explode, L labels, R reset. Hanging wall versus footwall: get the names right before the arrows. Folds are not only for soft clay. Inversion can lift an old basin. Use the explode control. Finish in Check. Jurassic Coast folds are the other locator.",
      "Without the 3D view: rocks bend or they break. Anticline up, syncline down. Normal in extension (hanging wall down), reverse in shortening (hanging wall up), strike-slip sideways. San Andreas is strike-slip. Jurassic Coast folds are the UK walk. Exploded blocks are a labelled teaching gap, not a canyon. Folds can happen in hard rock given time and depth. Then rock may still break. Inversion can lift an old basin. Get hanging wall and footwall right before the arrows. Three fault slips, two folds. Cascadia is not this machine.",
    ],
    glossary: [
      { term: "Anticline", def: "Upfold. Oldest rocks in the core." },
      { term: "Syncline", def: "Downfold." },
      { term: "Normal fault", def: "Extension. Hanging wall down." },
      { term: "Reverse fault", def: "Shortening. Hanging wall up. Thrust if the plane is gentle." },
      { term: "Strike-slip", def: "Horizontal slip. Transform cousin." },
      { term: "Hanging wall", def: "The block above the fault plane." },
      { term: "Footwall", def: "The block below the fault plane." },
      { term: "Inversion", def: "An old basin later lifted, so low becomes high." },
    ],
    misconception: { claim: "Folds only happen in soft clay.", truth: "Given time and depth, rock flows. Then it may still break." },
    misconceptions: [
      {
        claim: "Folds only happen in soft clay.",
        truth: "Given time and depth, rock flows. Then it may still break.",
      },
      {
        claim: "The hanging wall is always the downthrown side.",
        truth: "Hanging wall is the block above the plane. It goes down in a normal fault, up in a reverse fault.",
      },
      {
        claim: "San Andreas is a fold, or a subduction zone like Cascadia.",
        truth: "It is strike-slip. Cascadia to the north is the subduction zone.",
      },
    ],
    cases: [{ slug: "san-andreas", label: "San Andreas" }, { slug: "jurassic-coast", label: "Jurassic Coast folds" }],
    teacher: {
      script:
        "Name the fold. Anticline up, oldest in the core. Syncline down.\nFolds are not only for soft clay. Given time and depth, rock flows. Then it may still break.\nThat is the misconception.\nExplode the blocks. Normal fault: extension, hanging wall down.\nReverse: shortening, hanging wall up. Strike-slip: horizontal slip.\nPoint at the San Andreas colour. Transform cousin, slide past. Not Cascadia.\nHanging wall versus footwall: get the names right before the arrows.\nInversion can lift an old basin. Jurassic Coast folds are the other locator.\nThe explode gap is labelled teaching, not a canyon. Real faults are not that open.\nThree fault slips, two folds, one explode control. Use it. Finish in Check.",
      pitfalls: [
        "Hanging wall vs footwall mix-up.",
        "Teaching folds as clay-only.",
        "Colouring San Andreas as Cascadia’s subduction.",
      ],
    },
    sources: [{ label: "USGS faults" }, { label: "BGS structure" }],
    controls: { time: "none", explode: true },
  }),
  lab({
    slug: "aeolian",
    title: "Wind landforms",
    hook: "Yardangs are carved. Barchans are built. Wind is a sculptor where vegetation is thin.",
    objective: "Orbit a yardang ridge and a barchan, and play sand along the horns.",
    realm: "landforms",
    ages: ["GCSE", "A-level", "NGSS MS"],
    curriculum: ["A-level", "NGSS MS-ESS2-2"],
    steps: steps("Yardang: streamlined ridge, wind-parallel.", "Barchan: crescent, horns downwind.", "World examples, not a single-country exam core."),
    questions: [
      q("A barchan’s horns point…", ["Upwind", "Downwind", "Always north", "To the sea only"], 1, "Crescent; horns downwind."),
      q("A yardang is…", ["A spit", "A wind-carved ridge", "A moraine", "A meander"], 1, "Erosional."),
      q("Aeolian work needs…", ["A rainforest canopy", "Loose sediment and enough wind, often sparse vegetation", "A glacier always", "Tides"], 1, "Dust Bowl was land use plus drought plus wind."),
      q("The Dust Bowl’s headline process was…", ["A barchan dune sea covering the plains", "Deflation of a bare A horizon after plough and drought", "A lava tube", "Nick-point retreat"], 1, "Land use plus drought plus wind. Not a textbook erg as the default landform."),
    ],
    why: [
      "Yardangs are carved. Barchans are built. Wind is a sculptor where vegetation is thin. The Dust Bowl is the process without needing a Chinese exam map as the hero: 1930s Great Plains, a plough, a drought, a wind that took the A horizon off the prairie. Deflation and transport of farmed silt, not a textbook dune sea. Grand Canyon country is dryland weathering and wind on rock and pavement as much as sand. UK blown sand on some coasts and bare peat in a dry spring are the small cousins. GCSE is light here; A-level and NGSS MS-ESS2-2 still need carved versus built, and the honesty that many deserts are rock. Dunes need a sand supply. Land use plus drought plus wind is the Dust Bowl sentence, not a morality play.",
      "A yardang is a streamlined wind-eroded ridge, wind-parallel — carved. A barchan is a crescent dune, horns pointing downwind — built. Play the lab and sand walks along the horns; the crescent migrates downwind. Aeolian work needs loose sediment and enough wind, often sparse vegetation. All deserts are not dune seas. Many are rock and pavement. Dunes need a sand supply. Dust Bowl was land use plus drought plus wind, deflation of an A horizon, not a barchan field as the default landform. Yardangs and barchans are the world-example kit. Vertical exaggeration is labelled ×8 so the carved ridges and the built crescents read from the back of the room. True dune relief on a table would be a film of sand. The dunes are a schematic pair, not a traced erg. Horns point downwind, not upwind, not always north. Carved versus built. Say the pair. A nabkha is sand trapped at a plant; that is vegetation as roughness, the opposite of a bare Dust Bowl field. Wind direction is the arrow in this lab. Saltation hops grains; suspension takes dust. The 1930s black blizzards were suspension of farmed silt, not a yardang lesson first.",
      "Orbit the yardang. It is a wind-carved ridge, streamlined, wind-parallel. Then the barchan: a crescent, horns downwind. Carved versus built. Say the pair out loud. Play sand along the horns and watch the crescent migrate. Keyboard: space, arrows, L labels, R reset. Vertical exaggeration is ×8 and labelled. This is not the homepage special effect. Keep it as a process. Finish in Check. All deserts are not dune seas. Dust Bowl was land use plus drought plus wind, not a dune-sea poster.",
      "Without the 3D view: yardangs are carved, barchans are built, horns point downwind. Aeolian work needs loose sediment, wind, and often thin vegetation. Many deserts are rock and pavement; dunes need a sand supply. Dust Bowl was land use plus drought plus wind, not a dune-sea poster. Vertical exaggeration is ×8 and labelled. This is a process, not a homepage special effect. Grand Canyon dryland is rock and pavement as much as sand. Horns are not a compass. Carved versus built. Say the pair. Vegetation is roughness.",
    ],
    glossary: [
      { term: "Yardang", def: "Streamlined wind-eroded ridge, wind-parallel. Carved." },
      { term: "Barchan", def: "Crescent dune, horns downwind. Built." },
      { term: "Deflation", def: "Wind lifting and removing loose particles from a surface." },
      { term: "Saltation", def: "Grains hopping in the near-surface wind." },
      { term: "Suspension", def: "Fine dust carried high. Dust Bowl black blizzards." },
      { term: "Nabkha", def: "Sand trapped at a plant. Vegetation as roughness." },
      { term: "Erg", def: "A sand sea. Needs a sand supply. Not every desert." },
    ],
    misconception: { claim: "All deserts are dune seas.", truth: "Many are rock and pavement. Dunes need a sand supply." },
    misconceptions: [
      {
        claim: "All deserts are dune seas.",
        truth: "Many are rock and pavement. Dunes need a sand supply.",
      },
      {
        claim: "A barchan’s horns point upwind.",
        truth: "Horns point downwind. The crescent migrates that way.",
      },
      {
        claim: "The Dust Bowl was a textbook barchan field.",
        truth: "It was land use plus drought plus wind: deflation of a farmed A horizon, not an erg as the default landform.",
      },
    ],
    cases: [{ slug: "dust-bowl", label: "Dust Bowl" }, { slug: "grand-canyon", label: "Dryland weathering" }],
    teacher: {
      script:
        "Orbit the yardang. It is a wind-carved ridge, streamlined, wind-parallel.\nThen the barchan. It is built: a crescent, horns downwind.\nCarved versus built. Say the pair.\nPlay sand along the horns. Horns point downwind, not upwind.\nAll deserts are not dune seas. Many are rock and pavement. Dunes need a sand supply.\nThat is the misconception.\nAeolian work needs loose sediment and enough wind, often sparse vegetation.\nDust Bowl was land use plus drought plus wind, not a single-country exam map as the hero.\nVertical exaggeration is ×8 and labelled. This is not the homepage special effect. Keep it as a process.\nFinish in Check.",
      pitfalls: [
        "Making this the homepage hero.",
        "Teaching every desert as a dune sea.",
        "Pointing barchan horns upwind.",
      ],
    },
    sources: [{ label: "USGS dunes" }, { label: "NOAA Dust Bowl" }],
    controls: { time: "none" },
  }),
];
