import type { LabMeta } from "./types";
import { lab, q, steps, mc } from "./make";

export const PLANET_LABS: LabMeta[] = [
  lab({
    slug: "solar-system",
    title: "Solar system",
    hook: "Eight planets, one star. Distances are the lie a classroom model always tells — we exaggerate so you can see them.",
    objective: "Name the eight planets, compare orbital periods, and treat size as labelled exaggeration.",
    realm: "planet",
    ages: ["KS3", "NGSS MS"],
    curriculum: ["KS3 Earth and atmosphere", "NGSS MS-ESS1-2", "GCSE background"],
    steps: steps("Play a year. Inner planets lap the outer.", "Pause on Saturn’s ring and Jupiter’s size.", "Periods lengthen with distance. Sizes here are not to scale with orbits."),
    questions: [
      q("Which planet orbits fastest?", ["Neptune", "Mercury", "Jupiter", "Earth"], 1, "Kepler: closer, faster. Mercury."),
      q("Saturn is famous in this lab for…", ["Liquid water oceans on the surface", "A ring you can orbit", "Being the closest to the Sun", "Having no orbit"], 1, "Ice and rock ring. Size exaggerated."),
      q("Why exaggerate planet size?", ["To lie about science", "So the set reads from the back of the room; teacher notes flag it", "NASA asked", "Because orbits are square"], 1, "Honesty in the pitfall list."),
      q("If I turn True distance on, what happens?", ["Planets swell until they fill the orbits", "Orbits stretch toward AU and planets shrink toward dust", "The Sun vanishes and astrology begins", "Mercury and Neptune swap periods"], 1, "Two scales cannot both be true on one table. Visible mode is the classroom lie; True distance is the other one."),
    ],
    why: [
      "A London planetarium kit parks Jupiter beside Mars on a table. A night sky over Miami does not. Distances are the first lie every classroom model tells, and this lab names it. Greenwich treats Earth as a labelled planet, not a special case. The same star that lights a Holderness beach lights Hawaii. Eight names. Two families: rock, then gas and ice. A ring you can point at from the back row. Scale literacy is the skill. If you cannot say which number is size and which is orbit, you cannot read a NASA poster, a GCSE diagram, or a news graphic that sits Saturn next to Earth. Fieldwork does not need the plastic kit. It needs one sentence: closer planets lap the outer ones; periods lengthen with distance; sizes on the table are not the same lie as the gaps. That sentence travels from Leeds to a Florida pier without changing.",
      "Input is time: one school year on the slider. The Sun sits still. Eight planets run their rings. Mercury, Venus, Earth, Mars lap the outer four. Jupiter, Saturn, Uranus, Neptune take longer because they are farther, not because this lab plots mass as the clock. What moves: position on the orbit. What does not: the order of the eight, the Sun’s place at the centre of this set, the fact of closed paths. What is conserved: Kepler’s bargain — closer, faster. Period squared with distance cubed, in school language. Toggle True distance and the set tells a different honesty. Orbits stretch toward astronomical units. Planets shrink toward dust. You cannot keep both size and orbit honest on one table. That is the lie visible mode tells on purpose, so the back row can still name Saturn’s ring. The ring is ice and rock, drawn fat. The Sun is a ball you can see, not a 109-Earth-diameter monster at a true gap. Periods stay true-ish: Mercury about 88 days, Earth a year, Neptune about 165 years. Astrology is not in the room. Size is not orbit scale. If the orbits were true and the planets were true, you would need a field, not a screen.",
      "Play a year. Space toggles play. Arrows nudge time. Speed is 1×, 2×, or 4× on the bar. Toggle True distance: classroom set versus compressed AU. L labels. R reset. P projector. No explode, no slice. Pause on Saturn’s ring. Pause on Mercury lapping Earth. Reset if the class has lost the inner four. The year slider is the orbit clock. Names are the point. The toggle is the honesty. Leave True distance off for the back row, then on once so they hear the dust sentence.",
      "If the model will not spin, keep the sentences. Eight planets, one star. Inner four are rock. Outer four are gas and ice giants. Closer orbits are faster. Sizes in a kit are exaggerated so you can see them. True orbits would leave planets as dust. Saturn has a ring of ice and rock. Neptune takes far longer than Earth. Pluto is not on this table. That is enough to sit Check without WebGL, and enough to catch a poster that pretends two scales at once.",
    ],
    glossary: [
      { term: "Orbital period", def: "Time for one trip around the Sun. Mercury ~88 days. Earth 1 year. Neptune ~165 years." },
      { term: "Terrestrial planet", exam: "Rocky planet", def: "Mercury, Venus, Earth, Mars: rock and metal, close in." },
      { term: "Gas giant", def: "Jupiter and Saturn: thick hydrogen–helium envelopes. Not small rocky worlds with weather like ours." },
      { term: "Ice giant", def: "Uranus and Neptune: ices of water, ammonia, methane over a denser interior. Farther and slower than the gas giants." },
      { term: "Astronomical unit", exam: "AU", def: "Earth–Sun distance, about 150 million km. The school unit for the inner system." },
      { term: "Kepler’s third law", def: "Closer orbits are faster. Period squared scales with distance cubed. This lab shows the qualitative half." },
      { term: "True scale", def: "A mode where distances lean toward AU and planets shrink toward dust. Still compressed. Still a lie, just a different one." },
      { term: "Planetary ring", def: "Ice and rock in orbit, here Saturn’s. Drawn fat so the back row can see it. Not a solid disc." },
    ],
    misconception: { claim: "The model on the table is to scale.", truth: "If orbits were to scale, planets would be dust." },
    misconceptions: [
      mc("The model on the table is to scale.", "If orbits were to scale, planets would be dust."),
      mc("Pluto should be on this table as a planet.", "Eight planets. Pluto is a dwarf planet. This lab does not park it in the set."),
      mc("The outer planets take longer because they are bigger.", "Period follows distance, not girth. Kepler: closer, faster. Neptune is slow because it is far."),
    ],
    cases: [{ slug: "greenwich", label: "Earth as a labelled planet" }, { slug: "florida-insolation", label: "Insolation starts at the Sun" }],
    teacher: {
      script:
        "Play a year. Name the inner four, then the gas giants, then the ice giants.\nSaturn’s ring is ice and rock, size exaggerated. Say that before anyone calls it a solid disc.\nToggle True distance. Planets become dust. That is the honest sentence.\nToggle back to visible mode so the set reads from the back row.\nPeriods lengthen with distance. Kepler, not astrology.\nAsk which planet laps Earth first. Mercury.\nAsk why Neptune is slow. Distance, not bulk.\nPluto is not on this table. Do not apologise for that.\nTwo scales cannot both be true in one plastic kit.\nFinish in Check.",
      pitfalls: [
        "Astrology dressed as orbital period.",
        "Treating size and orbit as one scale.",
        "Parking Pluto as a ninth planet in this set.",
        "Calling Saturn’s ring a solid disc.",
      ],
    },
    sources: [{ label: "NASA solar system" }],
    controls: { time: "year", toggles: [{ key: "trueScale", label: "True distance" }] },
  }),
  lab({
    slug: "sun-earth",
    title: "Sun and Earth",
    hook: "The solar constant is a number. Latitude is why a playground in London and one in Nairobi disagree.",
    objective: "Link solar constant, insolation by latitude, and sunspots as a school-level activity toggle — not astrology.",
    realm: "planet",
    ages: ["KS3", "GCSE", "NGSS MS", "APES"],
    curriculum: ["KS3", "NGSS MS-ESS1-1", "APES 4.7"],
    steps: steps("Beam hits a globe. Bars of insolation by latitude.", "Toggle sunspots — a magnetic blemish, not a weather spell.", "Same solar constant; different incidence."),
    questions: [
      q("The solar constant is measured…", ["At Earth’s surface always", "At the top of the atmosphere, ~1366 W m⁻², a school figure", "Only at night", "In the core of Earth"], 1, "Surface gets less. Atmosphere and angle."),
      q("Insolation at the poles is low mainly because…", ["The Sun is farther in kilometres that matter", "The beam is oblique and, in winter, absent", "There is no atmosphere", "Time zones"], 1, "Geometry."),
      q("Sunspots are…", ["Holes to another universe", "Cooler, magnetically active patches; they do not run the seasons", "The cause of tides", "Clouds"], 1, "Toggle, not astrology."),
      q("If I toggle Sunspots on, what happens to a London December playground?", ["It goes dark because spots block the beam.", "Almost nothing you can feel. Spots are a small, separate story. Latitude and tilt still run the season.", "The solar constant doubles.", "Miami freezes and London becomes tropical."], 1, "The toggle is honesty, not weather magic. Incidence by latitude is the plot."),
    ],
    why: [
      "A playground in London and one in Nairobi disagree at noon. Same star. Same solar constant at the top of the atmosphere. Different incidence. Miami in December still takes a high beam; Leeds does not. That is this lab plus tilt, not a farther Sun in kilometres that matter. UK glasshouses plot hours above a useful angle. Florida growers plot the same number with a different latitude. Snowdonia fieldwork in June is long light on a steep slope. Holderness in December is a low, weak punch on wet till. The skill is to separate the constant from the geometry. If you mix them, you will blame sunspots for winter, or blame distance for the poles. Neither is the story. The beam is the story. The bars by latitude are the story. Seasons are a tilt lab. This one is the punch the tilt then aims.",
      "Input is the solar beam. The school figure is about 1366 W m⁻² at 1 AU, top of atmosphere. That number does not change with latitude. What changes is incidence: how oblique the beam is when it meets a patch of ground. Equator bars stand tall. Polar bars sit low, and in winter they vanish. What moves: the globe’s face, the height of the bars, the season’s aiming if you let time walk. What does not: the solar constant as a top-of-atmosphere number, the fact of a beam, the order of the latitudes. What is conserved: energy in the beam before atmosphere and angle take a cut. Surface flux is less. Always. Sunspots are cooler, magnetically active patches on the photosphere. Toggle them. They do not run the seasons. They do not dim a London playground in any way this lab will let you claim. The lie the model tells: the Sun is a nearby ball, Earth is huge beside it, bars are lollipops stuck on a globe. The constant is true-ish. The geometry of incidence is the lesson. Astrology is not invited. Distance to the poles is not the mechanism.",
      "There is no year slider in the bar. Space still turns the globe. Arrows nudge it. Toggle Sunspots on, then off, so the class hears they are not the season. L labels. R reset. P projector. No explode, no slice. Point at the bars: equator, 55°N playground, pole. Pause. Ask which bar is London in December before you name it. The beam is the plot. The toggle is a warning label. Leave spots off when you want the bars to stay the story.",
      "If the globe will not spin, keep the sentences. Solar constant: about 1366 W m⁻² at the top of the atmosphere, a school figure. Surface gets less. Poles are cold mainly because the beam is oblique, not because the Sun is farther in kilometres that matter. A London playground and a Nairobi playground disagree by latitude. Sunspots are magnetic blemishes, not winter. Seasons are tilt. This lab is the beam. That is enough for Check on paper, and enough to kill a sunspot scare story in one line.",
    ],
    glossary: [
      { term: "Solar constant", exam: "Total solar irradiance (school figure)", def: "Solar flux at 1 AU, top of atmosphere. School figure ~1366 W m⁻². Not the flux on a playground." },
      { term: "Insolation", exam: "Incoming solar radiation", def: "Incoming solar radiation at a surface. Incidence and atmosphere both cut it." },
      { term: "Incidence", def: "How steeply the beam meets the ground. Oblique at high latitude. Overhead only between the tropics, and not every day." },
      { term: "Sunspot", def: "A cooler, magnetically active patch on the photosphere. A school toggle. Not the cause of seasons." },
      { term: "Top of atmosphere", exam: "TOA", def: "Where the solar constant is defined. Below that, air and angle take a cut." },
      { term: "Latitude", def: "Angle from the equator. It sets how oblique the noon beam is, before tilt aims the season." },
      { term: "Photosphere", def: "The Sun’s visible surface. Spots live here. It is not a hole, and it is not weather." },
    ],
    misconception: { claim: "Sunspots cause seasons.", truth: "Tilt causes seasons. Sunspots are a small, separate story." },
    misconceptions: [
      mc("Sunspots cause seasons.", "Tilt causes seasons. Sunspots are a small, separate story."),
      mc("The poles are cold because they are farther from the Sun in kilometres that matter.", "The extra distance is tiny next to 1 AU. The beam is oblique. That is the cut."),
      mc("The solar constant is what hits a London playground.", "The constant is top of atmosphere. Surface flux is less: air and angle both take a share."),
    ],
    cases: [{ slug: "uk-daylength", label: "UK day length" }, { slug: "florida-insolation", label: "Florida insolation" }],
    teacher: {
      script:
        "Point at the bars of insolation by latitude. Equator high, poles low.\nThat is incidence, not a farther Sun in kilometres that matter.\nThe solar constant is about 1366 W m⁻² at the top of the atmosphere, a school figure.\nSurface flux is less: atmosphere and angle both take a cut.\nToggle Sunspots on. They are cooler, magnetically active patches.\nThey do not run the seasons. Say that out loud.\nToggle them off again so the bars stay the story.\nA playground in London and one in Nairobi disagree because of latitude, not sunspots.\nSeasons are a tilt lab. This lab is the beam.\nFinish in Check.",
      pitfalls: [
        "Sunspot scare stories as weather or seasons.",
        "Saying the poles are farther from the Sun in kilometres that matter.",
        "Treating 1366 W m⁻² as playground flux.",
      ],
    },
    sources: [{ label: "NASA / NOAA solar" }],
    controls: { time: "none", toggles: [{ key: "spots", label: "Sunspots" }] },
  }),
  lab({
    slug: "universe-scale",
    title: "Universe scale",
    hook: "Powers of ten: Earth, then the system, then the local star field. Keep it short. You cannot see a galaxy in one glance honestly.",
    objective: "Step Earth → orbit → neighbouring stars and say what each jump does to size.",
    realm: "planet",
    ages: ["KS3", "NGSS MS"],
    curriculum: ["KS3", "NGSS MS-ESS1-2"],
    steps: steps("Earth.", "Scrub scale out to the solar system.", "Then a local star dusting. Stop. No cartoon universe tour."),
    questions: [
      q("If Earth is a pea, the Sun is roughly…", ["Another pea next to it", "A much larger ball a good walk away — this lab still exaggerates", "Inside the pea", "Invisible"], 1, "Order of magnitude, not a tape measure."),
      q("The next stars are…", ["Just beyond Neptune on the same table", "A jump of scale that makes planets vanish", "Inside the Moon", "UK counties"], 1, "Powers of ten."),
      q("This lab stops at the local galaxy hop because…", ["Galaxies are fake", "Honesty: one more jump and the screen is a lie of scale", "NASA forbids it", "It causes tides"], 1, "Keep it short."),
      q("If I scrub Scale jump past the solar system, what should disappear?", ["Only the labels", "Planets, if they were honest — they become a jump of scale, not a dusting on the same table", "The Sun, because stars have no fuel", "Greenwich, because Earth has no size"], 1, "Each hop hides a jump. Neighbouring stars are not Neptune’s neighbours."),
    ],
    why: [
      "A night walk from Greenwich is still Earth underfoot. A dark sky over Yosemite is still the same jump: one planet, then a star, then a gap you cannot draw honestly on a poster. Leeds does not sit next to Hawaii in kilometres the way a wallchart parks them. Scale is a skill. Wonder without a fake fly-through. The Kola borehole is a 12 km scratch on a 6371 km radius — even crust is thin — and that is still stop one. Stop two is the solar system in AU. Stop three is neighbouring stars in light years. Stop four would be a cartoon. UK GCSE diagrams and US planetarium posters both hide the jump. Your job is to say so. If Earth is a pea, the Sun is a much larger ball a good walk away. This lab still exaggerates. The next stars are not just beyond Neptune on the same table. That sentence is the whole point.",
      "Input is the Scale jump slider: 0 Earth, 1 solar system, 2 local stars. What moves: the camera’s hop, the unit on the readout, which objects are allowed to exist on screen. What does not: the fact of nested scales, the order of the hops, the honesty that each jump hides a factor. What is conserved: powers of ten as a way of thinking, not a tape measure. Stop 1: Earth in kilometres, Moon drawn close so you can see it — real gap is about 30 Earth-diameters. Stop 2: 1 AU is about 150 million km; planets at true size would be dust. Stop 3: neighbouring stars; units are light years; planets have no right to remain as dots you could name. The lie the model tells is every poster’s lie: one frame, several scales. We stop before a galaxy tour because one more jump and the screen is decoration. Keep it short. Order of magnitude, not a ruler. Greenwich underfoot is still stop one. If the class asks for the whole universe, the answer is no, not on this glass.",
      "Drag Scale jump from 0 to 2. Pause at each stop. Ask what vanished before you scrub on. Space does little here; the slider is the drive. Arrows still nudge time if anything is turning. L labels. R reset. P projector. No explode, no slice. Reset view if the hop has left the class in empty black. Name the unit at each stop: km, AU, light years. Then stop. No cartoon universe tour. The slider is labelled Scale jump. Do not skip a stop.",
      "If the hop will not run, keep three sentences. Earth is a sphere you can name, units in kilometres. The solar system is a jump to AU; planets would be dust at true size. Neighbouring stars are another jump; they are not just beyond Neptune. Every poster hides a jump. This lab refuses a galaxy fly-through because that would be a fourth lie. Powers of ten are the skill. Wonder stays. The tape measure does not pretend. Without the 3D view, a student should still refuse a cartoon galaxy tour and still name which unit belongs to which stop.",
    ],
    glossary: [
      { term: "Astronomical unit", exam: "AU", def: "Earth–Sun distance, about 150 million km. Stop 2’s unit." },
      { term: "Light year", def: "Distance light travels in one year. Stop 3’s unit. Not a time." },
      { term: "Power of ten", def: "A jump of scale by ×10, or many tens. The skill is naming the jump, not pretending one picture holds them all." },
      { term: "Order of magnitude", def: "A rough size class. If Earth is a pea, the Sun is not another pea. Exact millimetres are not the point." },
      { term: "Scale jump", def: "This lab’s slider: Earth, then solar system, then local stars. Each hop hides a factor." },
      { term: "Parsec", def: "About 3.26 light years. An exam unit for stellar distance. Not used as a stop here, but it is the same idea." },
      { term: "Local stars", def: "The neighbouring suns, not a galaxy tour. This lab stops there on purpose." },
    ],
    misconception: { claim: "Space pictures are a single scale.", truth: "Every poster hides a jump." },
    misconceptions: [
      mc("Space pictures are a single scale.", "Every poster hides a jump."),
      mc("The next stars sit just beyond Neptune on the same poster.", "That is a jump of scale that makes planets vanish. Light years, not AU."),
      mc("If Earth is a pea, the Sun is another pea beside it.", "The Sun is a much larger ball a good walk away. This lab still exaggerates."),
    ],
    cases: [{ slug: "greenwich", label: "Earth underfoot" }, { slug: "kola", label: "Even crust is thin" }],
    teacher: {
      script:
        "Start the Scale jump slider at Earth. A sphere you can name.\nScrub toward the solar system hop. Earth shrinks; the Sun becomes the object that reads.\nAsk what disappeared. Planets, if they were honest, are dust at this jump.\nScrub again to the local star field. Stop there.\nOne more jump and the screen is a lie of scale.\nEvery poster hides a jump. That is the misconception.\nIf Earth is a pea, the Sun is a much larger ball a good walk away — this lab still exaggerates.\nThe next stars are not just beyond Neptune on the same table.\nPowers of ten are the skill. Wonder without a fake fly-through.\nFinish in Check.",
      pitfalls: [
        "Endless zoom porn past the local stars.",
        "Leaving the class thinking one poster is one scale.",
        "Pea-Sun diagrams that put two peas side by side.",
      ],
    },
    sources: [{ label: "NASA scale" }],
    controls: { time: "none", extra: [{ key: "zoom", label: "Scale jump", min: 0, max: 2, step: 0.01, default: 0 }] },
  }),
  lab({
    slug: "geologic-time",
    title: "Geologic time",
    hook: "A spiral, not a calendar. Units in Ma. Life and continents are marks, not a cartoon parade.",
    objective: "Read deep time in millions of years and place a few honest marks.",
    realm: "planet",
    ages: ["KS3", "GCSE", "NGSS MS", "HS Earth Sci"],
    curriculum: ["KS3", "NGSS HS-ESS1-6", "GCSE"],
    steps: steps("The spiral is 4500 Ma to now.", "Scrub age. Marks: life, Pangaea, now.", "Humans are a hair at the end."),
    questions: [
      q("Ma means…", ["Minutes ago", "Million years", "Metres of altitude", "Magnetic"], 1, "Mega-annum."),
      q("Pangaea sits…", ["At 4500 Ma", "In the last few hundred Ma, not at Earth’s birth", "Tomorrow", "In the core"], 1, "Late Palaeozoic–Mesozoic."),
      q("Human history on this spiral is…", ["Half the coil", "A thin mark at the end", "The whole core", "Before life"], 1, "Humility."),
      q("If I set Time before present to 4500 Ma, where am I?", ["The K–Pg boundary", "Earth’s start on this spiral, not Pangaea and not humans", "The Cambrian explosion", "Grand Canyon tourism season"], 1, "4500 Ma is the birth mark. Pangaea is late. Humans are a hair at 0 Ma."),
    ],
    why: [
      "Grand Canyon walls are rock age. The hole is younger. That sentence is the whole fieldwork. Snowdonia’s slates are old; the path you walk is not 4500 Ma. Holderness till is a blink. Mississippi mud is a blink. Deep time is humility with a number, and the number is Ma — million years — not a school calendar of equal boxes. UK GCSE charts that give the Mesozoic as much wall as the Precambrian are the trap. US park signs that make dinosaurs and people neighbours are the same trap. Kola is a 12 km scratch. The Canyon visor is a young cut in old rock. Place a few honest marks: Earth forms, Cambrian, Pangaea, K–Pg, now. Life is a mark on the coil, not a cartoon parade. Humans are a hair at the end. Say that before anyone asks for us beside the dinosaurs.",
      "Input is Time before present, 0 to 4500 Ma. The coil is a log spiral so the late marks can still be seen. Linear time would crush Cambrian-to-now into a speck. What moves: the bead on the coil, the readout in Ma or ka. What does not: the order of the marks, the fact that 4500 Ma is Earth’s start on this diagram, the fact that humans are last. What is conserved: sequence, not equal spacing. Pangaea sits in the last few hundred Ma, late Palaeozoic to Mesozoic, not at Earth’s birth. Cambrian is about 540 Ma. K–Pg is 66 Ma. Now is a hair. The lie the model tells: a pretty helix, a fat bead, marks you could trip over. Real duration is not a staircase of equal treads. Equal-length era boxes on a wall chart are the other lie. The spiral is still a drawing. It is a better drawing than the boxes. Units stay Ma. Do not switch to biblical calendars, Hollywood timelines, or a parade of animals walking left to right as if time were a road.",
      "Drag Time before present from 4500 Ma to 0. Space still walks the coil. Arrows nudge it. L labels. R reset. P projector. No explode, no slice. Pause at Pangaea. Pause at K–Pg. Ask where humans go before you reveal the hair. If the class treats the boxes on their wall as equal, put the spiral next to that poster and let the lengths argue. Names on the marks, not a cartoon parade. The slider is labelled Time before present, units Ma. Walk slowly through the last 500 Ma so the hair at the end can be seen.",
      "If the spiral will not turn, keep the marks. Earth about 4500 Ma. Cambrian about 540 Ma. Pangaea in the last few hundred Ma, not at the start. K–Pg at 66 Ma. Humans a hair at the end. Ma means million years. Equal boxes on a wall chart lie. Grand Canyon walls are old rock; the hole is younger. That is enough to sit Check on paper, and enough to refuse a dinosaur-and-human handshake. Without the 3D view, a student should still place those five marks in order and still refuse equal boxes.",
    ],
    glossary: [
      { term: "Ma", exam: "Myr / million years ago", def: "Mega-annum: million years ago. The unit on this spiral. Not minutes, not metres." },
      { term: "ka", def: "Thousand years ago. The readout may drop into ka near the hair of now." },
      { term: "Deep time", def: "Earth history at geologic scale. A spiral, not a school calendar." },
      { term: "Pangaea", def: "Late Palaeozoic–Mesozoic supercontinent. A mark in the last few hundred Ma, not Earth’s starting position." },
      { term: "Cambrian", def: "About 540 Ma. A mark for early animal diversity, not the start of the planet." },
      { term: "K–Pg", exam: "K–T boundary", def: "About 66 Ma. End-Cretaceous. Not the end of time, and not where humans begin." },
      { term: "Log spiral", def: "A coil that gives late marks room. Linear time would crush the Phanerozoic into a speck." },
      { term: "Precambrian", def: "Most of the coil: from Earth’s start to the Cambrian. Wall charts usually under-draw it." },
    ],
    misconception: { claim: "Dinosaurs and humans overlap on a wall chart of equal boxes.", truth: "Boxes lie. The spiral does not." },
    misconceptions: [
      mc("Dinosaurs and humans overlap on a wall chart of equal boxes.", "Boxes lie. The spiral does not."),
      mc("Pangaea is how Earth started.", "Pangaea is late. 4500 Ma is the birth mark. Supercontinents come and go."),
      mc("The Grand Canyon hole is as old as the rock in the walls.", "Walls are rock age. The hole is younger. Deep time is not one number for both."),
    ],
    cases: [{ slug: "grand-canyon", label: "Grand Canyon time" }, { slug: "kola", label: "A 12 km scratch" }],
    teacher: {
      script:
        "Set Time before present to 4500 Ma. That is Earth’s start on this spiral.\nWalk the slider toward now. Units are Ma, million years, not a school calendar.\nPause at Pangaea. It sits in the last few hundred Ma, not at Earth’s birth.\nLife is a mark on the coil, not a cartoon parade.\nHumans are a hair at the end. Say that before anyone asks for dinosaurs beside us.\nEqual-length era boxes on a wall chart are the trap.\nBoxes lie. The spiral does not.\nGrand Canyon walls are rock age; the hole is younger.\nDeep time is humility with a number.\nFinish in Check.",
      pitfalls: [
        "Equal-length era boxes on the wall.",
        "Pangaea as Earth’s starting position.",
        "Letting dinosaurs and humans share a handshake on the same tread.",
      ],
    },
    sources: [{ label: "USGS geologic time" }, { label: "BGS" }],
    controls: { time: "none", extra: [{ key: "ageMa", label: "Time before present", min: 0, max: 4500, step: 10, unit: " Ma", default: 0 }] },
  }),
  lab({
    slug: "eclipses",
    title: "Eclipses",
    hook: "Umbra and penumbra are cones. The Moon’s 5° tilt is why most months miss.",
    objective: "Show umbra/penumbra and why a 5° lunar-orbit tilt makes eclipses rare.",
    realm: "planet",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "NGSS MS-ESS1-1"],
    steps: steps("Sun, Earth, Moon. Umbra dark, penumbra pale.", "Toggle 5° vs aligned.", "New/full every month. Eclipse only near a node."),
    questions: [
      q("The umbra is…", ["The faint outer shadow", "The dark core of the shadow", "A planet", "Albedo"], 1, "Total eclipse sits in umbra."),
      q("Eclipses are rare because…", ["The Moon is too small to ever hit", "The orbit is tilted ~5°, so the Moon usually misses the cone", "Clouds", "Time zones"], 1, "Nodes."),
      q("A lunar eclipse needs…", ["New Moon plus a node", "Full Moon plus a node", "Any crescent", "Perihelion only"], 1, "Earth between Sun and Moon, and aligned."),
      q("If I leave Eclipse alignment off, what happens at full Moon?", ["A lunar eclipse every time", "Usually a miss: the Moon slides above or below the cone", "The Sun goes out", "Snowdonia sees a solar eclipse and Yosemite does not"], 1, "New and full happen every month. An eclipse needs a node. The 5° tilt is why most months miss."),
    ],
    why: [
      "Snowdonia and Yosemite see the same phase on the same night. Eclipses are pickier. A full Moon over Eryri is geometry, not a promise of Earth’s shadow. A full Moon over Yosemite is the same triangle. Eclipse chasers wait for a node, not for every full. UK school trips still miss most months. US park night walks still miss most months. The skill is to split phase from eclipse. Phases are how much of the sunlit half faces us. Eclipses are alignment plus the 5° lunar-orbit tilt being near zero. Clouds are weather. Time zones are clocks. Neither is the cone. If you cannot say umbra versus penumbra, you cannot say why a total is a tunnel and a partial is a graze. Holderness does not get a private Moon. Miami does not get a different shadow. Same machine, rare hit.",
      "Input is a month on the slider, plus the Eclipse alignment toggle. Sun, Earth, Moon. The Moon runs a ring. Leave alignment off and the ring is tilted about 5° to the ecliptic. What moves: the Moon’s place, the cones if you are looking, whether a new or full sits near a node. What does not: the 5° unless you toggle it to zero, the fact of two cones, the fact that new and full happen every synodic month. What is conserved: half the Moon is always sunlit; umbra is the dark core; penumbra is the pale outer shadow. A solar eclipse needs new Moon plus a node — Moon between Sun and Earth. A lunar eclipse needs full Moon plus a node — Earth between Sun and Moon. The lie the model tells: Moon and Earth are huge beside their true gap; cones are fat enough to read from the back row; the orbit is a tidy hoop. Size is exaggerated on purpose. The tilt is the mechanism. Most months the Moon misses the cone. Every full Moon is not an eclipse. A crescent is not Earth’s shadow — that is a different lab’s trap, and it is still wrong here.",
      "Play the month. Space toggles play. Arrows nudge time. Speed 1×, 2×, 4×. Toggle Eclipse alignment off for the 5° miss, on once so the cones line up, then off again. L labels. R reset. P projector. No explode, no slice in the bar. Pause at new. Pause at full. Ask why next month fails before you toggle. Rarity is the lesson, not the special effect. The toggle is labelled Eclipse alignment. Off is the real 5°. On is the special-effect month. Use it once, not as the default.",
      "If the cones will not spin, keep the sentences. Umbra is the dark core. Penumbra is the partial shadow. The Moon’s orbit is tilted about 5°, so most months miss. New and full happen every month. An eclipse needs a node. Solar: new plus node. Lunar: full plus node. Snowdonia and Yosemite share the phase; they do not share an eclipse every month. Size in the kit is fat on purpose. That is enough for Check on paper. Without the 3D view, a student should still split phase from eclipse and still name the 5° tilt as the miss.",
    ],
    glossary: [
      { term: "Umbra", def: "Dark core of a shadow. A total eclipse sits here." },
      { term: "Penumbra", def: "Partial, paler shadow around the umbra. A graze, not the tunnel." },
      { term: "Node", def: "Where the Moon’s tilted orbit crosses the ecliptic. Eclipses need the Moon near a node." },
      { term: "Ecliptic", def: "The plane of Earth’s orbit around the Sun. The Moon’s orbit is tilted about 5° to it." },
      { term: "Orbital inclination", def: "The Moon’s ~5° tilt to the ecliptic. That is why eclipses are rare." },
      { term: "Solar eclipse", def: "New Moon plus a node. Moon between Sun and Earth. Umbra on the ground is a small track." },
      { term: "Lunar eclipse", def: "Full Moon plus a node. Earth between Sun and Moon. The Moon rides through Earth’s umbra." },
      { term: "Synodic month", def: "New to new, about 29.5 days. Phase clock. Not the eclipse clock." },
    ],
    misconception: { claim: "Every full Moon is an eclipse.", truth: "Need a node." },
    misconceptions: [
      mc("Every full Moon is an eclipse.", "Need a node."),
      mc("A crescent is Earth’s shadow on the Moon.", "A crescent is the Moon’s night side. Earth’s shadow is a lunar eclipse, and it is rare."),
      mc("The Moon is too small to ever cover the Sun.", "Angular size can match. The reason most months miss is the 5° tilt, not a tiny Moon."),
    ],
    cases: [{ slug: "snowdonia-moon", label: "Snowdonia Moon" }, { slug: "yosemite-moon", label: "Yosemite Moon" }],
    teacher: {
      script:
        "Play the month. Sun, Earth, Moon: umbra dark, penumbra pale.\nThe umbra is the dark core of the shadow. A total eclipse sits there.\nLeave Eclipse alignment off. The Moon’s orbit is tilted about 5°.\nNew and full happen every month. An eclipse needs a node.\nAsk why next month’s full Moon fails. It usually misses the cone.\nToggle Eclipse alignment on once so the cones line up.\nThen off again. Rarity is the lesson, not the special effect.\nEvery full Moon is not an eclipse. That is the misconception.\nA lunar eclipse needs full Moon plus a node. A solar eclipse needs new Moon plus a node.\nFinish in Check.",
      pitfalls: [
        "Crescent as Earth’s shadow.",
        "Teaching every full Moon as an eclipse.",
        "Saying the Moon is too small to ever hit, instead of naming the 5° tilt.",
      ],
    },
    sources: [{ label: "NASA eclipses" }],
    controls: { time: "month", toggles: [{ key: "align", label: "Eclipse alignment" }] },
  }),
  lab({
    slug: "tides",
    title: "Tides",
    hook: "Two bulges. Spring and neap are alignment, not emotion.",
    objective: "Show two tidal bulges and spring/neap with Moon–Sun alignment.",
    realm: "planet",
    ages: ["KS3", "GCSE", "NGSS MS"],
    curriculum: ["KS3", "GCSE coasts", "NGSS MS-ESS1-1"],
    steps: steps("Two bulges: toward the Moon and opposite.", "Play the month. Align Sun and Moon: spring. Right angle: neap.", "Sun is weaker but not zero."),
    questions: [
      q("Why two bulges?", ["Two Moons", "Gravity plus the orbiting-system’s inertia — a school two-bulge model", "Wind only", "Rivers"], 1, "Simplification flagged in teacher notes."),
      q("Spring tides occur when…", ["Only in spring season", "Sun and Moon pull along one line", "There is no Moon", "Earth stops"], 1, "New or full."),
      q("Neap tides are…", ["The largest range", "The smaller range, Sun and Moon at right angles", "Tsunamis", "Only in the UK"], 1, "Quarter moons."),
      q("If I pause when the Sun and Moon sit at right angles, the range is…", ["Spring — the bulges add", "Neap — the bulges fight, smaller range", "Zero, because the Moon has vanished", "A tsunami on Holderness"], 1, "Quadrature. Quarter moons. Neap is smaller, not zero, and not a season."),
    ],
    why: [
      "Holderness waves ride a tidal range. Estuaries even more. The Mississippi meets a modest Gulf tide and still dumps a delta; UK east-coast mudflats live on a larger clock. Spring and neap are alignment, not April. A Leeds student who thinks spring tide waits for daffodils will misread every tide table from the Humber to Miami. Yosemite has no sea, but the same Moon that pulls Holderness pulls a California coast twice a day. Hawaii sits in a different basin with a different range; the two-bulge idea still holds as the school start. Fieldwork on a UK beach is a timetable. Miss the range and you miss the spit, the mud, the harbour gate. The skill is two bulges, then syzygy versus quadrature. Wind is weather. Rivers are catchments. Neither is the second bulge.",
      "Input is a month. The Moon goes around. The Sun sits off-stage, weaker, not zero. Two bulges: one toward the Moon, one opposite. That opposite bulge is the school model — gravity plus the orbiting-system’s inertia — and the teacher notes flag the simplification. What moves: the Moon’s place, which way the fat water points, whether the Sun’s smaller pull adds or fights. What does not: the existence of two bulges, Earth’s spin as the thing that carries a coast through those bulges twice a day, in the simple picture. What is conserved: mass of water, the fortnightly spring–neap beat, the fact that new and full are both syzygy. Align Sun and Moon along one line: spring tide, larger range, twice a month, named for leaping, not the season. Right angles: neap, smaller range, quarter moons. The lie the model tells: water is a deformed mesh around a smooth globe; continents do not get in the way; real amphidromes, basins, and coastal funnelling are missing. Holderness and the Gulf are not the same range. The mechanism still starts here. Tsunamis are not tides. Wind setup is not the two-bulge clock.",
      "Play the month. Space toggles play. Arrows nudge time. Speed 1×, 2×, 4×. No extra slider. No toggle. L labels. R reset. P projector. No explode, no slice. Pause when the readout says spring — Sun and Moon aligned. Pause on neap — quadrature. Ask which phases give spring before you reveal: new or full, both. Quarter moons give neap. Reset if the class has named the season by accident. The month slider is the only clock. Watch the mesh deform; it is not a sticker. Name spring and neap from alignment, not from the calendar.",
      "If the bulges will not spin, keep the sentences. Two bulges: toward the Moon and opposite. Spring tide is larger range when Sun and Moon pull along one line, twice a month, not in April. Neap is smaller range at right angles. The Sun is weaker than the Moon here, but not zero. Holderness rides a real range. Gulf tides can be modest. This is a school two-bulge model, not a harbour forecast. That is enough for Check on paper.",
    ],
    glossary: [
      { term: "Spring tide", exam: "Syzygy tide", def: "Larger range. Sun and Moon pull along one line. New or full. Twice a month, not the season." },
      { term: "Neap tide", exam: "Quadrature tide", def: "Smaller range. Sun and Moon at right angles. Quarter moons." },
      { term: "Syzygy", def: "Sun, Moon, and Earth in one line. Spring tide. Exam word for the alignment." },
      { term: "Quadrature", def: "Sun and Moon at right angles as seen from Earth. Neap tide." },
      { term: "Tidal bulge", def: "A school picture: one bulge toward the Moon, one opposite. A simplification, flagged as such." },
      { term: "Tidal range", def: "High water minus low water. Springs large, neaps small. Coasts then reshape the number." },
      { term: "Semi-diurnal tide", def: "Two highs and two lows in about a day, in the simple spinning-through-bulges picture." },
    ],
    misconception: { claim: "Spring tides happen in April.", truth: "Spring as in leap, twice a month." },
    misconceptions: [
      mc("Spring tides happen in April.", "Spring as in leap, twice a month."),
      mc("There is only one bulge, the one facing the Moon.", "Two. Toward the Moon and opposite. The second is the school-model surprise."),
      mc("The Sun does not affect tides.", "Weaker than the Moon, not zero. Alignment is why springs beat neaps."),
    ],
    cases: [{ slug: "holderness", label: "Holderness coast" }, { slug: "mississippi", label: "Modest Gulf tides" }],
    teacher: {
      script:
        "Play the month. Two bulges: one toward the Moon, one opposite.\nThat two-bulge picture is a school model. Flag the simplification.\nWhen Sun and Moon pull along one line, the range is larger: spring tide.\nSpring as in leap, twice a month, not the season.\nAt right angles the bulges fight: neap tide, smaller range.\nThe Sun is weaker than the Moon here, but not zero.\nAsk which phase gives spring: new or full — both, syzygy.\nQuarter moons give neap.\nSpring tides do not wait for April. That is the trap.\nFinish in Check.",
      pitfalls: [
        "Season named spring.",
        "Only one bulge, facing the Moon.",
        "Calling a tsunami a tide, or wind setup the two-bulge clock.",
      ],
    },
    sources: [{ label: "NOAA tides" }, { label: "UKHO" }],
    controls: { time: "month" },
  }),
  lab({
    slug: "solar-altitude",
    title: "Solar altitude and sun path",
    hook: "A dome over a marked horizon. Date and latitude write the path. Noon altitude and day length fall out.",
    objective: "Read noon altitude and day length from a sun-path dome for London, Nairobi, New York.",
    realm: "planet",
    ages: ["KS3", "GCSE", "NGSS MS", "APES"],
    curriculum: ["KS3", "NGSS MS-ESS1-1", "GCSE"],
    steps: steps("Dome. Today’s path. London marker.", "Scrub date. Change latitude toward Nairobi.", "Noon altitude = 90° − |φ − δ|."),
    questions: [
      q("Noon solar altitude is lowest in London around…", ["June", "December", "March only", "Every day the same"], 1, "December solstice."),
      q("At the equator day length is…", ["0 in June", "Near 12 hours all year", "24 hours", "8 hours always"], 1, "Small seasonal swing."),
      q("Raising latitude in winter…", ["Raises noon Sun", "Lowers noon Sun and shortens the day", "Stops rotation", "Creates sunspots"], 1, "Geometry."),
      q("If I drag Latitude from 51.5° toward 0°, what happens to the path?", ["Noon Sun goes lower and the day collapses to polar night", "Noon Sun stays higher and day length sits nearer 12 h — Nairobi, not London", "The Sun starts orbiting Earth", "Miami and London swap hemispheres"], 1, "Latitude writes the path. Equator: high noon, near-12 h days. London: winter low and short."),
    ],
    why: [
      "London in December is a low noon and a short day. Miami still has a useful beam. Same dome idea. Different latitude. Leeds glasshouses plot hours above a height that plants can use. Florida growers plot the same curve with a different φ. Snowdonia fieldwork in June is a long arc; the same slope in December is a brief, low Sun. New York sits between London and Miami on that ladder. The skill is to read noon altitude and day length from a path, not from a weather app. Pairs with the calculator tool. A magnetic compass is not true south. Overhead Sun is not a global noon habit. If you cannot move latitude in your head from 51.5° to 0°, you cannot compare a UK playground with Nairobi, and you will keep saying the Sun is overhead everywhere at lunch.",
      "Input is latitude, plus the time slider that walks the Sun along the dome. Default latitude is 51.5°, London. The path is the day’s arc on a sky hemisphere over a marked horizon. Noon altitude is 90° minus the absolute difference of latitude and declination: 90° − |φ − δ|. Day length falls out of whether the path clears the horizon, and for how long. What moves: the Sun along the arc, the length of that arc when you change φ, the gnomon’s shadow. What does not: the formula, the fact of a horizon, the fact that overhead Sun only happens between the tropics, and not every day. What is conserved: spherical geometry. Raise latitude in winter: noon Sun drops, day shortens. Toward the equator: noon stays high, day length sits near 12 h. Polar extremes are a longer day or a night that will not end, depending on season, but this slider caps short of the pole. The lie the model tells: a small dome, a fat Sun, a toy gnomon, a teaching plinth instead of a real playground. The path is the lesson. The numbers on the readout are the lesson. Seasons still come from tilt; this lab aims the beam for one place.",
      "Leave Latitude near 51.5°. That is London. Play. Space toggles play. Arrows nudge the Sun along the path. Speed 1×, 2×, 4×. Drag Latitude toward 0° for Nairobi, or toward Miami’s band, or south. Read noon altitude and day length from the readout. L labels. R reset. P projector. No explode, no slice in the bar. Reset if the dome has walked off a useful latitude. True south is not a magnetic compass. The Latitude slider is the extra. The time slider walks the Sun on the dome. Read the gnomon shadow as well as the numbers.",
      "If the dome will not spin, keep the formula and the places. Noon altitude = 90° − |φ − δ|. London winter: low noon, short day. Equator: day length near 12 h, noon Sun high. Overhead at noon only between the tropics, and not every day. Raising latitude in winter lowers the Sun and shortens the day. Miami is not London. Snowdonia in June is not Snowdonia in December. That is enough for Check on paper, and enough to kill ‘the Sun is overhead everywhere at noon’.",
    ],
    glossary: [
      { term: "Solar altitude", exam: "Elevation angle", def: "Angle of the Sun above the horizon. Noon altitude is the day’s peak." },
      { term: "Sun path", def: "The day’s arc on the sky dome. Date and latitude write it." },
      { term: "Declination", def: "The latitude where the Sun is overhead at noon. It travels between 23.44°N and 23.44°S." },
      { term: "Noon altitude", def: "90° − |φ − δ|. School formula. φ is latitude, δ is declination." },
      { term: "Day length", def: "Hours the Sun is above the horizon. Near 12 h at the equator. A wide swing at London." },
      { term: "Gnomon", def: "A stick that casts a shadow. Shadow length is a readout of solar altitude." },
      { term: "Tropics", def: "23.44°N to 23.44°S. Overhead Sun lives only in this belt, and not every day." },
      { term: "Latitude", exam: "φ", def: "Angle from the equator. This lab’s slider. Default 51.5° is London." },
    ],
    misconception: { claim: "The Sun is overhead at noon everywhere.", truth: "Only between the tropics, and not every day." },
    misconceptions: [
      mc("The Sun is overhead at noon everywhere.", "Only between the tropics, and not every day."),
      mc("Day length is 12 hours everywhere, every day.", "Near 12 h at the equator. London swings from a short December to a long June."),
      mc("Raising latitude always makes the Sun higher.", "In winter it lowers noon Sun and shortens the day. Geometry, not a hill."),
    ],
    cases: [{ slug: "uk-daylength", label: "London day length" }, { slug: "florida-insolation", label: "New York / Miami" }],
    teacher: {
      script:
        "Leave Latitude near 51.5°. That is London.\nPlay. Watch the path on the dome. Read noon altitude and day length.\nThe Sun is overhead at noon only between the tropics, and not every day.\nThat is the misconception: overhead everywhere.\nScrub Latitude toward the equator, near Nairobi.\nDay length sits nearer 12 h. Noon Sun stays high.\nRaising latitude in winter lowers noon Sun and shortens the day.\nNoon altitude is 90° minus the absolute difference of latitude and declination.\nA magnetic compass is not true south. Say that once.\nFinish in Check.",
      pitfalls: [
        "Magnetic compass vs true south.",
        "Overhead Sun as a global noon habit.",
        "Forgetting that day length and noon altitude both move with latitude.",
      ],
    },
    sources: [{ label: "NOAA solar calculator" }],
    controls: {
      time: "year",
      extra: [{ key: "latitude", label: "Latitude", min: -60, max: 65, step: 0.5, unit: "°", default: 51.5 }],
    },
  }),
];
